'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const ctx={window:{},console};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root,'assets/warhammer-40k/imperial-dramatis-personae-v1.js'),'utf8'),ctx,{filename:'imperial-dramatis-personae-v1.js'});
const P=ctx.window.CafarronDramatisPersonaeV1;
if(!P)throw new Error('Archivum Personae register did not answer.');
const v=P.validate();
if(!v.allValid)throw new Error(`Personae validation failed: ${JSON.stringify(v)}`);
if(v.personae!==37)throw new Error(`Expected thirty-seven chronicle personae; received ${v.personae}.`);
const by=new Map(P.PERSONAE.map(p=>[p.id,p]));
const expected=['vishwa-love','karenov','lieutenant-mandrel','besorev','interrogator-javard','pontiff-montpclair','chancellor-ardenal','grand-reverend-grellholm','prefect-lorus','minister-heldforned','sergeant-maximillion-dewinter','lieutenant-abereneth','benson-pelcher','jerry-slassen','governor-talbor-varik','commissar-keeper-dren-solvik','domina-aestra-callen','harbour-master-gaston-selecton','jak-degravian-harbor','sergeant-vange','commissar-velraden','corporal-kathine','lieutenant-durak','private-cren','suitor-johnis','galladin-planetary-governor','stefan-galladin-heir','valen-galladin-aide','lord-commissar-galladin','commissar-cressus-argenetio','sister-alara','sister-exegete-halvenna-mord','canoness-deyra-solm','sister-arbentia-tenelja','magos-abraxas-8207','sister-bethany-pradaxa','mulvane-drenal'];
for(const id of expected)if(!by.has(id))throw new Error(`Missing chronicle persona ${id}.`);
for(const id of ['vishwa-love','karenov','lieutenant-mandrel','besorev'])if(!by.get(id).mapNodeIds.includes('node-kertora'))throw new Error(`${id} lost Kertora concordance.`);
for(const id of ['interrogator-javard','pontiff-montpclair'])if(!by.get(id).mapNodeIds.includes('node-jhasyiapan'))throw new Error(`${id} lost Jhasyi’apan concordance.`);
for(const id of ['chancellor-ardenal','grand-reverend-grellholm','prefect-lorus','minister-heldforned','sister-exegete-halvenna-mord','canoness-deyra-solm'])if(!by.get(id).mapNodeIds.includes('node-presteria'))throw new Error(`${id} lost Presteria concordance.`);
for(const id of ['sister-arbentia-tenelja','magos-abraxas-8207','sister-bethany-pradaxa'])if(!by.get(id).mapNodeIds.includes('node-pelzane'))throw new Error(`${id} lost Pelzane/Tenelja concordance.`);
for(const id of ['sergeant-maximillion-dewinter','lieutenant-abereneth'])if(!by.get(id).mapNodeIds.includes('node-panthes'))throw new Error(`${id} lost Panthes concordance.`);
for(const id of ['benson-pelcher','jerry-slassen','governor-talbor-varik','commissar-keeper-dren-solvik','domina-aestra-callen','commissar-cressus-argenetio','sister-alara'])if(!by.get(id).mapNodeIds.includes('node-new-presidio'))throw new Error(`${id} lost New Presidio concordance.`);
for(const id of ['harbour-master-gaston-selecton','jak-degravian-harbor','sergeant-vange','commissar-velraden','corporal-kathine','lieutenant-durak','private-cren','suitor-johnis','galladin-planetary-governor','stefan-galladin-heir','valen-galladin-aide','lord-commissar-galladin'])if(!by.get(id).mapNodeIds.includes('node-galladin'))throw new Error(`${id} lost Galladin concordance.`);
if(!/Critical casualty/i.test(by.get('vishwa-love').status)||/dead|killed/i.test(by.get('vishwa-love').status))throw new Error('Vishwa outcome was over-resolved beyond the attached chronicle.');
if(!/not established/i.test(by.get('besorev').status))throw new Error('Besorev survival uncertainty was lost.');
if(!/Alive when removed/i.test(by.get('pontiff-montpclair').status))throw new Error('Montpclair medicae status is over-resolved or missing.');
if(!/killed in action|death is explicitly/i.test(by.get('sergeant-maximillion-dewinter').status))throw new Error('Dewinter explicit death seal was weakened or lost.');
if(/killed|dead|missing in action/i.test(by.get('lieutenant-abereneth').status)||!/Active at latest attached testimony/i.test(by.get('lieutenant-abereneth').status))throw new Error('Abereneth later fate was over-resolved.');
for(const id of ['benson-pelcher','jerry-slassen'])if(/killed|dead|missing in action|retired/i.test(by.get(id).status)||!/Active at latest attached testimony/i.test(by.get(id).status))throw new Error(`${id} later outcome was invented beyond By Ink and Mandate.`);
for(const id of ['governor-talbor-varik','commissar-keeper-dren-solvik','domina-aestra-callen'])if(/killed|dead|missing in action|removed from office/i.test(by.get(id).status)||!/Active at latest attached testimony/i.test(by.get(id).status))throw new Error(`${id} later outcome was invented beyond Antegra Station.`);
for(const id of ['harbour-master-gaston-selecton','jak-degravian-harbor'])if(/killed|dead|missing in action|arrested|removed from office/i.test(by.get(id).status)||!/Active at latest attached testimony/i.test(by.get(id).status))throw new Error(`${id} later outcome was invented beyond A Harbormaster’s Hope.`);
if(/killed|dead|missing in action|corrupted/i.test(by.get('sergeant-vange').status)||!/Active at latest attached testimony/i.test(by.get('sergeant-vange').status))throw new Error('Vange later outcome was over-resolved.');
const vangeText=[by.get('sergeant-vange').standing,by.get('sergeant-vange').role,by.get('sergeant-vange').biography,by.get('sergeant-vange').doctrine].join(' ');if(/\b(blank|psyker|saint|pariah)\b/i.test(vangeText))throw new Error('Vange received an unsupported supernatural classification.');
if(!by.get('sergeant-vange').storyBeats.some(x=>/Neverborn/i.test(x.beat)&&/unexplained resistance/i.test(x.beat)))throw new Error('Vange lost the observed-but-unexplained Neverborn resistance testimony.');
if(!P.sourceHistory(by.get('sergeant-vange')).some(s=>/1ggo856/i.test(s.url)))throw new Error('Vange lost his Galladin Part-3 secondary chronicle seal.');
if(!by.get('sergeant-vange').storyBeats.some(x=>/Durak/i.test(x.beat)&&/Volkite/i.test(x.beat))||!by.get('sergeant-vange').storyBeats.some(x=>/rotating checkpoints/i.test(x.place)))throw new Error('Vange lost his Part-3 continuation testimony.');
if(/killed|dead|missing in action|executed/i.test(by.get('commissar-velraden').status)||!/Active at last direct appearance/i.test(by.get('commissar-velraden').status))throw new Error('Velraden later fate was invented.');
if(!by.get('commissar-velraden').storyBeats.some(x=>/tasked with carrying out/i.test(x.beat)&&/not directly depicted/i.test(x.beat)))throw new Error('Velraden execution-assignment uncertainty was lost.');
if(!/Executed following summary judgment/i.test(by.get('corporal-kathine').status)||!/death is explicitly reported/i.test(by.get('corporal-kathine').status))throw new Error('Kathine explicit execution seal was weakened or lost.');
if(!by.get('sergeant-vange').relationships.some(x=>/Kathine/i.test(x.name))||!by.get('corporal-kathine').relationships.some(x=>/Vange/i.test(x.name)))throw new Error('Vange and Kathine lost their direct command concordance.');
const durak=by.get('lieutenant-durak');
if(!/Lieutenant/.test(durak.rank)||!/Active at latest attached testimony/i.test(durak.status)||/killed|dead|missing in action/i.test(durak.status))throw new Error('Durak rank or unresolved later fate was corrupted.');
if(!durak.possessions.some(x=>/Volkite/i.test(x))||!durak.possessions.some(x=>/Cadian Meritorious Citation/i.test(x)))throw new Error('Durak lost the Volkite or citation testimony.');
if(!/Kerodan VII/i.test(durak.biography)||!/Durak’s own account/i.test(durak.sourceAuthority))throw new Error('Durak backstory lost its self-reported evidentiary boundary.');
if(!/formal command does not know/i.test(durak.biography)||!/open secret/i.test(durak.biography))throw new Error('Durak command-awareness contradiction was flattened instead of preserved.');
const cren=by.get('private-cren');
if(!/Private/.test(cren.rank)||!/Active at latest attached testimony/i.test(cren.status)||/killed|dead|missing in action|promoted/i.test(cren.status))throw new Error('Cren narrow enlisted record over-resolved his later life.');
const cressus=by.get('commissar-cressus-argenetio');
if(!/Active at latest direct testimony/i.test(cressus.status)||/killed|dead|missing in action/i.test(cressus.status))throw new Error('Cressus later fate was invented.');
if(!/Prescia/i.test(cressus.biography)||!/twenty-one/i.test(cressus.biography)||!/Umezeprel-Beta/i.test(cressus.biography)||!/founding Headmaster/i.test(cressus.biography))throw new Error('Cressus lost core Schola or campaign testimony.');
if(!cressus.storyBeats.some(x=>/High Presidio/i.test(x.place)&&/no arrival|not.*depicted/i.test(x.beat)))throw new Error('Cressus High Presidio destination was over-resolved into an arrival.');
const alara=by.get('sister-alara');
if(!/Active at latest direct testimony/i.test(alara.status)||!/Sister of Battle/i.test(alara.rank)||/killed|dead|missing in action/i.test(alara.status))throw new Error('Alara rank or later fate was corrupted.');
if(!/bodyguard and Ecclesiastical monitor/i.test(alara.role)||!alara.storyBeats.some(x=>/daily|Checked on Cressus daily/i.test(x.beat)))throw new Error('Alara lost her direct A’reef assignment testimony.');
if(/Alara (personally |herself )?(donated|contributed|provided).*(gene|genetic)/i.test(alara.biography)||alara.physicalHistory.some(x=>/donor|genetic-legacy|gene-offering/i.test(x)))throw new Error('Alara was falsely converted from collective Sororitas testimony into a personal genetic donor record.');
if(!cressus.relationships.some(x=>/Sister Alara/i.test(x.name))||!alara.relationships.some(x=>/Cressus/i.test(x.name)))throw new Error('Cressus and Alara lost their direct mission concordance.');
const halvenna=by.get('sister-exegete-halvenna-mord');
if(!/Dead by the time/i.test(halvenna.status)||!/stripped of rank, condemned/i.test(halvenna.status))throw new Error('Halvenna death or condemnation seal was weakened.');
if(!/conflict|conflicting/i.test(halvenna.biography)||!/sealed/i.test(halvenna.sourceAuthority))throw new Error('Halvenna fall was over-resolved beyond contradictory sealed testimony.');
if(!/disciple-authenticated appendix/i.test(halvenna.doctrine)||!/disciple/i.test(halvenna.sourceAuthority)||/Halvenna (wrote|authored).*life-preservation exception/i.test(halvenna.biography))throw new Error('Halvenna appendix authorship boundary was lost.');
if(!halvenna.storyBeats.some(x=>/Argent Sepulchre/i.test(x.beat))||!halvenna.affiliations.some(x=>/Adepta Sororitas/i.test(x)))throw new Error('Halvenna Sororitas elevation testimony was lost.');
const deyra=by.get('canoness-deyra-solm');
if(!/Serving as Canoness/i.test(deyra.status)||!/never directly appears/i.test(deyra.status)||/killed|dead|removed/i.test(deyra.status))throw new Error('Deyra direct-appearance or later-fate boundary was lost.');
if(!/exact planetary location not supplied/i.test(deyra.currentLocation)||!/rather than asserting physical residence/i.test(deyra.sourceAuthority))throw new Error('Deyra was assigned invented physical geography.');
if(!deyra.storyBeats.some(x=>/fourteen thousand/i.test(x.beat)&&/no personal action/i.test(x.beat)))throw new Error('Deyra inherited institutional reliquary irregularity was misattributed as her personal act.');
const arbentia=by.get('sister-arbentia-tenelja');
if(!/Active at latest direct testimony/i.test(arbentia.status)||/killed|dead|missing in action|promoted/i.test(arbentia.status))throw new Error('Arbentia later fate or rank was invented.');
if(!/petitioned repeatedly/i.test(arbentia.biography)||!arbentia.relationships.some(x=>/^Rix$/i.test(x.name))||!arbentia.storyBeats.some(x=>/patient survived|survived repeated/i.test(x.beat)))throw new Error('Arbentia lost her education, Rix or survivor testimony.');
const abraxas=by.get('magos-abraxas-8207');
if(!/Magos Biologis-Abstrator/i.test(abraxas.rank)||!/Active at latest direct appearance/i.test(abraxas.status)||/killed|dead|removed/i.test(abraxas.status))throw new Error('Abraxas rank or later fate was corrupted.');
if(!abraxas.relationships.some(x=>/Bethany Pradaxa/i.test(x.name))||!abraxas.storyBeats.some(x=>/cardiac crisis|emergency/i.test(x.beat)))throw new Error('Abraxas lost Tenelja clinical testimony.');
const bethany=by.get('sister-bethany-pradaxa');
if(!/Hospitaller Militant/i.test(bethany.rank)||!/Active at latest direct appearance/i.test(bethany.status)||/killed|dead|removed/i.test(bethany.status))throw new Error('Bethany rank or later fate was corrupted.');
if(!bethany.relationships.some(x=>/Abraxas 8207/i.test(x.name))||!bethany.storyBeats.some(x=>/urgent|stabilization/i.test(x.beat)))throw new Error('Bethany lost Tenelja clinical testimony.');
const mulvane=by.get('mulvane-drenal');
if(!/Active at latest attached life testimony/i.test(mulvane.status)||/killed|dead|retired|failed/i.test(mulvane.status))throw new Error('Mulvane later fate was invented.');
if(mulvane.mapNodeIds.length!==0||!/Sol System|Terra/i.test(mulvane.offMapConcordance||''))throw new Error('Mulvane was forced onto a Cafarron map node or lost his extra-sector concordance.');
if(!/fourteen Terran years/i.test(mulvane.biography)||!/twenty-five/i.test(mulvane.biography)||!/two decades/i.test(mulvane.biography)||!/twelve sons/i.test(mulvane.biography))throw new Error('Mulvane lost core age, service or lineage testimony.');
if(!mulvane.storyBeats.some(x=>/Terra approaches/i.test(x.place)&&/summoned specialist/i.test(x.beat)))throw new Error('Mulvane lost his inner-system navigation specialty.');
const johnis=by.get('suitor-johnis');
if(!/Active at latest direct testimony/i.test(johnis.status)||/killed|dead|missing in action/i.test(johnis.status))throw new Error('Johnis later fate was invented.');
if(!/served for decades/i.test(johnis.biography)||!/raised from childhood/i.test(johnis.biography)||!johnis.storyBeats.some(x=>/administered the poison/i.test(x.beat)))throw new Error('Johnis lost his steward-assassin life testimony.');
const galladinGovernor=by.get('galladin-planetary-governor');
if(!/Active at latest attached testimony/i.test(galladinGovernor.status)||/killed|dead|removed from office/i.test(galladinGovernor.status))throw new Error('Galladin governor later fate was invented.');
if(!galladinGovernor.physicalHistory.some(x=>/centuries/i.test(x))||!galladinGovernor.physicalHistory.some(x=>/throat implant|subsonic/i.test(x)))throw new Error('Galladin governor lost longevity or implant testimony.');
if(!/personal name is not supplied/i.test(galladinGovernor.sourceAuthority)||!/reported framing/i.test(galladinGovernor.sourceAuthority))throw new Error('Galladin governor title-only or framing boundary was lost.');
if(/Kathine|Vange/i.test([galladinGovernor.biography,...galladinGovernor.storyBeats.map(x=>x.beat)].join(' ')))throw new Error('Galladin governor was speculatively tied to a separately recorded frontline persona.');
const stefan=by.get('stefan-galladin-heir');
if(!/Poisoned at latest direct testimony/i.test(stefan.status)||/(dead|killed|executed)|death is (established|confirmed)/i.test(stefan.status))throw new Error('Stefan poisoning was over-resolved into a confirmed death.');
if(!stefan.storyBeats.some(x=>/poison/i.test(x.beat)&&/not.*observ|before.*observ/i.test(x.beat)))throw new Error('Stefan lost the poisoned-but-unwitnessed outcome boundary.');
const valen=by.get('valen-galladin-aide');
if(!/Active at latest direct appearance/i.test(valen.status)||/killed|dead|removed/i.test(valen.status))throw new Error('Valen narrow political record over-resolved his later life.');
const lordCommissar=by.get('lord-commissar-galladin');
if(!/Active at latest direct appearance/i.test(lordCommissar.status)||!/personal name/i.test(lordCommissar.sourceAuthority)||/Kathine|Vange/i.test(lordCommissar.biography))throw new Error('Galladin Lord Commissar title-only or non-linkage boundary was lost.');
if(!johnis.relationships.some(x=>/Planetary Governor/i.test(x.name))||!galladinGovernor.relationships.some(x=>/Sui’tor Johnis/i.test(x.name)))throw new Error('Johnis and the Galladin governor lost their household concordance.');
if(!johnis.relationships.some(x=>/^Stefan$/i.test(x.name))||!stefan.relationships.some(x=>/Johnis/i.test(x.name)))throw new Error('Johnis and Stefan lost their direct assassination concordance.');
if(!by.get('sergeant-vange').relationships.some(x=>/Lieutenant Durak/i.test(x.name))||!durak.relationships.some(x=>/Sergeant Vange/i.test(x.name)))throw new Error('Vange and Durak lost their direct field concordance.');
if(!by.get('sergeant-vange').relationships.some(x=>/Private Cren/i.test(x.name))||!cren.relationships.some(x=>/Sergeant Vange/i.test(x.name)))throw new Error('Vange and Cren lost their direct command concordance.');
if(!by.get('harbour-master-gaston-selecton').relationships.some(x=>/^Jak$/i.test(x.name))||!by.get('jak-degravian-harbor').relationships.some(x=>/Gaston/i.test(x.name)))throw new Error('Gaston and Jak lost their direct Degravian Harbor concordance.');
if(!/(served as a sked captain|former sked captain)/i.test(by.get('harbour-master-gaston-selecton').biography)||!by.get('harbour-master-gaston-selecton').affiliations.some(x=>/Degravian Harbor/i.test(x)))throw new Error('Gaston lost his sked-captain history or harbor authority.');
if(!by.get('benson-pelcher').relationships.some(x=>/Jerry Slassen/i.test(x.name))||!by.get('jerry-slassen').relationships.some(x=>/Benson Pelcher/i.test(x.name)))throw new Error('Benson and Jerry lost their mutual Channel 93-H Sigma concordance.');
if(!by.get('benson-pelcher').affiliations.some(x=>/Channel 93-H Sigma/i.test(x))||!by.get('jerry-slassen').affiliations.some(x=>/Channel 93-H Sigma/i.test(x)))throw new Error('New Presidio channel affiliation was lost.');
const varik=by.get('governor-talbor-varik');
if(!varik.physicalHistory.some(x=>/more than two centuries/i.test(x))||!varik.physicalHistory.some(x=>/rejuvenant|vivification|marrow/i.test(x)))throw new Error('Varik longevity testimony lost its explicit two-century medicae basis.');
if(!varik.relationships.some(x=>/House Varik/i.test(x.name))||!varik.relationships.some(x=>/High Presidio/i.test(x.name)))throw new Error('Varik dynastic or planetary-command concordance is incomplete.');
if(!by.get('commissar-keeper-dren-solvik').affiliations.some(x=>/Securities Advisory Board/i.test(x))||!by.get('domina-aestra-callen').affiliations.some(x=>/Ecclesiarchy/i.test(x)))throw new Error('Antegra institutional roles are incomplete.');
if(!/Interrogator/.test(by.get('interrogator-javard').rank)||!by.get('interrogator-javard').affiliations.some(x=>/Kelford del Blank/i.test(x)))throw new Error('Javard inquisitorial service seal is incomplete.');
const g=by.get('grand-reverend-grellholm');
if(!g.physicalHistory.some(x=>/xenos-derived|xenos derivatives/i.test(x))||!g.physicalHistory.some(x=>/wholly human|human Imperial alternative/i.test(x)))throw new Error('Grellholm Prolong provenance testimony is incomplete.');
if(g.physicalHistory.some(x=>/administered|received the wholly human|underwent the wholly human/i.test(x)))throw new Error('Grellholm treatment administration was invented beyond the chronicle.');
const exactSources=new Map([
 ['chancellor-ardenal','1vfnma7'],['grand-reverend-grellholm','1vfnma7'],['prefect-lorus','1vfnma7'],['minister-heldforned','1vfnma7'],['sister-exegete-halvenna-mord','1vfnma7'],['canoness-deyra-solm','1vfnma7'],
 ['sergeant-maximillion-dewinter','1msi8aa'],['lieutenant-abereneth','1msi8aa'],
 ['benson-pelcher','1lga6is'],['jerry-slassen','1lga6is'],
 ['commissar-cressus-argenetio','1ovtfru'],['sister-alara','1ovtfru'],
 ['sister-arbentia-tenelja','1kvp2hx'],['magos-abraxas-8207','1kvp2hx'],['sister-bethany-pradaxa','1kvp2hx'],['mulvane-drenal','1kyqzh1'],
 ['governor-talbor-varik','1lr8fmy'],['commissar-keeper-dren-solvik','1lr8fmy'],['domina-aestra-callen','1lr8fmy'],
 ['harbour-master-gaston-selecton','1ggo76o'],['jak-degravian-harbor','1ggo76o'],
 ['sergeant-vange','1fakl6i'],['commissar-velraden','1fakl6i'],['corporal-kathine','1fakl6i'],['lieutenant-durak','1ggo856'],['private-cren','1ggo856'],
 ['suitor-johnis','1gkv2sj'],['galladin-planetary-governor','1gkv2sj'],['stefan-galladin-heir','1gkv2sj'],['valen-galladin-aide','1gkv2sj'],['lord-commissar-galladin','1gkv2sj']
]);
for(const[id,post]of exactSources)if(!new RegExp(`/comments/${post}/`,'i').test(by.get(id).source.url))throw new Error(`${id} lost its exact chronicle seal.`);
for(const p of P.PERSONAE){for(const s of P.sourceHistory(p))if(!/^https:\/\/www\.reddit\.com\/r\/EmperorProtects\/comments\/[a-z0-9]+\//i.test(s.url))throw new Error(`${p.id} lacks an EmperorProtects chronicle route.`);if(!p.storyBeats.length||!p.relationships.length)throw new Error(`${p.id} lacks narrative or relationship depth.`)}
console.log(JSON.stringify({personae:v.personae,kertora:4,jhasyiapan:2,presteria:6,panthes:2,newPresidioBroadcast:2,highPresidioSchola:2,tenelja:3,solExtraSector:1,antegra:3,galladinHarbor:2,galladinThrone:10,galladinHousehold:5,multiChroniclePersonae:1,sourceSealed:v.allSourceSealed,allValid:v.allValid},null,2));
