'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const ctx={window:{},console};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root,'assets/warhammer-40k/imperial-dramatis-personae-v1.js'),'utf8'),ctx,{filename:'imperial-dramatis-personae-v1.js'});
const P=ctx.window.CafarronDramatisPersonaeV1;if(!P)throw new Error('Archivum Personae register did not answer.');
const v=P.validate();if(!v.allValid)throw new Error(`Personae validation failed: ${JSON.stringify(v)}`);if(v.personae!==50)throw new Error(`Expected fifty chronicle personae; received ${v.personae}.`);
const by=new Map(P.PERSONAE.map(p=>[p.id,p]));
const expected=['vishwa-love','karenov','lieutenant-mandrel','besorev','interrogator-javard','pontiff-montpclair','chancellor-ardenal','grand-reverend-grellholm','prefect-lorus','minister-heldforned','sergeant-maximillion-dewinter','lieutenant-abereneth','benson-pelcher','jerry-slassen','governor-talbor-varik','commissar-keeper-dren-solvik','domina-aestra-callen','harbour-master-gaston-selecton','jak-degravian-harbor','sergeant-vange','commissar-velraden','corporal-kathine','lieutenant-durak','private-cren','suitor-johnis','galladin-planetary-governor','stefan-galladin-heir','valen-galladin-aide','lord-commissar-galladin','commissar-cressus-argenetio','sister-alara','sister-exegete-halvenna-mord','canoness-deyra-solm','sister-arbentia-tenelja','magos-abraxas-8207','sister-bethany-pradaxa','mulvane-drenal','doctor-reinhold-vigilant-shade','doc-finkey-vigilant-shade','inquisitor-atwell-zavoner','lieutenant-hendrick-laar','magos-elebendentis-zabrin','hans-vigilant-shade','matron-lagas-atrovald','lord-inquisitor-predulum-termuth','technician-prite-vallimere','technician-darcelle-vallimere','technician-renault-vallimere','academy-headmaster-vallimere','interrogator-iral-vane'];
if(expected.length!==50||new Set(expected).size!==50)throw new Error('Expected-persona fixture is malformed.');for(const id of expected)if(!by.has(id))throw new Error(`Missing chronicle persona ${id}.`);if(by.size!==50)throw new Error(`Unexpected persona count in map: ${by.size}.`);
const nodeGroups={
 'node-kertora':['vishwa-love','karenov','lieutenant-mandrel','besorev'],
 'node-jhasyiapan':['interrogator-javard','pontiff-montpclair'],
 'node-presteria':['chancellor-ardenal','grand-reverend-grellholm','prefect-lorus','minister-heldforned','sister-exegete-halvenna-mord','canoness-deyra-solm'],
 'node-panthes':['sergeant-maximillion-dewinter','lieutenant-abereneth'],
 'node-new-presidio':['benson-pelcher','jerry-slassen','governor-talbor-varik','commissar-keeper-dren-solvik','domina-aestra-callen','commissar-cressus-argenetio','sister-alara'],
 'node-pelzane':['sister-arbentia-tenelja','magos-abraxas-8207','sister-bethany-pradaxa'],
 'node-galladin':['harbour-master-gaston-selecton','jak-degravian-harbor','sergeant-vange','commissar-velraden','corporal-kathine','lieutenant-durak','private-cren','suitor-johnis','galladin-planetary-governor','stefan-galladin-heir','valen-galladin-aide','lord-commissar-galladin']};
for(const[node,ids]of Object.entries(nodeGroups))for(const id of ids)if(!by.get(id).mapNodeIds.includes(node))throw new Error(`${id} lost ${node} concordance.`);
if(!/Critical casualty/i.test(by.get('vishwa-love').status)||/dead|killed/i.test(by.get('vishwa-love').status))throw new Error('Vishwa outcome over-resolved.');if(!/not established/i.test(by.get('besorev').status))throw new Error('Besorev uncertainty lost.');if(!/Alive when removed/i.test(by.get('pontiff-montpclair').status))throw new Error('Montpclair status corrupted.');if(!/killed in action|death is explicitly/i.test(by.get('sergeant-maximillion-dewinter').status))throw new Error('Dewinter death seal lost.');
const vange=by.get('sergeant-vange'),vangeText=[vange.standing,vange.role,vange.biography,vange.doctrine].join(' ');if(/\b(blank|psyker|saint|pariah)\b/i.test(vangeText)||!vange.storyBeats.some(x=>/Neverborn/i.test(x.beat)&&/unexplained resistance/i.test(x.beat)))throw new Error('Vange supernatural boundary corrupted.');if(!P.sourceHistory(vange).some(s=>/1ggo856/i.test(s.url)))throw new Error('Vange Part-3 seal lost.');
if(!/Executed following summary judgment/i.test(by.get('corporal-kathine').status))throw new Error('Kathine execution seal lost.');const durak=by.get('lieutenant-durak');if(!durak.possessions.some(x=>/Volkite/i.test(x))||!/Durak’s own account/i.test(durak.sourceAuthority))throw new Error('Durak relic or testimony boundary lost.');if(!/Active at latest attached testimony/i.test(by.get('private-cren').status))throw new Error('Cren later state corrupted.');
const cressus=by.get('commissar-cressus-argenetio');if(!/Prescia/i.test(cressus.biography)||!/Umezeprel-Beta/i.test(cressus.biography)||!/founding Headmaster/i.test(cressus.biography))throw new Error('Cressus core record lost.');const alara=by.get('sister-alara');if(!/bodyguard and Ecclesiastical monitor/i.test(alara.role)||alara.physicalHistory.some(x=>/donor|genetic-legacy|gene-offering/i.test(x)))throw new Error('Alara testimony boundary lost.');
const halvenna=by.get('sister-exegete-halvenna-mord');if(!/Dead by the time/i.test(halvenna.status)||!/disciple-authenticated appendix/i.test(halvenna.doctrine)||!/conflict|conflicting/i.test(halvenna.biography))throw new Error('Halvenna historical boundary lost.');const deyra=by.get('canoness-deyra-solm');if(!/never directly appears/i.test(deyra.status)||!/exact planetary location not supplied/i.test(deyra.currentLocation))throw new Error('Deyra title/geography boundary lost.');
const arbentia=by.get('sister-arbentia-tenelja');if(!arbentia.relationships.some(x=>/^Rix$/i.test(x.name))||!/petitioned repeatedly/i.test(arbentia.biography))throw new Error('Arbentia testimony lost.');if(!/Magos Biologis-Abstrator/i.test(by.get('magos-abraxas-8207').rank)||!/Hospitaller Militant/i.test(by.get('sister-bethany-pradaxa').rank))throw new Error('Tenelja specialist ranks lost.');
const mulvane=by.get('mulvane-drenal');if(mulvane.mapNodeIds.length||!/Sol System|Terra/i.test(mulvane.offMapConcordance)||!/fourteen Terran years/i.test(mulvane.biography)||!/twelve sons/i.test(mulvane.biography))throw new Error('Mulvane extra-sector testimony lost.');
for(const id of ['doctor-reinhold-vigilant-shade','doc-finkey-vigilant-shade','inquisitor-atwell-zavoner','lieutenant-hendrick-laar','magos-elebendentis-zabrin','hans-vigilant-shade']){const p=by.get(id);if(p.mapNodeIds.length||!/Installation Theta-99/i.test(p.offMapConcordance||''))throw new Error(`${id} VIGILANT concordance corrupted.`)}
if(P.sourceHistory(by.get('doctor-reinhold-vigilant-shade')).length!==4||P.sourceHistory(by.get('doc-finkey-vigilant-shade')).length!==4||P.sourceHistory(by.get('inquisitor-atwell-zavoner')).length!==4||P.sourceHistory(by.get('magos-elebendentis-zabrin')).length!==2||P.sourceHistory(by.get('hans-vigilant-shade')).length!==3)throw new Error('VIGILANT multi-chronicle provenance lost.');if(!/Stasis-preserved/i.test(by.get('hans-vigilant-shade').status)||/confirmed dead|recovered|resurrected/i.test(by.get('hans-vigilant-shade').status))throw new Error('Hans stasis state over-resolved.');
const johnis=by.get('suitor-johnis'),gov=by.get('galladin-planetary-governor'),stefan=by.get('stefan-galladin-heir');if(!/raised from childhood/i.test(johnis.biography)||!johnis.storyBeats.some(x=>/Administered the poison/i.test(x.beat)))throw new Error('Johnis life testimony lost.');if(!/reported framing/i.test(gov.sourceAuthority)||/Kathine|Vange/i.test([gov.biography,...gov.storyBeats.map(x=>x.beat)].join(' ')))throw new Error('Galladin governor testimony was flattened across chronicles.');if(!/Poisoned at latest direct testimony/i.test(stefan.status)||/\b(dead|killed|executed)\b/i.test(stefan.status))throw new Error('Stefan poisoning over-resolved.');if(!/personal name/i.test(by.get('lord-commissar-galladin').sourceAuthority))throw new Error('Galladin Lord Commissar title-only boundary lost.');
const matron=by.get('matron-lagas-atrovald'),predulum=by.get('lord-inquisitor-predulum-termuth');for(const p of [matron,predulum])if(p.mapNodeIds.length||!/Spire Methelium Beta/i.test(p.offMapConcordance||''))throw new Error(`${p.id} Interlocutum geography corrupted.`);if(!/Keeper of Contextual Truths/i.test(matron.rank)||!/preserv/i.test(matron.doctrine))throw new Error('Atrovald office or preservation doctrine lost.');if(!/at least seven/i.test(predulum.sourceAuthority)||!/uncertain whether|false exact count|precise total/i.test([predulum.biography,predulum.sourceAuthority].join(' ')))throw new Error('Predulum sanitization uncertainty flattened.');
const trio=['technician-prite-vallimere','technician-darcelle-vallimere','technician-renault-vallimere'];for(const id of trio){const p=by.get(id);if(p.mapNodeIds.length||!/exact world and system not supplied/i.test(p.offMapConcordance||''))throw new Error(`${id} received invented Academy geography.`);if(!/Tenured strategic professor/i.test(p.rank)||!/House Vallimere member/i.test(p.rank))throw new Error(`${id} lost signed House/professor state.`);if(!/collective|individual mapping|individual alias/i.test(p.sourceAuthority))throw new Error(`${id} received unsupported individual Admiral alias.`)}
const prite=by.get('technician-prite-vallimere');if(!/father died/i.test(prite.biography)||!/(home.*console|private simulation console)/i.test(prite.biography))throw new Error('Prite founding-console testimony lost.');if(!by.get('technician-renault-vallimere').storyBeats.some(x=>/Hive Fleet/i.test(x.beat)))throw new Error('Renault Hive Fleet testimony lost.');const headmaster=by.get('academy-headmaster-vallimere');if(!/personal name.*not supplied/i.test(headmaster.sourceAuthority)||!headmaster.storyBeats.some(x=>/permanent induction|House membership/i.test(x.beat)))throw new Error('Headmaster title-only or induction evidence lost.');const vane=by.get('interrogator-iral-vane');if(!/Interrogator-Senior Grade/i.test(vane.rank)||!vane.storyBeats.some(x=>/Edward/i.test(x.beat)&&/drugged|unconscious/i.test(x.beat))||!vane.relationships.some(x=>/Belfran Hellfrost/i.test(x.name)))throw new Error('Iral Vane undercover testimony lost.');
const exactNew=new Map([['matron-lagas-atrovald','1p99lab'],['lord-inquisitor-predulum-termuth','1p99lab'],['technician-prite-vallimere','1owwykd'],['technician-darcelle-vallimere','1owwykd'],['technician-renault-vallimere','1owwykd'],['academy-headmaster-vallimere','1owwykd'],['interrogator-iral-vane','1owwykd']]);for(const[id,post]of exactNew)if(!by.get(id).source.url.includes(`/comments/${post}/`))throw new Error(`${id} lost exact new chronicle seal.`);
for(const p of P.PERSONAE){for(const s of P.sourceHistory(p))if(!/^https:\/\/www\.reddit\.com\/r\/EmperorProtects\/comments\/[a-z0-9]+\//i.test(s.url)||s.status!=='verified')throw new Error(`${p.id} lacks a verified EmperorProtects seal.`);if(!p.storyBeats.length||!p.relationships.length)throw new Error(`${p.id} lacks narrative or relationship depth.`)}
console.log(JSON.stringify({personae:v.personae,interlocutum:2,vallimereAcademy:5,sourceSealed:v.allSourceSealed,allValid:v.allValid},null,2));
