package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 014: fleet responders travel through the shared NPC transit engine before and after on-scene work. */
public final class FleetResponseTransitSchema {
    private FleetResponseTransitSchema() { }

    public static List<String> statements() {
        return List.of(
                "ALTER TABLE fleet_response_operation ADD COLUMN response_phase TEXT NOT NULL DEFAULT 'WAITING' CHECK(response_phase IN ('WAITING','OUTBOUND','ON_SCENE','RETURNING','COMPLETE','FAILED','CANCELLED'))",
                "ALTER TABLE fleet_response_operation ADD COLUMN attempt_number INTEGER NOT NULL DEFAULT 0 CHECK(attempt_number >= 0)",
                "ALTER TABLE fleet_response_operation ADD COLUMN materials_committed INTEGER NOT NULL DEFAULT 0 CHECK(materials_committed IN (0,1))",
                "ALTER TABLE fleet_response_operation ADD COLUMN responder_origin_location_id TEXT",
                "ALTER TABLE fleet_response_operation ADD COLUMN outbound_started_tick INTEGER CHECK(outbound_started_tick >= 0)",
                "ALTER TABLE fleet_response_operation ADD COLUMN arrived_tick INTEGER CHECK(arrived_tick >= 0)",
                "ALTER TABLE fleet_response_operation ADD COLUMN return_started_tick INTEGER CHECK(return_started_tick >= 0)",
                "ALTER TABLE fleet_response_operation ADD COLUMN responder_returned_tick INTEGER CHECK(responder_returned_tick >= 0)",

                "UPDATE fleet_response_operation SET response_phase=CASE status WHEN 'COMPLETE' THEN 'COMPLETE' WHEN 'FAILED' THEN 'FAILED' WHEN 'CANCELLED' THEN 'CANCELLED' WHEN 'ACTIVE' THEN 'ON_SCENE' ELSE 'WAITING' END,materials_committed=CASE WHEN status='COMPLETE' THEN 1 ELSE 0 END,arrived_tick=CASE WHEN status='ACTIVE' THEN updated_tick ELSE arrived_tick END,responder_returned_tick=CASE WHEN status='COMPLETE' THEN completed_tick ELSE responder_returned_tick END",

                "CREATE TABLE fleet_response_transit_leg (leg_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, operation_id TEXT NOT NULL, responder_npc_vessel_id TEXT NOT NULL, attempt_number INTEGER NOT NULL CHECK(attempt_number > 0), leg_type TEXT NOT NULL CHECK(leg_type IN ('OUTBOUND','RETURN')), status TEXT NOT NULL CHECK(status IN ('PREPARING','IN_TRANSIT','ARRIVED','FAILED','CANCELLED')), start_location_id TEXT NOT NULL, end_location_id TEXT NOT NULL, route_ticks_required INTEGER NOT NULL CHECK(route_ticks_required >= 1), started_tick INTEGER NOT NULL CHECK(started_tick >= 0), arrived_tick INTEGER CHECK(arrived_tick >= 0), completed_tick INTEGER CHECK(completed_tick >= 0), UNIQUE(operation_id,attempt_number,leg_type), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(operation_id) REFERENCES fleet_response_operation(operation_id), FOREIGN KEY(responder_npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id), FOREIGN KEY(start_location_id) REFERENCES world_location(location_id), FOREIGN KEY(end_location_id) REFERENCES world_location(location_id))",
                "CREATE INDEX fleet_response_transit_leg_status_index ON fleet_response_transit_leg(world_id,status,started_tick)",
                "CREATE TABLE fleet_response_transit_encounter (encounter_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, operation_id TEXT NOT NULL, leg_id TEXT NOT NULL, responder_npc_vessel_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), FOREIGN KEY(encounter_id) REFERENCES world_encounter(encounter_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(operation_id) REFERENCES fleet_response_operation(operation_id), FOREIGN KEY(leg_id) REFERENCES fleet_response_transit_leg(leg_id), FOREIGN KEY(responder_npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id))",
                "CREATE INDEX fleet_response_transit_encounter_tick_index ON fleet_response_transit_encounter(world_id,tick_sequence DESC)",

                "CREATE VIEW fleet_response_dispatch_plan AS SELECT o.operation_id,o.world_id,o.assigned_npc_vessel_id responder_npc_vessel_id,v.current_location_id start_location_id,o.target_location_id end_location_id,MAX(2,MIN(24,2+ABS(start_location.ring-target_location.ring)/8+ABS(start_location.location_level-target_location.location_level))) route_ticks_required FROM fleet_response_operation o JOIN npc_vessel v ON v.npc_vessel_id=o.assigned_npc_vessel_id JOIN world_location start_location ON start_location.location_id=v.current_location_id JOIN world_location target_location ON target_location.location_id=o.target_location_id WHERE o.status='ACTIVE' AND o.assigned_npc_vessel_id IS NOT NULL",
                "CREATE VIEW fleet_response_return_plan AS SELECT o.operation_id,o.world_id,o.assigned_npc_vessel_id responder_npc_vessel_id,v.current_location_id start_location_id,home.location_id end_location_id,MAX(2,MIN(24,2+ABS(start_location.ring-home_location.ring)/8+ABS(start_location.location_level-home_location.location_level))) route_ticks_required FROM fleet_response_operation o JOIN npc_vessel v ON v.npc_vessel_id=o.assigned_npc_vessel_id JOIN world_station home ON home.station_id=v.home_station_id JOIN world_location start_location ON start_location.location_id=v.current_location_id JOIN world_location home_location ON home_location.location_id=home.location_id WHERE o.status='ACTIVE' AND o.assigned_npc_vessel_id IS NOT NULL",

                "DROP TRIGGER IF EXISTS fleet_response_assigned",
                "CREATE TRIGGER fleet_response_assigned AFTER UPDATE OF assigned_npc_vessel_id ON fleet_response_operation WHEN NEW.assigned_npc_vessel_id IS NOT NULL AND NEW.status='ACTIVE' AND (OLD.assigned_npc_vessel_id IS NULL OR OLD.assigned_npc_vessel_id<>NEW.assigned_npc_vessel_id) BEGIN "
                        + "UPDATE fleet_response_operation SET response_phase='OUTBOUND',attempt_number=attempt_number+1,responder_origin_location_id=(SELECT start_location_id FROM fleet_response_dispatch_plan WHERE operation_id=NEW.operation_id),outbound_started_tick=NEW.updated_tick,arrived_tick=NULL,return_started_tick=NULL,responder_returned_tick=NULL WHERE operation_id=NEW.operation_id; "
                        + "UPDATE npc_vessel SET mission_id=NULL,destination_location_id=NEW.target_location_id,status='PREPARING',route_progress=0,route_ticks_required=(SELECT route_ticks_required FROM fleet_response_dispatch_plan WHERE operation_id=NEW.operation_id),last_tick=NEW.updated_tick WHERE npc_vessel_id=NEW.assigned_npc_vessel_id; "
                        + "INSERT OR IGNORE INTO fleet_response_transit_leg(leg_id,world_id,operation_id,responder_npc_vessel_id,attempt_number,leg_type,status,start_location_id,end_location_id,route_ticks_required,started_tick) SELECT NEW.operation_id||':outbound:'||o.attempt_number,NEW.world_id,NEW.operation_id,NEW.assigned_npc_vessel_id,o.attempt_number,'OUTBOUND','PREPARING',o.responder_origin_location_id,NEW.target_location_id,v.route_ticks_required,NEW.updated_tick FROM fleet_response_operation o JOIN npc_vessel v ON v.npc_vessel_id=NEW.assigned_npc_vessel_id WHERE o.operation_id=NEW.operation_id; "
                        + "INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) VALUES (NEW.operation_id||':assigned:'||NEW.updated_tick,NEW.world_id,NEW.operation_id,NEW.updated_tick,'ASSIGNED','A recovery vessel was assigned and began outbound departure checks.'); END",

                "CREATE TRIGGER fleet_response_responder_departed AFTER UPDATE OF status ON npc_vessel WHEN NEW.status='IN_TRANSIT' AND OLD.status='PREPARING' AND EXISTS (SELECT 1 FROM fleet_response_operation o WHERE o.assigned_npc_vessel_id=NEW.npc_vessel_id AND o.status='ACTIVE' AND o.response_phase IN ('OUTBOUND','RETURNING')) BEGIN UPDATE fleet_response_transit_leg SET status='IN_TRANSIT' WHERE leg_id=(SELECT leg_id FROM fleet_response_transit_leg WHERE responder_npc_vessel_id=NEW.npc_vessel_id AND status='PREPARING' ORDER BY started_tick DESC LIMIT 1); END",

                "CREATE TRIGGER fleet_response_responder_arrives_scene AFTER UPDATE OF status ON npc_vessel WHEN NEW.status='WORKING' AND EXISTS (SELECT 1 FROM fleet_response_operation o WHERE o.assigned_npc_vessel_id=NEW.npc_vessel_id AND o.status='ACTIVE' AND o.response_phase='OUTBOUND') BEGIN "
                        + "UPDATE fleet_response_transit_leg SET status='ARRIVED',arrived_tick=NEW.last_tick,completed_tick=NEW.last_tick WHERE leg_id=(SELECT leg_id FROM fleet_response_transit_leg WHERE responder_npc_vessel_id=NEW.npc_vessel_id AND leg_type='OUTBOUND' AND status IN ('PREPARING','IN_TRANSIT') ORDER BY started_tick DESC LIMIT 1); "
                        + "UPDATE fleet_response_operation SET response_phase='ON_SCENE',arrived_tick=NEW.last_tick,updated_tick=NEW.last_tick WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase='OUTBOUND'; "
                        + "UPDATE npc_vessel SET status='DOCKED',destination_location_id=NULL,route_progress=0,last_tick=NEW.last_tick WHERE npc_vessel_id=NEW.npc_vessel_id; "
                        + "INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) SELECT operation_id||':arrived:'||NEW.last_tick,world_id,operation_id,NEW.last_tick,'PROGRESS','The assigned responder survived outbound transit and arrived on scene.' FROM fleet_response_operation WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase='ON_SCENE'; END",

                "CREATE TRIGGER fleet_response_transit_encounter_link AFTER INSERT ON world_encounter WHEN EXISTS (SELECT 1 FROM fleet_response_transit_leg l WHERE l.responder_npc_vessel_id=NEW.npc_vessel_id AND l.started_tick<=NEW.tick_sequence AND COALESCE(l.completed_tick,NEW.tick_sequence)>=NEW.tick_sequence AND l.status IN ('IN_TRANSIT','ARRIVED') ORDER BY l.started_tick DESC LIMIT 1) BEGIN INSERT OR IGNORE INTO fleet_response_transit_encounter(encounter_id,world_id,operation_id,leg_id,responder_npc_vessel_id,tick_sequence) SELECT NEW.encounter_id,NEW.world_id,l.operation_id,l.leg_id,NEW.npc_vessel_id,NEW.tick_sequence FROM fleet_response_transit_leg l WHERE l.responder_npc_vessel_id=NEW.npc_vessel_id AND l.started_tick<=NEW.tick_sequence AND COALESCE(l.completed_tick,NEW.tick_sequence)>=NEW.tick_sequence AND l.status IN ('IN_TRANSIT','ARRIVED') ORDER BY l.started_tick DESC LIMIT 1; END",

                "CREATE TRIGGER fleet_response_requires_scene BEFORE UPDATE OF progress ON fleet_response_operation WHEN NEW.status='ACTIVE' AND OLD.response_phase<>'ON_SCENE' BEGIN SELECT RAISE(IGNORE); END",
                "DROP TRIGGER IF EXISTS fleet_response_requires_supplies",
                "CREATE TRIGGER fleet_response_requires_supplies BEFORE UPDATE OF progress ON fleet_response_operation WHEN NEW.progress>OLD.progress AND NEW.status='ACTIVE' AND NEW.response_phase='ON_SCENE' AND NEW.materials_committed=0 AND NEW.origin_station_id IS NOT NULL AND (COALESCE((SELECT quantity FROM station_inventory WHERE station_id=NEW.origin_station_id AND item_id='item-steel'),0)<NEW.spare_parts_required OR COALESCE((SELECT quantity FROM station_inventory WHERE station_id=NEW.origin_station_id AND item_id='item-fuel'),0)<NEW.fuel_required OR COALESCE((SELECT quantity FROM station_inventory WHERE station_id=NEW.origin_station_id AND item_id='item-ammunition'),0)<NEW.ammunition_required OR COALESCE((SELECT quantity FROM station_inventory WHERE station_id=NEW.origin_station_id AND item_id='item-medical'),0)<NEW.medical_required) BEGIN SELECT RAISE(IGNORE); END",

                "DROP TRIGGER IF EXISTS fleet_response_complete",
                "CREATE TRIGGER fleet_response_complete AFTER UPDATE OF progress ON fleet_response_operation WHEN NEW.status='ACTIVE' AND NEW.response_phase='ON_SCENE' AND NEW.progress>=100 BEGIN "
                        + "UPDATE station_simulation_state SET integrity=MIN(100,integrity+CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 8 ELSE 0 END),security=MIN(100,security+CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 10 ELSE 0 END),supplies=MAX(0,supplies-CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 6 ELSE 0 END),threat=MAX(0,threat-CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 12 ELSE 0 END) WHERE station_id=NEW.target_station_id AND NEW.materials_committed=0; "
                        + "UPDATE station_inventory SET quantity=MAX(0,quantity-CASE item_id WHEN 'item-steel' THEN NEW.spare_parts_required WHEN 'item-fuel' THEN NEW.fuel_required WHEN 'item-ammunition' THEN NEW.ammunition_required WHEN 'item-medical' THEN NEW.medical_required ELSE 0 END),last_tick=NEW.updated_tick WHERE station_id=NEW.origin_station_id AND item_id IN ('item-steel','item-fuel','item-ammunition','item-medical') AND NEW.materials_committed=0; "
                        + "UPDATE fleet_response_operation SET materials_committed=1,response_phase='RETURNING',return_started_tick=NEW.updated_tick,progress=100 WHERE operation_id=NEW.operation_id; "
                        + "UPDATE npc_vessel SET mission_id=NULL,destination_location_id=(SELECT end_location_id FROM fleet_response_return_plan WHERE operation_id=NEW.operation_id),status='PREPARING',route_progress=0,route_ticks_required=(SELECT route_ticks_required FROM fleet_response_return_plan WHERE operation_id=NEW.operation_id),last_tick=NEW.updated_tick WHERE npc_vessel_id=NEW.assigned_npc_vessel_id; "
                        + "INSERT OR IGNORE INTO fleet_response_transit_leg(leg_id,world_id,operation_id,responder_npc_vessel_id,attempt_number,leg_type,status,start_location_id,end_location_id,route_ticks_required,started_tick) SELECT NEW.operation_id||':return:'||o.attempt_number,NEW.world_id,NEW.operation_id,NEW.assigned_npc_vessel_id,o.attempt_number,'RETURN','PREPARING',p.start_location_id,p.end_location_id,p.route_ticks_required,NEW.updated_tick FROM fleet_response_operation o JOIN fleet_response_return_plan p ON p.operation_id=o.operation_id WHERE o.operation_id=NEW.operation_id; "
                        + "INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) VALUES (NEW.operation_id||':returning:'||NEW.updated_tick,NEW.world_id,NEW.operation_id,NEW.updated_tick,'PROGRESS','On-scene work completed; the responder began the return or towing leg.'); END",

                "CREATE TRIGGER fleet_response_responder_returns_home AFTER UPDATE OF status ON npc_vessel WHEN NEW.status='WORKING' AND EXISTS (SELECT 1 FROM fleet_response_operation o WHERE o.assigned_npc_vessel_id=NEW.npc_vessel_id AND o.status='ACTIVE' AND o.response_phase='RETURNING') BEGIN "
                        + "UPDATE fleet_response_transit_leg SET status='ARRIVED',arrived_tick=NEW.last_tick,completed_tick=NEW.last_tick WHERE leg_id=(SELECT leg_id FROM fleet_response_transit_leg WHERE responder_npc_vessel_id=NEW.npc_vessel_id AND leg_type='RETURN' AND status IN ('PREPARING','IN_TRANSIT') ORDER BY started_tick DESC LIMIT 1); "
                        + "UPDATE npc_vessel SET status='DOCKED',hull=MIN(100,MAX(hull,35)+CASE (SELECT operation_type FROM fleet_response_operation WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase='RETURNING') WHEN 'REPAIR' THEN 35 ELSE 15 END),supplies=MIN(100,supplies+CASE (SELECT operation_type FROM fleet_response_operation WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase='RETURNING') WHEN 'REFUEL' THEN 45 ELSE 25 END),current_location_id=COALESCE((SELECT location_id FROM world_station WHERE station_id=home_station_id),current_location_id),destination_location_id=NULL,mission_id=NULL,route_progress=0,last_tick=NEW.last_tick WHERE npc_vessel_id=(SELECT distressed_npc_vessel_id FROM fleet_response_operation WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase='RETURNING'); "
                        + "UPDATE fleet_response_operation SET status='COMPLETE',response_phase='COMPLETE',completed_tick=NEW.last_tick,responder_returned_tick=NEW.last_tick,updated_tick=NEW.last_tick WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase='RETURNING'; "
                        + "UPDATE npc_vessel SET status='DOCKED',destination_location_id=NULL,mission_id=NULL,route_progress=0,last_tick=NEW.last_tick WHERE npc_vessel_id=NEW.npc_vessel_id; "
                        + "INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) SELECT operation_id||':complete:'||NEW.last_tick,world_id,operation_id,NEW.last_tick,'COMPLETED','The responder returned safely and delivered the casualty or completed the reinforcement operation.' FROM fleet_response_operation WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='COMPLETE' AND response_phase='COMPLETE' AND completed_tick=NEW.last_tick; END",

                "CREATE TRIGGER fleet_response_responder_failure AFTER UPDATE OF status ON npc_vessel WHEN NEW.status IN ('DISABLED','LOST') AND OLD.status<>NEW.status AND EXISTS (SELECT 1 FROM fleet_response_operation o WHERE o.assigned_npc_vessel_id=NEW.npc_vessel_id AND o.status='ACTIVE' AND o.response_phase IN ('OUTBOUND','RETURNING')) BEGIN "
                        + "UPDATE fleet_response_transit_leg SET status='FAILED',completed_tick=NEW.last_tick WHERE leg_id=(SELECT leg_id FROM fleet_response_transit_leg WHERE responder_npc_vessel_id=NEW.npc_vessel_id AND status IN ('PREPARING','IN_TRANSIT') ORDER BY started_tick DESC LIMIT 1); "
                        + "INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) SELECT operation_id||':transit-failed:'||NEW.last_tick,world_id,operation_id,NEW.last_tick,'FAILED','The assigned responder was disabled or lost during transit; the operation returned to the response queue.' FROM fleet_response_operation WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase IN ('OUTBOUND','RETURNING'); "
                        + "UPDATE fleet_response_operation SET status='AVAILABLE',assigned_npc_vessel_id=NULL,response_phase='WAITING',updated_tick=NEW.last_tick WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status='ACTIVE' AND response_phase IN ('OUTBOUND','RETURNING'); END",

                "CREATE TRIGGER fleet_response_cancelled_releases_responder AFTER UPDATE OF status ON fleet_response_operation WHEN NEW.status='CANCELLED' AND OLD.status<>'CANCELLED' AND NEW.assigned_npc_vessel_id IS NOT NULL BEGIN UPDATE fleet_response_transit_leg SET status='CANCELLED',completed_tick=NEW.updated_tick WHERE operation_id=NEW.operation_id AND status IN ('PREPARING','IN_TRANSIT'); UPDATE npc_vessel SET status=CASE WHEN status IN ('DISABLED','LOST') THEN status ELSE 'RETURNING' END,destination_location_id=CASE WHEN status IN ('DISABLED','LOST') THEN destination_location_id ELSE (SELECT location_id FROM world_station WHERE station_id=home_station_id) END,route_progress=0,last_tick=NEW.updated_tick WHERE npc_vessel_id=NEW.assigned_npc_vessel_id; UPDATE fleet_response_operation SET response_phase='CANCELLED' WHERE operation_id=NEW.operation_id; END"
        );
    }
}
