package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 010: passive fleet recovery plus ecological and geological world activity. */
public final class FleetRecoveryAndNaturalWorldSchema {
    private FleetRecoveryAndNaturalWorldSchema() { }

    public static List<String> statements() {
        return List.of(
                "CREATE TABLE fleet_response_operation (operation_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, operation_type TEXT NOT NULL CHECK(operation_type IN ('RESCUE','TOWING','REPAIR','REFUEL','REARM','REINFORCEMENT')), status TEXT NOT NULL DEFAULT 'AVAILABLE' CHECK(status IN ('AVAILABLE','ACTIVE','COMPLETE','FAILED','CANCELLED')), distressed_npc_vessel_id TEXT, assigned_npc_vessel_id TEXT, origin_station_id TEXT, target_station_id TEXT, target_location_id TEXT NOT NULL, progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100), difficulty INTEGER NOT NULL CHECK(difficulty BETWEEN 1 AND 100), spare_parts_required INTEGER NOT NULL DEFAULT 0 CHECK(spare_parts_required >= 0), fuel_required INTEGER NOT NULL DEFAULT 0 CHECK(fuel_required >= 0), ammunition_required INTEGER NOT NULL DEFAULT 0 CHECK(ammunition_required >= 0), medical_required INTEGER NOT NULL DEFAULT 0 CHECK(medical_required >= 0), created_tick INTEGER NOT NULL CHECK(created_tick >= 0), updated_tick INTEGER NOT NULL CHECK(updated_tick >= 0), completed_tick INTEGER CHECK(completed_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(distressed_npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id), FOREIGN KEY(assigned_npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id), FOREIGN KEY(origin_station_id) REFERENCES world_station(station_id), FOREIGN KEY(target_station_id) REFERENCES world_station(station_id), FOREIGN KEY(target_location_id) REFERENCES world_location(location_id))",
                "CREATE INDEX fleet_response_status_index ON fleet_response_operation(world_id,status,operation_type,created_tick)",
                "CREATE UNIQUE INDEX one_active_response_per_vessel ON fleet_response_operation(assigned_npc_vessel_id) WHERE assigned_npc_vessel_id IS NOT NULL AND status='ACTIVE'",
                "CREATE TABLE fleet_response_log (log_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, operation_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), event_type TEXT NOT NULL CHECK(event_type IN ('REQUESTED','ASSIGNED','PROGRESS','COMPLETED','FAILED')), summary TEXT NOT NULL, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(operation_id) REFERENCES fleet_response_operation(operation_id))",
                "CREATE INDEX fleet_response_log_tick_index ON fleet_response_log(world_id,tick_sequence DESC)",

                "CREATE TABLE location_ecology_state (location_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, primary_producers INTEGER NOT NULL DEFAULT 30 CHECK(primary_producers BETWEEN 0 AND 100), algal_bloom INTEGER NOT NULL DEFAULT 5 CHECK(algal_bloom BETWEEN 0 AND 100), herbivore_biomass INTEGER NOT NULL DEFAULT 20 CHECK(herbivore_biomass BETWEEN 0 AND 100), predator_biomass INTEGER NOT NULL DEFAULT 15 CHECK(predator_biomass BETWEEN 0 AND 100), scavenger_biomass INTEGER NOT NULL DEFAULT 10 CHECK(scavenger_biomass BETWEEN 0 AND 100), bioaccumulator_mass INTEGER NOT NULL DEFAULT 5 CHECK(bioaccumulator_mass BETWEEN 0 AND 100), nutrient_load INTEGER NOT NULL DEFAULT 35 CHECK(nutrient_load BETWEEN 0 AND 100), habitat_integrity INTEGER NOT NULL DEFAULT 70 CHECK(habitat_integrity BETWEEN 0 AND 100), migration_pressure INTEGER NOT NULL DEFAULT 10 CHECK(migration_pressure BETWEEN 0 AND 100), last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), FOREIGN KEY(location_id) REFERENCES world_location(location_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))",
                "CREATE INDEX location_ecology_predator_index ON location_ecology_state(world_id,predator_biomass DESC,migration_pressure DESC)",
                "CREATE TABLE location_geology_state (location_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, tectonic_stress INTEGER NOT NULL DEFAULT 20 CHECK(tectonic_stress BETWEEN 0 AND 100), hydrothermal_activity INTEGER NOT NULL DEFAULT 20 CHECK(hydrothermal_activity BETWEEN 0 AND 100), mineral_exposure INTEGER NOT NULL DEFAULT 10 CHECK(mineral_exposure BETWEEN 0 AND 100), cave_instability INTEGER NOT NULL DEFAULT 10 CHECK(cave_instability BETWEEN 0 AND 100), sediment_flux INTEGER NOT NULL DEFAULT 20 CHECK(sediment_flux BETWEEN 0 AND 100), last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), FOREIGN KEY(location_id) REFERENCES world_location(location_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))",
                "CREATE INDEX location_geology_resource_index ON location_geology_state(world_id,mineral_exposure DESC,hydrothermal_activity DESC)",
                "CREATE TABLE natural_resource_site (site_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, location_id TEXT NOT NULL, resource_type TEXT NOT NULL CHECK(resource_type IN ('ORE_VEIN','RARE_MINERALS','HYDROTHERMAL_DEPOSIT','BIOACTIVE_ACCUMULATOR','ALGAE_HARVEST')), richness INTEGER NOT NULL CHECK(richness BETWEEN 1 AND 100), accessibility INTEGER NOT NULL CHECK(accessibility BETWEEN 1 AND 100), renewable INTEGER NOT NULL DEFAULT 0 CHECK(renewable IN (0,1)), status TEXT NOT NULL DEFAULT 'EXPOSED' CHECK(status IN ('EXPOSED','SURVEYED','HARVESTING','DEPLETED','DORMANT')), discovered_tick INTEGER NOT NULL CHECK(discovered_tick >= 0), last_tick INTEGER NOT NULL CHECK(last_tick >= 0), UNIQUE(location_id,resource_type), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(location_id) REFERENCES world_location(location_id))",
                "CREATE INDEX natural_resource_status_index ON natural_resource_site(world_id,status,resource_type,richness DESC)",
                "CREATE TABLE natural_world_event (event_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, location_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), event_type TEXT NOT NULL CHECK(event_type IN ('ALGAL_BLOOM','HERBIVORE_SURGE','PREDATOR_EXPANSION','BIOACCUMULATION','VENT_ERUPTION','ROCKFALL','RESOURCE_EXPOSURE','HABITAT_RECOVERY')), severity INTEGER NOT NULL CHECK(severity BETWEEN 0 AND 100), summary TEXT NOT NULL, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(location_id) REFERENCES world_location(location_id))",
                "CREATE INDEX natural_world_event_tick_index ON natural_world_event(world_id,tick_sequence DESC,severity DESC)",

                "INSERT OR IGNORE INTO location_ecology_state(location_id,world_id,primary_producers,algal_bloom,herbivore_biomass,predator_biomass,scavenger_biomass,bioaccumulator_mass,nutrient_load,habitat_integrity,migration_pressure,last_tick) SELECT location_id,world_id,MIN(100,20+(source_ordinal%31)+location_level*2),source_ordinal%12,MIN(100,15+(source_ordinal%23)+location_level),MIN(100,8+(source_ordinal%19)+location_level*2),8+(source_ordinal%15),source_ordinal%10,MIN(100,25+(source_ordinal%37)),MAX(20,85-location_level*5),MIN(100,8+location_level*4),0 FROM world_location",
                "INSERT OR IGNORE INTO location_geology_state(location_id,world_id,tectonic_stress,hydrothermal_activity,mineral_exposure,cave_instability,sediment_flux,last_tick) SELECT location_id,world_id,MIN(100,10+(source_ordinal%41)+location_level*3),MIN(100,10+(source_ordinal%29)+location_level*4),5+(source_ordinal%16),MIN(100,5+(source_ordinal%21)+location_level*3),10+(source_ordinal%31),0 FROM world_location",
                "CREATE TRIGGER natural_world_seed AFTER INSERT ON world_location BEGIN INSERT OR IGNORE INTO location_ecology_state(location_id,world_id,primary_producers,algal_bloom,herbivore_biomass,predator_biomass,scavenger_biomass,bioaccumulator_mass,nutrient_load,habitat_integrity,migration_pressure,last_tick) VALUES (NEW.location_id,NEW.world_id,MIN(100,20+(NEW.source_ordinal%31)+NEW.location_level*2),NEW.source_ordinal%12,MIN(100,15+(NEW.source_ordinal%23)+NEW.location_level),MIN(100,8+(NEW.source_ordinal%19)+NEW.location_level*2),8+(NEW.source_ordinal%15),NEW.source_ordinal%10,MIN(100,25+(NEW.source_ordinal%37)),MAX(20,85-NEW.location_level*5),MIN(100,8+NEW.location_level*4),0); INSERT OR IGNORE INTO location_geology_state(location_id,world_id,tectonic_stress,hydrothermal_activity,mineral_exposure,cave_instability,sediment_flux,last_tick) VALUES (NEW.location_id,NEW.world_id,MIN(100,10+(NEW.source_ordinal%41)+NEW.location_level*3),MIN(100,10+(NEW.source_ordinal%29)+NEW.location_level*4),5+(NEW.source_ordinal%16),MIN(100,5+(NEW.source_ordinal%21)+NEW.location_level*3),10+(NEW.source_ordinal%31),0); END",

                "CREATE TRIGGER disabled_vessel_requests_response AFTER UPDATE OF status ON npc_vessel WHEN NEW.status='DISABLED' AND OLD.status<>'DISABLED' BEGIN INSERT OR IGNORE INTO fleet_response_operation(operation_id,world_id,operation_type,status,distressed_npc_vessel_id,origin_station_id,target_location_id,progress,difficulty,spare_parts_required,fuel_required,medical_required,created_tick,updated_tick) VALUES (substr(NEW.npc_vessel_id,1,24)||printf('%012x',(NEW.last_tick*4+1)%281474976710655),NEW.world_id,CASE WHEN NEW.hull<=10 THEN 'TOWING' ELSE 'RESCUE' END,'AVAILABLE',NEW.npc_vessel_id,NEW.home_station_id,NEW.current_location_id,0,MIN(100,35+(100-NEW.hull)/2),MAX(2,(100-NEW.hull)/8),4,MAX(1,(100-NEW.hull)/12),NEW.last_tick,NEW.last_tick); INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) VALUES (NEW.npc_vessel_id||':response-request:'||NEW.last_tick,NEW.world_id,substr(NEW.npc_vessel_id,1,24)||printf('%012x',(NEW.last_tick*4+1)%281474976710655),NEW.last_tick,'REQUESTED',NEW.display_name||' transmitted a distress call requiring rescue or towing.'); END",
                "CREATE TRIGGER besieged_station_requests_reinforcement AFTER UPDATE OF status ON station_simulation_state WHEN NEW.status='BESIEGED' AND OLD.status<>'BESIEGED' BEGIN INSERT OR IGNORE INTO fleet_response_operation(operation_id,world_id,operation_type,status,origin_station_id,target_station_id,target_location_id,progress,difficulty,spare_parts_required,fuel_required,ammunition_required,medical_required,created_tick,updated_tick) SELECT substr(NEW.station_id,1,24)||printf('%012x',(NEW.last_tick*4+2)%281474976710655),NEW.world_id,'REINFORCEMENT','AVAILABLE',NEW.station_id,NEW.station_id,ws.location_id,0,MIN(100,40+NEW.threat/2),4,5,MAX(4,NEW.threat/8),3,NEW.last_tick,NEW.last_tick FROM world_station ws WHERE ws.station_id=NEW.station_id; END",

                "CREATE TRIGGER passive_natural_and_recovery_cycle AFTER UPDATE OF last_cycle_tick ON passive_simulation_config WHEN NEW.last_cycle_tick IS NOT NULL AND (OLD.last_cycle_tick IS NULL OR NEW.last_cycle_tick>OLD.last_cycle_tick) BEGIN "
                        + "UPDATE location_geology_state SET tectonic_stress=MAX(0,MIN(100,tectonic_stress+((NEW.last_cycle_tick+ABS(unicode(substr(location_id,4,1))))%5)-2)),hydrothermal_activity=MAX(0,MIN(100,hydrothermal_activity+CASE WHEN tectonic_stress>=70 THEN 2 WHEN tectonic_stress<25 THEN -1 ELSE 0 END)),mineral_exposure=MAX(0,MIN(100,mineral_exposure+CASE WHEN hydrothermal_activity>=60 THEN 2 WHEN ((NEW.last_cycle_tick+ABS(unicode(substr(location_id,5,1))))%17)=0 THEN 5 ELSE 0 END)),cave_instability=MAX(0,MIN(100,cave_instability+CASE WHEN tectonic_stress>=75 THEN 2 WHEN tectonic_stress<35 THEN -1 ELSE 0 END)),sediment_flux=MAX(0,MIN(100,sediment_flux+CASE WHEN hydrothermal_activity>=55 THEN 1 ELSE -1 END)),last_tick=NEW.last_cycle_tick WHERE world_id=NEW.world_id; "
                        + "UPDATE location_ecology_state SET primary_producers=MAX(0,MIN(100,primary_producers+CASE WHEN nutrient_load>=55 OR (SELECT hydrothermal_activity FROM location_geology_state g WHERE g.location_id=location_ecology_state.location_id)>=55 THEN 2 ELSE 0 END-herbivore_biomass/35)),algal_bloom=MAX(0,MIN(100,algal_bloom+CASE WHEN primary_producers>=60 AND nutrient_load>=50 THEN 3 ELSE -1 END)),herbivore_biomass=MAX(0,MIN(100,herbivore_biomass+CASE WHEN algal_bloom>=35 OR primary_producers>=60 THEN 2 ELSE -1 END-predator_biomass/40)),predator_biomass=MAX(0,MIN(100,predator_biomass+CASE WHEN herbivore_biomass>=50 THEN 2 WHEN herbivore_biomass<20 THEN -2 ELSE 0 END)),scavenger_biomass=MAX(0,MIN(100,scavenger_biomass+CASE WHEN predator_biomass>=50 OR (SELECT cave_instability FROM location_geology_state g WHERE g.location_id=location_ecology_state.location_id)>=60 THEN 1 ELSE -1 END)),bioaccumulator_mass=MAX(0,MIN(100,bioaccumulator_mass+CASE WHEN algal_bloom>=45 OR herbivore_biomass>=55 THEN 2 ELSE 0 END)),nutrient_load=MAX(0,MIN(100,nutrient_load+CASE WHEN scavenger_biomass>=35 THEN 1 ELSE 0 END-primary_producers/45)),habitat_integrity=MAX(0,MIN(100,habitat_integrity+CASE WHEN predator_biomass<=herbivore_biomass AND (SELECT cave_instability FROM location_geology_state g WHERE g.location_id=location_ecology_state.location_id)<55 THEN 1 WHEN predator_biomass>=herbivore_biomass+25 OR (SELECT cave_instability FROM location_geology_state g WHERE g.location_id=location_ecology_state.location_id)>=75 THEN -2 ELSE 0 END)),migration_pressure=MAX(0,MIN(100,predator_biomass-herbivore_biomass/2+CASE WHEN algal_bloom>=50 THEN 5 ELSE 0 END)),last_tick=NEW.last_cycle_tick WHERE world_id=NEW.world_id; "
                        + "INSERT OR IGNORE INTO natural_world_event(event_id,world_id,location_id,tick_sequence,event_type,severity,summary) SELECT location_id||':bloom:'||NEW.last_cycle_tick,world_id,location_id,NEW.last_cycle_tick,'ALGAL_BLOOM',algal_bloom,'A nutrient-rich algal bloom expanded the base of the local food web.' FROM location_ecology_state WHERE world_id=NEW.world_id AND algal_bloom>=55 AND ((NEW.last_cycle_tick+ABS(unicode(substr(location_id,6,1))))%7)=0; "
                        + "INSERT OR IGNORE INTO natural_world_event(event_id,world_id,location_id,tick_sequence,event_type,severity,summary) SELECT location_id||':herbivore:'||NEW.last_cycle_tick,world_id,location_id,NEW.last_cycle_tick,'HERBIVORE_SURGE',herbivore_biomass,'Herbivore populations expanded behind sustained producer and algal growth.' FROM location_ecology_state WHERE world_id=NEW.world_id AND herbivore_biomass>=55 AND herbivore_biomass>predator_biomass+10 AND ((NEW.last_cycle_tick+ABS(unicode(substr(location_id,7,1))))%9)=0; "
                        + "INSERT OR IGNORE INTO natural_world_event(event_id,world_id,location_id,tick_sequence,event_type,severity,summary) SELECT location_id||':predator:'||NEW.last_cycle_tick,world_id,location_id,NEW.last_cycle_tick,'PREDATOR_EXPANSION',predator_biomass,'Predators expanded their feeding grounds toward richer herbivore concentrations.' FROM location_ecology_state WHERE world_id=NEW.world_id AND predator_biomass>=45 AND migration_pressure>=30 AND ((NEW.last_cycle_tick+ABS(unicode(substr(location_id,8,1))))%11)=0; "
                        + "INSERT OR IGNORE INTO natural_world_event(event_id,world_id,location_id,tick_sequence,event_type,severity,summary) SELECT location_id||':bioaccumulation:'||NEW.last_cycle_tick,world_id,location_id,NEW.last_cycle_tick,'BIOACCUMULATION',bioaccumulator_mass,'Natural biological accumulators concentrated harvestable compounds in the habitat.' FROM location_ecology_state WHERE world_id=NEW.world_id AND bioaccumulator_mass>=60 AND ((NEW.last_cycle_tick+ABS(unicode(substr(location_id,9,1))))%13)=0; "
                        + "INSERT OR IGNORE INTO natural_world_event(event_id,world_id,location_id,tick_sequence,event_type,severity,summary) SELECT location_id||':vent:'||NEW.last_cycle_tick,world_id,location_id,NEW.last_cycle_tick,'VENT_ERUPTION',hydrothermal_activity,'Hydrothermal activity exposed new chemical energy and mineral deposits.' FROM location_geology_state WHERE world_id=NEW.world_id AND hydrothermal_activity>=65 AND ((NEW.last_cycle_tick+ABS(unicode(substr(location_id,10,1))))%13)=0; "
                        + "INSERT OR IGNORE INTO natural_world_event(event_id,world_id,location_id,tick_sequence,event_type,severity,summary) SELECT location_id||':rockfall:'||NEW.last_cycle_tick,world_id,location_id,NEW.last_cycle_tick,'ROCKFALL',cave_instability,'Geological instability collapsed old passages and opened new terrain.' FROM location_geology_state WHERE world_id=NEW.world_id AND cave_instability>=65 AND ((NEW.last_cycle_tick+ABS(unicode(substr(location_id,11,1))))%17)=0; "
                        + "INSERT OR IGNORE INTO natural_resource_site(site_id,world_id,location_id,resource_type,richness,accessibility,renewable,status,discovered_tick,last_tick) SELECT substr(location_id,1,24)||printf('%012x',1),world_id,location_id,CASE ABS(unicode(substr(location_id,12,1)))%3 WHEN 0 THEN 'ORE_VEIN' WHEN 1 THEN 'RARE_MINERALS' ELSE 'HYDROTHERMAL_DEPOSIT' END,MIN(100,mineral_exposure),MAX(1,100-cave_instability),0,'EXPOSED',NEW.last_cycle_tick,NEW.last_cycle_tick FROM location_geology_state WHERE world_id=NEW.world_id AND mineral_exposure>=60 ON CONFLICT(location_id,resource_type) DO UPDATE SET richness=MIN(100,natural_resource_site.richness+1),accessibility=MAX(1,100-excluded.accessibility),last_tick=excluded.last_tick,status=CASE WHEN natural_resource_site.status='DEPLETED' THEN 'DORMANT' ELSE natural_resource_site.status END; "
                        + "INSERT OR IGNORE INTO natural_resource_site(site_id,world_id,location_id,resource_type,richness,accessibility,renewable,status,discovered_tick,last_tick) SELECT substr(location_id,1,24)||printf('%012x',2),world_id,location_id,'BIOACTIVE_ACCUMULATOR',MIN(100,bioaccumulator_mass),MAX(1,habitat_integrity),1,'EXPOSED',NEW.last_cycle_tick,NEW.last_cycle_tick FROM location_ecology_state WHERE world_id=NEW.world_id AND bioaccumulator_mass>=60 ON CONFLICT(location_id,resource_type) DO UPDATE SET richness=MIN(100,natural_resource_site.richness+1),accessibility=excluded.accessibility,last_tick=excluded.last_tick,status=CASE WHEN natural_resource_site.status='DEPLETED' THEN 'DORMANT' ELSE natural_resource_site.status END; "
                        + "INSERT OR IGNORE INTO natural_resource_site(site_id,world_id,location_id,resource_type,richness,accessibility,renewable,status,discovered_tick,last_tick) SELECT substr(location_id,1,24)||printf('%012x',3),world_id,location_id,'ALGAE_HARVEST',MIN(100,algal_bloom),MAX(1,habitat_integrity),1,'EXPOSED',NEW.last_cycle_tick,NEW.last_cycle_tick FROM location_ecology_state WHERE world_id=NEW.world_id AND algal_bloom>=55 ON CONFLICT(location_id,resource_type) DO UPDATE SET richness=MIN(100,natural_resource_site.richness+1),accessibility=excluded.accessibility,last_tick=excluded.last_tick; "
                        + "UPDATE station_simulation_state SET threat=MIN(100,threat+COALESCE((SELECT CASE WHEN e.predator_biomass>=65 THEN 2 WHEN e.predator_biomass>=45 THEN 1 ELSE 0 END FROM world_station ws JOIN location_ecology_state e ON e.location_id=ws.location_id WHERE ws.station_id=station_simulation_state.station_id),0)) WHERE world_id=NEW.world_id; "
                        + "UPDATE fleet_response_operation SET assigned_npc_vessel_id=(SELECT v.npc_vessel_id FROM npc_vessel v WHERE v.world_id=NEW.world_id AND v.status='DOCKED' AND v.mission_id IS NULL AND v.role IN ('SALVAGE','PATROL','COURIER') AND NOT EXISTS (SELECT 1 FROM fleet_response_operation busy WHERE busy.assigned_npc_vessel_id=v.npc_vessel_id AND busy.status='ACTIVE') ORDER BY CASE v.role WHEN 'SALVAGE' THEN 0 WHEN 'PATROL' THEN 1 ELSE 2 END,v.engineering DESC,v.npc_vessel_id LIMIT 1),status='ACTIVE',updated_tick=NEW.last_cycle_tick WHERE operation_id=(SELECT operation_id FROM fleet_response_operation WHERE world_id=NEW.world_id AND status='AVAILABLE' ORDER BY difficulty,created_tick LIMIT 1) AND EXISTS (SELECT 1 FROM npc_vessel v WHERE v.world_id=NEW.world_id AND v.status='DOCKED' AND v.mission_id IS NULL AND v.role IN ('SALVAGE','PATROL','COURIER') AND NOT EXISTS (SELECT 1 FROM fleet_response_operation busy WHERE busy.assigned_npc_vessel_id=v.npc_vessel_id AND busy.status='ACTIVE')); "
                        + "UPDATE fleet_response_operation SET progress=MIN(100,progress+MAX(4,COALESCE((SELECT engineering/10+combat/20 FROM npc_vessel v WHERE v.npc_vessel_id=fleet_response_operation.assigned_npc_vessel_id),4))),updated_tick=NEW.last_cycle_tick WHERE world_id=NEW.world_id AND status='ACTIVE'; END",

                "CREATE TRIGGER fleet_response_assigned AFTER UPDATE OF assigned_npc_vessel_id ON fleet_response_operation WHEN NEW.assigned_npc_vessel_id IS NOT NULL AND OLD.assigned_npc_vessel_id IS NULL BEGIN INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) VALUES (NEW.operation_id||':assigned:'||NEW.updated_tick,NEW.world_id,NEW.operation_id,NEW.updated_tick,'ASSIGNED','A recovery vessel was assigned to the operation.'); END",
                "CREATE TRIGGER fleet_response_progress AFTER UPDATE OF progress ON fleet_response_operation WHEN NEW.status='ACTIVE' AND NEW.progress>OLD.progress AND NEW.progress<100 BEGIN INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) VALUES (NEW.operation_id||':progress:'||NEW.updated_tick,NEW.world_id,NEW.operation_id,NEW.updated_tick,'PROGRESS','The assigned vessel advanced recovery, repair, refuel, rearm, or reinforcement work.'); END",
                "CREATE TRIGGER fleet_response_complete AFTER UPDATE OF progress ON fleet_response_operation WHEN NEW.status='ACTIVE' AND NEW.progress>=100 BEGIN UPDATE npc_vessel SET status='DOCKED',hull=MIN(100,MAX(hull,35)+CASE NEW.operation_type WHEN 'REPAIR' THEN 35 ELSE 15 END),supplies=MIN(100,supplies+CASE NEW.operation_type WHEN 'REFUEL' THEN 45 ELSE 25 END),current_location_id=COALESCE((SELECT location_id FROM world_station WHERE station_id=home_station_id),current_location_id),destination_location_id=NULL,mission_id=NULL,route_progress=0,last_tick=NEW.updated_tick WHERE npc_vessel_id=NEW.distressed_npc_vessel_id; UPDATE station_simulation_state SET integrity=MIN(100,integrity+CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 8 ELSE 0 END),security=MIN(100,security+CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 10 ELSE 0 END),supplies=MAX(0,supplies-CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 6 ELSE 0 END),threat=MAX(0,threat-CASE NEW.operation_type WHEN 'REINFORCEMENT' THEN 12 ELSE 0 END) WHERE station_id=NEW.target_station_id; UPDATE station_inventory SET quantity=MAX(0,quantity-CASE item_id WHEN 'item-steel' THEN NEW.spare_parts_required WHEN 'item-fuel' THEN NEW.fuel_required WHEN 'item-ammunition' THEN NEW.ammunition_required WHEN 'item-medical' THEN NEW.medical_required ELSE 0 END),last_tick=NEW.updated_tick WHERE station_id=NEW.origin_station_id AND item_id IN ('item-steel','item-fuel','item-ammunition','item-medical'); UPDATE fleet_response_operation SET status='COMPLETE',progress=100,completed_tick=NEW.updated_tick WHERE operation_id=NEW.operation_id; INSERT OR IGNORE INTO fleet_response_log(log_id,world_id,operation_id,tick_sequence,event_type,summary) VALUES (NEW.operation_id||':complete:'||NEW.updated_tick,NEW.world_id,NEW.operation_id,NEW.updated_tick,'COMPLETED','The fleet response restored the vessel or reinforced the threatened station.'); END"
        );
    }
}
