package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 013: finite extraction, renewable recovery, freight settlement, and resource evidence. */
public final class NaturalResourceHarvestingSchema {
    private NaturalResourceHarvestingSchema() { }

    public static List<String> statements() {
        return List.of(
                "ALTER TABLE natural_resource_site ADD COLUMN remaining_units INTEGER NOT NULL DEFAULT 0 CHECK(remaining_units >= 0)",
                "ALTER TABLE natural_resource_site ADD COLUMN carrying_capacity INTEGER NOT NULL DEFAULT 0 CHECK(carrying_capacity >= 0)",
                "ALTER TABLE natural_resource_site ADD COLUMN harvest_rate INTEGER NOT NULL DEFAULT 1 CHECK(harvest_rate BETWEEN 1 AND 100)",
                "ALTER TABLE natural_resource_site ADD COLUMN recovery_progress INTEGER NOT NULL DEFAULT 0 CHECK(recovery_progress BETWEEN 0 AND 100)",
                "ALTER TABLE natural_resource_site ADD COLUMN dormant_until_tick INTEGER CHECK(dormant_until_tick >= 0)",
                "ALTER TABLE natural_resource_site ADD COLUMN extraction_count INTEGER NOT NULL DEFAULT 0 CHECK(extraction_count >= 0)",
                "ALTER TABLE natural_resource_site ADD COLUMN last_harvest_tick INTEGER CHECK(last_harvest_tick >= 0)",

                "UPDATE natural_resource_site SET carrying_capacity=CASE WHEN renewable=1 THEN richness*3 ELSE richness*8 END,"
                        + "remaining_units=CASE WHEN renewable=1 THEN richness*3 ELSE richness*8 END,"
                        + "harvest_rate=MAX(1,MIN(100,2+richness/12+accessibility/20)) WHERE carrying_capacity=0",

                "CREATE TABLE resource_harvest_mission (mission_id TEXT PRIMARY KEY, site_id TEXT NOT NULL, cycle_number INTEGER NOT NULL CHECK(cycle_number >= 0), created_tick INTEGER NOT NULL CHECK(created_tick >= 0), UNIQUE(site_id,cycle_number), FOREIGN KEY(mission_id) REFERENCES world_mission(mission_id), FOREIGN KEY(site_id) REFERENCES natural_resource_site(site_id))",
                "CREATE INDEX resource_harvest_site_index ON resource_harvest_mission(site_id,cycle_number DESC)",
                "CREATE TABLE resource_extraction_batch (extraction_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, site_id TEXT NOT NULL, mission_id TEXT NOT NULL UNIQUE, station_id TEXT NOT NULL, npc_vessel_id TEXT NOT NULL, freight_lot_id TEXT NOT NULL UNIQUE, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), resource_type TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity > 0), remaining_before INTEGER NOT NULL CHECK(remaining_before >= 0), remaining_after INTEGER NOT NULL CHECK(remaining_after >= 0), richness_before INTEGER NOT NULL CHECK(richness_before BETWEEN 1 AND 100), richness_after INTEGER NOT NULL CHECK(richness_after BETWEEN 1 AND 100), renewable INTEGER NOT NULL CHECK(renewable IN (0,1)), ecological_impact INTEGER NOT NULL DEFAULT 0 CHECK(ecological_impact >= 0), geological_impact INTEGER NOT NULL DEFAULT 0 CHECK(geological_impact >= 0), credits_value INTEGER NOT NULL CHECK(credits_value >= 0), station_credits_before INTEGER NOT NULL, station_supplies_before INTEGER NOT NULL CHECK(station_supplies_before >= 0), station_ore_before INTEGER NOT NULL CHECK(station_ore_before >= 0), station_industry_before INTEGER NOT NULL CHECK(station_industry_before BETWEEN 0 AND 100), station_threat_before INTEGER NOT NULL CHECK(station_threat_before BETWEEN 0 AND 100), station_research_before INTEGER NOT NULL CHECK(station_research_before >= 0), vessel_cargo_before INTEGER NOT NULL CHECK(vessel_cargo_before >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(site_id) REFERENCES natural_resource_site(site_id), FOREIGN KEY(mission_id) REFERENCES world_mission(mission_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id), FOREIGN KEY(npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id), FOREIGN KEY(item_id) REFERENCES item_catalogue(item_id))",
                "CREATE INDEX resource_extraction_tick_index ON resource_extraction_batch(world_id,tick_sequence DESC,resource_type)",

                "INSERT OR IGNORE INTO item_catalogue(item_id,item_key,display_name,category,base_value,unit_mass) VALUES "
                        + "('item-rare-minerals','rare-minerals','Rare Europan Minerals','RAW',420,5.0),"
                        + "('item-hydrothermal','hydrothermal-compounds','Hydrothermal Compounds','RESEARCH',560,2.0),"
                        + "('item-bioactive','bioactive-compounds','Bioactive Compounds','MEDICAL',480,1.0),"
                        + "('item-algae','algae-biomass','Algae Biomass','SUPPLY',150,2.0)",
                "INSERT OR IGNORE INTO station_inventory(station_id,item_id,quantity,reserved,reorder_point,last_tick) SELECT s.station_id,i.item_id,0,0,CASE i.item_id WHEN 'item-algae' THEN 20 WHEN 'item-bioactive' THEN 8 ELSE 5 END,s.last_tick FROM station_simulation_state s JOIN item_catalogue i ON i.item_id IN ('item-rare-minerals','item-hydrothermal','item-bioactive','item-algae')",
                "INSERT OR IGNORE INTO station_vendor_offer(offer_id,station_id,item_id,buy_price,sell_price,stock_limit,active,last_tick) SELECT s.station_id||':'||i.item_id,s.station_id,i.item_id,MAX(1,i.base_value*70/100),MAX(1,i.base_value*120/100),60,CASE WHEN s.status='FALLEN' THEN 0 ELSE 1 END,s.last_tick FROM station_simulation_state s JOIN item_catalogue i ON i.item_id IN ('item-rare-minerals','item-hydrothermal','item-bioactive','item-algae')",

                "CREATE VIEW resource_harvest_completion_plan AS SELECT p.mission_id,p.world_id,p.site_id,p.station_id,p.npc_vessel_id,p.tick_sequence,p.resource_type,p.item_id,p.quantity,p.remaining_before,MAX(0,p.remaining_before-p.quantity) remaining_after,p.richness_before,MAX(1,p.richness_before-p.quantity/CASE WHEN p.renewable=1 THEN 12 ELSE 8 END) richness_after,p.renewable,CASE WHEN p.resource_type IN ('BIOACTIVE_ACCUMULATOR','ALGAE_HARVEST') THEN MAX(1,p.quantity/4) ELSE 0 END ecological_impact,CASE WHEN p.resource_type IN ('ORE_VEIN','RARE_MINERALS','HYDROTHERMAL_DEPOSIT') THEN MAX(1,p.quantity/4) ELSE 0 END geological_impact,i.base_value*p.quantity credits_value,p.station_credits_before,p.station_supplies_before,p.station_ore_before,p.station_industry_before,p.station_threat_before,p.station_research_before,p.vessel_cargo_before FROM (SELECT m.mission_id,m.world_id,s.site_id,m.origin_station_id station_id,m.assigned_npc_vessel_id npc_vessel_id,m.updated_tick tick_sequence,s.resource_type,CASE s.resource_type WHEN 'ORE_VEIN' THEN 'item-ore' WHEN 'RARE_MINERALS' THEN 'item-rare-minerals' WHEN 'HYDROTHERMAL_DEPOSIT' THEN 'item-hydrothermal' WHEN 'BIOACTIVE_ACCUMULATOR' THEN 'item-bioactive' ELSE 'item-algae' END item_id,MAX(1,MIN(s.remaining_units,MIN(30,s.harvest_rate+COALESCE(CASE m.mission_type WHEN 'MINING' THEN v.mining WHEN 'RESEARCH' THEN v.research ELSE v.engineering END,50)/12))) quantity,s.remaining_units remaining_before,s.richness richness_before,s.renewable,st.credits station_credits_before,st.supplies station_supplies_before,st.ore station_ore_before,st.industry station_industry_before,st.threat station_threat_before,st.research station_research_before,v.cargo vessel_cargo_before FROM resource_harvest_mission h JOIN natural_resource_site s ON s.site_id=h.site_id JOIN world_mission m ON m.mission_id=h.mission_id JOIN station_simulation_state st ON st.station_id=m.origin_station_id JOIN npc_vessel v ON v.npc_vessel_id=m.assigned_npc_vessel_id WHERE s.remaining_units>0) p JOIN item_catalogue i ON i.item_id=p.item_id",

                "DROP TRIGGER IF EXISTS passive_station_logistics_cycle",
                "CREATE TRIGGER passive_station_logistics_cycle AFTER UPDATE OF last_cycle_tick ON passive_simulation_config "
                        + "WHEN NEW.last_cycle_tick IS NOT NULL AND (OLD.last_cycle_tick IS NULL OR NEW.last_cycle_tick>OLD.last_cycle_tick) BEGIN "
                        + "INSERT OR IGNORE INTO station_inventory(station_id,item_id,quantity,reserved,reorder_point,last_tick) SELECT s.station_id,i.item_id,0,0,5,NEW.last_cycle_tick FROM station_simulation_state s CROSS JOIN item_catalogue i WHERE s.world_id=NEW.world_id; "
                        + "INSERT OR IGNORE INTO station_vendor_offer(offer_id,station_id,item_id,buy_price,sell_price,stock_limit,active,last_tick) SELECT s.station_id||':'||i.item_id,s.station_id,i.item_id,MAX(1,i.base_value*70/100),MAX(1,i.base_value*120/100),60,1,NEW.last_cycle_tick FROM station_simulation_state s CROSS JOIN item_catalogue i WHERE s.world_id=NEW.world_id; "
                        + "UPDATE station_inventory SET quantity=quantity+MAX(1,(SELECT supplies FROM station_simulation_state s WHERE s.station_id=station_inventory.station_id)/50),last_tick=NEW.last_cycle_tick WHERE item_id='item-rations' AND station_id IN (SELECT station_id FROM station_simulation_state WHERE world_id=NEW.world_id AND status<>'FALLEN'); "
                        + "INSERT OR IGNORE INTO station_production_run(run_id,station_id,recipe_id,tick_sequence,cycles,status) SELECT s.station_id||':'||r.recipe_id||':'||NEW.last_cycle_tick,s.station_id,r.recipe_id,NEW.last_cycle_tick,1,'COMPLETE' FROM station_simulation_state s CROSS JOIN production_recipe r WHERE s.world_id=NEW.world_id AND s.status<>'FALLEN' AND r.recipe_id=(SELECT r2.recipe_id FROM production_recipe r2 WHERE NEW.last_cycle_tick%r2.cycle_ticks=0 AND NOT EXISTS (SELECT 1 FROM production_recipe_input ri LEFT JOIN station_inventory inv ON inv.station_id=s.station_id AND inv.item_id=ri.item_id WHERE ri.recipe_id=r2.recipe_id AND COALESCE(inv.quantity-inv.reserved,0)<ri.quantity) ORDER BY r2.recipe_id LIMIT 1); "
                        + "UPDATE station_vendor_offer SET buy_price=MAX(1,(SELECT base_value FROM item_catalogue i WHERE i.item_id=station_vendor_offer.item_id)*(70+(SELECT threat FROM station_simulation_state s WHERE s.station_id=station_vendor_offer.station_id)/4)/100),sell_price=MAX(1,(SELECT base_value FROM item_catalogue i WHERE i.item_id=station_vendor_offer.item_id)*(115+(SELECT threat FROM station_simulation_state s WHERE s.station_id=station_vendor_offer.station_id)/3)/100),active=CASE WHEN (SELECT status FROM station_simulation_state s WHERE s.station_id=station_vendor_offer.station_id)='FALLEN' THEN 0 ELSE 1 END,last_tick=NEW.last_cycle_tick WHERE station_id IN (SELECT station_id FROM station_simulation_state WHERE world_id=NEW.world_id); END",

                "DROP TRIGGER IF EXISTS natural_resource_creates_mission",
                "CREATE TRIGGER natural_resource_creates_mission AFTER INSERT ON natural_resource_site BEGIN "
                        + "UPDATE natural_resource_site SET carrying_capacity=CASE WHEN NEW.renewable=1 THEN NEW.richness*3 ELSE NEW.richness*8 END,remaining_units=CASE WHEN NEW.renewable=1 THEN NEW.richness*3 ELSE NEW.richness*8 END,harvest_rate=MAX(1,MIN(100,2+NEW.richness/12+NEW.accessibility/20)) WHERE site_id=NEW.site_id; "
                        + "INSERT OR IGNORE INTO world_mission(mission_id,world_id,mission_type,status,origin_station_id,target_location_id,deterministic_seed,difficulty,reward_credits,cargo_units,progress,created_tick,updated_tick) SELECT NEW.site_id,NEW.world_id,CASE NEW.resource_type WHEN 'ORE_VEIN' THEN 'MINING' WHEN 'RARE_MINERALS' THEN 'MINING' WHEN 'HYDROTHERMAL_DEPOSIT' THEN 'RESEARCH' WHEN 'BIOACTIVE_ACCUMULATOR' THEN 'RESEARCH' ELSE 'SALVAGE' END,'AVAILABLE',(SELECT ws.station_id FROM world_station ws JOIN world_location station_location ON station_location.location_id=ws.location_id JOIN world_location target_location ON target_location.location_id=NEW.location_id WHERE ws.world_id=NEW.world_id ORDER BY ABS(station_location.source_ordinal-target_location.source_ordinal),station_location.source_ordinal LIMIT 1),NEW.location_id,NEW.discovered_tick,MIN(100,20+NEW.richness/2+(100-NEW.accessibility)/3),1000+NEW.richness*80,MAX(1,MIN(30,NEW.richness/4)),0,NEW.discovered_tick,NEW.discovered_tick; "
                        + "INSERT OR IGNORE INTO resource_harvest_mission(mission_id,site_id,cycle_number,created_tick) VALUES (NEW.site_id,NEW.site_id,0,NEW.discovered_tick); END",
                "INSERT OR IGNORE INTO resource_harvest_mission(mission_id,site_id,cycle_number,created_tick) SELECT m.mission_id,s.site_id,0,m.created_tick FROM natural_resource_site s JOIN world_mission m ON m.mission_id=s.site_id",

                "DROP TRIGGER IF EXISTS freight_from_completed_mission",
                "CREATE TRIGGER freight_from_completed_mission AFTER UPDATE OF status ON world_mission WHEN NEW.status='COMPLETE' AND OLD.status<>'COMPLETE' AND NEW.mission_type IN ('TRADE','MINING','SALVAGE') AND NOT EXISTS (SELECT 1 FROM resource_harvest_mission h WHERE h.mission_id=NEW.mission_id) BEGIN "
                        + "INSERT OR IGNORE INTO freight_lot(lot_id,world_id,mission_id,source_station_id,destination_station_id,item_id,quantity,status,assigned_npc_vessel_id,created_tick,updated_tick) SELECT NEW.mission_id||':freight',NEW.world_id,NEW.mission_id,NEW.origin_station_id,COALESCE((SELECT station_id FROM world_station WHERE location_id=NEW.target_location_id),NEW.origin_station_id),CASE NEW.mission_type WHEN 'MINING' THEN 'item-ore' WHEN 'SALVAGE' THEN 'item-steel' ELSE 'item-rations' END,MAX(1,NEW.cargo_units),'IN_TRANSIT',NEW.assigned_npc_vessel_id,NEW.created_tick,NEW.updated_tick; END",

                "CREATE TRIGGER resource_mission_begins_harvest AFTER UPDATE OF status ON world_mission WHEN NEW.status IN ('ASSIGNED','ACTIVE') AND EXISTS (SELECT 1 FROM resource_harvest_mission h WHERE h.mission_id=NEW.mission_id) BEGIN UPDATE natural_resource_site SET status='HARVESTING',last_tick=NEW.updated_tick WHERE site_id=(SELECT site_id FROM resource_harvest_mission WHERE mission_id=NEW.mission_id) AND remaining_units>0; END",
                "CREATE TRIGGER resource_mission_abandoned AFTER UPDATE OF status ON world_mission WHEN NEW.status IN ('FAILED','CANCELLED') AND OLD.status<>NEW.status AND EXISTS (SELECT 1 FROM resource_harvest_mission h WHERE h.mission_id=NEW.mission_id) BEGIN UPDATE natural_resource_site SET status=CASE WHEN remaining_units>0 THEN 'SURVEYED' WHEN renewable=1 THEN 'DORMANT' ELSE 'DEPLETED' END,dormant_until_tick=CASE WHEN remaining_units=0 AND renewable=1 THEN NEW.updated_tick+12 ELSE dormant_until_tick END,last_tick=NEW.updated_tick WHERE site_id=(SELECT site_id FROM resource_harvest_mission WHERE mission_id=NEW.mission_id); END",

                "CREATE TRIGGER resource_mission_completed AFTER UPDATE OF status ON world_mission WHEN NEW.status='COMPLETE' AND OLD.status<>'COMPLETE' AND EXISTS (SELECT 1 FROM resource_harvest_completion_plan p WHERE p.mission_id=NEW.mission_id) BEGIN "
                        + "INSERT OR IGNORE INTO resource_extraction_batch(extraction_id,world_id,site_id,mission_id,station_id,npc_vessel_id,freight_lot_id,tick_sequence,resource_type,item_id,quantity,remaining_before,remaining_after,richness_before,richness_after,renewable,ecological_impact,geological_impact,credits_value,station_credits_before,station_supplies_before,station_ore_before,station_industry_before,station_threat_before,station_research_before,vessel_cargo_before) SELECT NEW.mission_id||':extract',p.world_id,p.site_id,p.mission_id,p.station_id,p.npc_vessel_id,NEW.mission_id||':resource',p.tick_sequence,p.resource_type,p.item_id,p.quantity,p.remaining_before,p.remaining_after,p.richness_before,p.richness_after,p.renewable,p.ecological_impact,p.geological_impact,p.credits_value,p.station_credits_before,p.station_supplies_before,p.station_ore_before,p.station_industry_before,p.station_threat_before,p.station_research_before,p.vessel_cargo_before FROM resource_harvest_completion_plan p WHERE p.mission_id=NEW.mission_id; "
                        + "UPDATE natural_resource_site SET remaining_units=(SELECT remaining_after FROM resource_extraction_batch WHERE mission_id=NEW.mission_id),richness=(SELECT richness_after FROM resource_extraction_batch WHERE mission_id=NEW.mission_id),status=CASE WHEN (SELECT remaining_after FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)>0 THEN 'SURVEYED' WHEN renewable=1 THEN 'DORMANT' ELSE 'DEPLETED' END,recovery_progress=0,dormant_until_tick=CASE WHEN renewable=1 AND (SELECT remaining_after FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)=0 THEN NEW.updated_tick+12 ELSE NULL END,extraction_count=extraction_count+1,last_harvest_tick=NEW.updated_tick,last_tick=NEW.updated_tick WHERE site_id=(SELECT site_id FROM resource_harvest_mission WHERE mission_id=NEW.mission_id); "
                        + "INSERT OR IGNORE INTO freight_lot(lot_id,world_id,mission_id,source_station_id,destination_station_id,item_id,quantity,status,assigned_npc_vessel_id,created_tick,updated_tick) SELECT b.freight_lot_id,b.world_id,NULL,NULL,b.station_id,b.item_id,b.quantity,'IN_TRANSIT',b.npc_vessel_id,b.tick_sequence,b.tick_sequence FROM resource_extraction_batch b WHERE b.mission_id=NEW.mission_id; "
                        + "UPDATE location_ecology_state SET primary_producers=MAX(0,primary_producers-CASE WHEN (SELECT resource_type FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)='ALGAE_HARVEST' THEN (SELECT ecological_impact FROM resource_extraction_batch WHERE mission_id=NEW.mission_id) ELSE 0 END),algal_bloom=MAX(0,algal_bloom-CASE WHEN (SELECT resource_type FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)='ALGAE_HARVEST' THEN (SELECT ecological_impact FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)*2 ELSE 0 END),bioaccumulator_mass=MAX(0,bioaccumulator_mass-CASE WHEN (SELECT resource_type FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)='BIOACTIVE_ACCUMULATOR' THEN (SELECT ecological_impact FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)*2 ELSE 0 END),habitat_integrity=MAX(0,habitat_integrity-(SELECT ecological_impact FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)),last_tick=NEW.updated_tick WHERE location_id=(SELECT location_id FROM natural_resource_site WHERE site_id=(SELECT site_id FROM resource_harvest_mission WHERE mission_id=NEW.mission_id)); "
                        + "UPDATE location_geology_state SET mineral_exposure=MAX(0,mineral_exposure-(SELECT geological_impact FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)*2),cave_instability=MIN(100,cave_instability+(SELECT geological_impact FROM resource_extraction_batch WHERE mission_id=NEW.mission_id)),last_tick=NEW.updated_tick WHERE location_id=(SELECT location_id FROM natural_resource_site WHERE site_id=(SELECT site_id FROM resource_harvest_mission WHERE mission_id=NEW.mission_id)); END",

                "CREATE TRIGGER resource_generic_effect_compensation AFTER UPDATE OF status ON npc_vessel WHEN OLD.status='WORKING' AND NEW.status='RETURNING' AND EXISTS (SELECT 1 FROM resource_extraction_batch b WHERE b.mission_id=NEW.mission_id) BEGIN "
                        + "UPDATE station_simulation_state SET credits=(SELECT station_credits_before FROM resource_extraction_batch WHERE mission_id=NEW.mission_id),supplies=(SELECT station_supplies_before FROM resource_extraction_batch WHERE mission_id=NEW.mission_id),ore=(SELECT station_ore_before FROM resource_extraction_batch WHERE mission_id=NEW.mission_id),industry=(SELECT station_industry_before FROM resource_extraction_batch WHERE mission_id=NEW.mission_id),threat=(SELECT station_threat_before FROM resource_extraction_batch WHERE mission_id=NEW.mission_id),research=(SELECT station_research_before FROM resource_extraction_batch WHERE mission_id=NEW.mission_id) WHERE station_id=(SELECT station_id FROM resource_extraction_batch WHERE mission_id=NEW.mission_id); "
                        + "UPDATE npc_vessel SET cargo=(SELECT vessel_cargo_before FROM resource_extraction_batch WHERE mission_id=NEW.mission_id) WHERE npc_vessel_id=NEW.npc_vessel_id; END",

                "CREATE TRIGGER resource_freight_supports_station AFTER UPDATE OF status ON freight_lot WHEN NEW.status='DELIVERED' AND OLD.status<>'DELIVERED' AND EXISTS (SELECT 1 FROM resource_extraction_batch b WHERE b.freight_lot_id=NEW.lot_id) BEGIN "
                        + "UPDATE station_simulation_state SET ore=ore+CASE (SELECT resource_type FROM resource_extraction_batch WHERE freight_lot_id=NEW.lot_id) WHEN 'ORE_VEIN' THEN NEW.quantity WHEN 'RARE_MINERALS' THEN MAX(1,NEW.quantity/2) ELSE 0 END,research=research+CASE (SELECT resource_type FROM resource_extraction_batch WHERE freight_lot_id=NEW.lot_id) WHEN 'HYDROTHERMAL_DEPOSIT' THEN NEW.quantity WHEN 'BIOACTIVE_ACCUMULATOR' THEN NEW.quantity ELSE 0 END,supplies=supplies+CASE (SELECT resource_type FROM resource_extraction_batch WHERE freight_lot_id=NEW.lot_id) WHEN 'ALGAE_HARVEST' THEN NEW.quantity ELSE 0 END WHERE station_id=NEW.destination_station_id; END",
                "CREATE TRIGGER resource_treasury_reclassification AFTER INSERT ON treasury_transaction WHEN NEW.category='FREIGHT' AND EXISTS (SELECT 1 FROM resource_extraction_batch b WHERE b.freight_lot_id||':delivery'=NEW.transaction_id) BEGIN UPDATE treasury_transaction SET category=CASE (SELECT resource_type FROM resource_extraction_batch WHERE freight_lot_id||':delivery'=NEW.transaction_id) WHEN 'ORE_VEIN' THEN 'MINING' WHEN 'RARE_MINERALS' THEN 'MINING' WHEN 'ALGAE_HARVEST' THEN 'TRADE' ELSE 'RESEARCH' END,counterparty_type='RESOURCE_SITE',counterparty_id=(SELECT site_id FROM resource_extraction_batch WHERE freight_lot_id||':delivery'=NEW.transaction_id),memo='Natural resource delivery from site '||(SELECT site_id FROM resource_extraction_batch WHERE freight_lot_id||':delivery'=NEW.transaction_id) WHERE transaction_id=NEW.transaction_id; END",

                "CREATE TRIGGER nonrenewable_resource_stays_depleted AFTER UPDATE OF status ON natural_resource_site WHEN NEW.renewable=0 AND NEW.remaining_units=0 AND NEW.status<>'DEPLETED' BEGIN UPDATE natural_resource_site SET status='DEPLETED',dormant_until_tick=NULL,recovery_progress=0 WHERE site_id=NEW.site_id; END",
                "CREATE TRIGGER passive_resource_recovery AFTER UPDATE OF last_cycle_tick ON passive_simulation_config WHEN NEW.last_cycle_tick IS NOT NULL AND (OLD.last_cycle_tick IS NULL OR NEW.last_cycle_tick>OLD.last_cycle_tick) BEGIN "
                        + "UPDATE natural_resource_site SET recovery_progress=MIN(100,recovery_progress+10+COALESCE((SELECT habitat_integrity/10 FROM location_ecology_state e WHERE e.location_id=natural_resource_site.location_id),5)),last_tick=NEW.last_cycle_tick WHERE world_id=NEW.world_id AND renewable=1 AND status='DORMANT' AND NEW.last_cycle_tick>=COALESCE(dormant_until_tick,NEW.last_cycle_tick); "
                        + "UPDATE natural_resource_site SET remaining_units=MAX(1,MIN(carrying_capacity,carrying_capacity/3)),richness=MIN(100,richness+10),status='SURVEYED',recovery_progress=0,dormant_until_tick=NULL,last_tick=NEW.last_cycle_tick WHERE world_id=NEW.world_id AND renewable=1 AND status='DORMANT' AND recovery_progress>=100; "
                        + "UPDATE natural_resource_site SET remaining_units=MIN(carrying_capacity,remaining_units+1),richness=MIN(100,richness+CASE WHEN NEW.last_cycle_tick%6=0 THEN 1 ELSE 0 END),last_tick=NEW.last_cycle_tick WHERE world_id=NEW.world_id AND renewable=1 AND status IN ('EXPOSED','SURVEYED') AND remaining_units<carrying_capacity; "
                        + "INSERT OR IGNORE INTO world_mission(mission_id,world_id,mission_type,status,origin_station_id,target_location_id,deterministic_seed,difficulty,reward_credits,cargo_units,progress,created_tick,updated_tick) SELECT substr(s.site_id,1,24)||printf('%012x',((NEW.last_cycle_tick*16+s.extraction_count+13)%281474976710655)),s.world_id,CASE s.resource_type WHEN 'ORE_VEIN' THEN 'MINING' WHEN 'RARE_MINERALS' THEN 'MINING' WHEN 'HYDROTHERMAL_DEPOSIT' THEN 'RESEARCH' WHEN 'BIOACTIVE_ACCUMULATOR' THEN 'RESEARCH' ELSE 'SALVAGE' END,'AVAILABLE',(SELECT ws.station_id FROM world_station ws JOIN world_location station_location ON station_location.location_id=ws.location_id JOIN world_location target_location ON target_location.location_id=s.location_id WHERE ws.world_id=s.world_id ORDER BY ABS(station_location.source_ordinal-target_location.source_ordinal),station_location.source_ordinal LIMIT 1),s.location_id,NEW.last_cycle_tick,MIN(100,20+s.richness/2+(100-s.accessibility)/3),1000+s.richness*80,MAX(1,MIN(30,s.harvest_rate)),0,NEW.last_cycle_tick,NEW.last_cycle_tick FROM natural_resource_site s WHERE s.world_id=NEW.world_id AND s.status IN ('EXPOSED','SURVEYED') AND s.remaining_units>0 AND NOT EXISTS (SELECT 1 FROM resource_harvest_mission h JOIN world_mission m ON m.mission_id=h.mission_id WHERE h.site_id=s.site_id AND m.status IN ('AVAILABLE','ASSIGNED','ACTIVE')); "
                        + "INSERT OR IGNORE INTO resource_harvest_mission(mission_id,site_id,cycle_number,created_tick) SELECT m.mission_id,s.site_id,s.extraction_count+1,NEW.last_cycle_tick FROM natural_resource_site s JOIN world_mission m ON m.mission_id=substr(s.site_id,1,24)||printf('%012x',((NEW.last_cycle_tick*16+s.extraction_count+13)%281474976710655)) WHERE s.world_id=NEW.world_id; END"
        );
    }
}
