package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 016: conserved NPC population accounting and frontier-index reconciliation. */
public final class NpcPopulationAccountingSchema {
    private NpcPopulationAccountingSchema() { }

    public static List<String> statements() {
        String total = "(p.civilians+p.industrial_workers+p.logistics_workers+p.security_personnel+"
                + "p.medical_personnel+p.scientific_personnel+p.temporary_residents+p.refugees)";
        String target = "CASE WHEN NEW.frontier_state='ABANDONED' OR "
                + "COALESCE((SELECT integrity FROM station_simulation_state WHERE station_id=NEW.station_id),0)<=0 THEN 0 "
                + "WHEN NEW.population_index<>r.last_population_index THEN MAX(0,CAST(ROUND(r.baseline_population_per_index*NEW.population_index) AS INTEGER)) "
                + "ELSE " + total + " END";
        String updateBefore = "(SELECT before_total FROM npc_population_ledger WHERE population_id=npc_population_state.population_id AND tick_sequence=NEW.last_tick)";
        String updateAfter = "(SELECT after_total FROM npc_population_ledger WHERE population_id=npc_population_state.population_id AND tick_sequence=NEW.last_tick)";
        String scaled = "CASE WHEN " + updateBefore + "<=0 THEN 0 ELSE %s*" + updateAfter + "/" + updateBefore + " END";
        String industrial = scaled.formatted("industrial_workers");
        String logistics = scaled.formatted("logistics_workers");
        String security = scaled.formatted("security_personnel");
        String medical = scaled.formatted("medical_personnel");
        String science = scaled.formatted("scientific_personnel");
        String temporary = scaled.formatted("temporary_residents");
        String refugees = scaled.formatted("refugees");

        return List.of(
                "CREATE TABLE npc_population_reconciliation (population_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, station_id TEXT NOT NULL UNIQUE, baseline_population_per_index REAL NOT NULL CHECK(baseline_population_per_index > 0), initial_population_index INTEGER NOT NULL CHECK(initial_population_index BETWEEN 0 AND 100), last_population_index INTEGER NOT NULL CHECK(last_population_index BETWEEN 0 AND 100), reconciliation_status TEXT NOT NULL CHECK(reconciliation_status IN ('ALIGNED','INDEX_GAIN','INDEX_LOSS','ABANDONED','SEEDED')), last_detailed_population INTEGER NOT NULL CHECK(last_detailed_population >= 0), last_tick INTEGER NOT NULL CHECK(last_tick >= 0), FOREIGN KEY(population_id) REFERENCES npc_population_state(population_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id))",
                "CREATE INDEX npc_population_reconciliation_tick_index ON npc_population_reconciliation(world_id,last_tick DESC,reconciliation_status)",
                "CREATE TABLE npc_population_ledger (ledger_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, population_id TEXT NOT NULL, station_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), before_total INTEGER NOT NULL CHECK(before_total >= 0), births INTEGER NOT NULL DEFAULT 0 CHECK(births >= 0), deaths INTEGER NOT NULL DEFAULT 0 CHECK(deaths >= 0), immigration INTEGER NOT NULL DEFAULT 0 CHECK(immigration >= 0), emigration INTEGER NOT NULL DEFAULT 0 CHECK(emigration >= 0), disaster_losses INTEGER NOT NULL DEFAULT 0 CHECK(disaster_losses >= 0), other_gains INTEGER NOT NULL DEFAULT 0 CHECK(other_gains >= 0), other_losses INTEGER NOT NULL DEFAULT 0 CHECK(other_losses >= 0), after_total INTEGER NOT NULL CHECK(after_total >= 0), housing_capacity INTEGER NOT NULL CHECK(housing_capacity >= 0), life_support_capacity INTEGER NOT NULL CHECK(life_support_capacity >= 0), employment_capacity INTEGER NOT NULL CHECK(employment_capacity >= 0), morale INTEGER NOT NULL CHECK(morale BETWEEN 0 AND 100), population_index_before INTEGER NOT NULL CHECK(population_index_before BETWEEN 0 AND 100), population_index_after INTEGER NOT NULL CHECK(population_index_after BETWEEN 0 AND 100), primary_cause TEXT NOT NULL CHECK(primary_cause IN ('SUPPLY_RECOVERY','SUPPLY_SHORTAGE','ABANDONMENT','OTHER')), evidence_key TEXT NOT NULL, summary TEXT NOT NULL, UNIQUE(population_id,tick_sequence), CHECK(after_total=before_total+births+immigration+other_gains-deaths-emigration-disaster_losses-other_losses), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(population_id) REFERENCES npc_population_state(population_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id))",
                "CREATE INDEX npc_population_ledger_tick_index ON npc_population_ledger(world_id,tick_sequence DESC,primary_cause,population_id)",
                "CREATE VIEW npc_population_accounting_observation AS SELECT l.ledger_id,l.world_id,l.population_id,l.station_id,ws.display_name AS station_name,l.tick_sequence,l.before_total,l.births,l.deaths,l.immigration,l.emigration,l.disaster_losses,l.other_gains,l.other_losses,l.after_total,l.housing_capacity,l.life_support_capacity,l.employment_capacity,l.morale,l.population_index_before,l.population_index_after,l.primary_cause,l.evidence_key,l.summary,r.baseline_population_per_index,r.reconciliation_status FROM npc_population_ledger l JOIN world_station ws ON ws.station_id=l.station_id JOIN npc_population_reconciliation r ON r.population_id=l.population_id",
                "CREATE TRIGGER npc_population_reconciliation_seed AFTER INSERT ON npc_population_state BEGIN INSERT OR IGNORE INTO npc_population_reconciliation(population_id,world_id,station_id,baseline_population_per_index,initial_population_index,last_population_index,reconciliation_status,last_detailed_population,last_tick) SELECT NEW.population_id,NEW.world_id,NEW.station_id,MAX(1.0,(NEW.civilians+NEW.industrial_workers+NEW.logistics_workers+NEW.security_personnel+NEW.medical_personnel+NEW.scientific_personnel+NEW.temporary_residents+NEW.refugees)*1.0/MAX(1,c.population_index)),c.population_index,c.population_index,'SEEDED',NEW.civilians+NEW.industrial_workers+NEW.logistics_workers+NEW.security_personnel+NEW.medical_personnel+NEW.scientific_personnel+NEW.temporary_residents+NEW.refugees,NEW.last_tick FROM station_civilization_state c WHERE c.station_id=NEW.station_id; END",
                "INSERT OR IGNORE INTO npc_population_reconciliation(population_id,world_id,station_id,baseline_population_per_index,initial_population_index,last_population_index,reconciliation_status,last_detailed_population,last_tick) SELECT p.population_id,p.world_id,p.station_id,MAX(1.0,(p.civilians+p.industrial_workers+p.logistics_workers+p.security_personnel+p.medical_personnel+p.scientific_personnel+p.temporary_residents+p.refugees)*1.0/MAX(1,c.population_index)),c.population_index,c.population_index,'SEEDED',p.civilians+p.industrial_workers+p.logistics_workers+p.security_personnel+p.medical_personnel+p.scientific_personnel+p.temporary_residents+p.refugees,MAX(p.last_tick,c.last_tick) FROM npc_population_state p JOIN station_civilization_state c ON c.station_id=p.station_id",
                "CREATE TRIGGER npc_population_tick_accounting AFTER UPDATE OF last_tick ON station_civilization_state WHEN NEW.last_tick>OLD.last_tick BEGIN "
                        + "INSERT OR IGNORE INTO npc_population_ledger(ledger_id,world_id,population_id,station_id,tick_sequence,before_total,births,deaths,immigration,emigration,disaster_losses,other_gains,other_losses,after_total,housing_capacity,life_support_capacity,employment_capacity,morale,population_index_before,population_index_after,primary_cause,evidence_key,summary) SELECT p.population_id||':ledger:'||NEW.last_tick,p.world_id,p.population_id,p.station_id,NEW.last_tick," + total + ",0,0,0,0,0,MAX(0,(" + target + ")-(" + total + ")),MAX(0,(" + total + ")-(" + target + ")),(" + target + "),p.housing_capacity,p.life_support_capacity,p.employment_capacity,p.morale,r.last_population_index,NEW.population_index,CASE WHEN (" + target + ")=0 AND (" + total + ")>0 THEN 'ABANDONMENT' WHEN (" + target + ")>(" + total + ") THEN 'SUPPLY_RECOVERY' WHEN (" + target + ")<(" + total + ") THEN 'SUPPLY_SHORTAGE' ELSE 'OTHER' END,CASE WHEN (" + target + ")=0 AND (" + total + ")>0 THEN 'frontier-abandonment-reconciliation' WHEN NEW.population_index<>r.last_population_index THEN 'frontier-population-index-reconciliation' ELSE 'population-accounting-no-change' END,CASE WHEN (" + target + ")>(" + total + ") THEN 'Detailed NPC population increased to reconcile an explicit rise in the civilization population index.' WHEN (" + target + ")<(" + total + ") THEN 'Detailed NPC population decreased to reconcile contraction or abandonment in the civilization frontier.' ELSE 'Detailed NPC population remained conserved during this passive tick.' END FROM npc_population_state p JOIN npc_population_reconciliation r ON r.population_id=p.population_id WHERE p.station_id=NEW.station_id; "
                        + "UPDATE npc_population_state SET industrial_workers=" + industrial + ",logistics_workers=" + logistics + ",security_personnel=" + security + ",medical_personnel=" + medical + ",scientific_personnel=" + science + ",temporary_residents=" + temporary + ",refugees=" + refugees + ",civilians=MAX(0," + updateAfter + "-(" + industrial + "+" + logistics + "+" + security + "+" + medical + "+" + science + "+" + temporary + "+" + refugees + ")),last_tick=NEW.last_tick WHERE station_id=NEW.station_id AND EXISTS(SELECT 1 FROM npc_population_ledger l WHERE l.population_id=npc_population_state.population_id AND l.tick_sequence=NEW.last_tick); "
                        + "UPDATE npc_population_reconciliation SET last_population_index=NEW.population_index,reconciliation_status=CASE WHEN (SELECT after_total FROM npc_population_ledger WHERE population_id=npc_population_reconciliation.population_id AND tick_sequence=NEW.last_tick)=0 THEN 'ABANDONED' WHEN NEW.population_index>last_population_index THEN 'INDEX_GAIN' WHEN NEW.population_index<last_population_index THEN 'INDEX_LOSS' ELSE 'ALIGNED' END,last_detailed_population=(SELECT after_total FROM npc_population_ledger WHERE population_id=npc_population_reconciliation.population_id AND tick_sequence=NEW.last_tick),last_tick=NEW.last_tick WHERE station_id=NEW.station_id; "
                        + "INSERT OR IGNORE INTO world_observation_event(event_id,world_id,tick_sequence,canonical_time,category,primary_entity_type,primary_entity_id,primary_cause,primary_evidence_key,contributing_factors,magnitude,visibility,confidence,summary) SELECT l.ledger_id||':event',l.world_id,l.tick_sequence,COALESCE((SELECT after_canonical_time FROM simulation_command_receipt WHERE world_id=l.world_id ORDER BY execution_sequence DESC LIMIT 1),(SELECT canonical_time FROM world_metadata WHERE world_id=l.world_id),(SELECT created_at FROM world_metadata WHERE world_id=l.world_id)),'POPULATION','NPC_POPULATION',l.population_id,l.primary_cause,l.evidence_key,'',ABS(l.after_total-l.before_total),'OMNISCIENT',100,l.summary FROM npc_population_ledger l WHERE l.station_id=NEW.station_id AND l.tick_sequence=NEW.last_tick AND l.after_total<>l.before_total; "
                        + "INSERT OR IGNORE INTO observation_metric_series(metric_id,world_id,entity_type,entity_id,metric_key,tick_sequence,numeric_value,unit,snapshot_id) SELECT l.population_id||':accounted-total:'||l.tick_sequence,l.world_id,'NPC_POPULATION',l.population_id,'accounted-total-population',l.tick_sequence,l.after_total,'persons',NULL FROM npc_population_ledger l WHERE l.station_id=NEW.station_id AND l.tick_sequence=NEW.last_tick; "
                        + "INSERT OR IGNORE INTO observation_metric_series(metric_id,world_id,entity_type,entity_id,metric_key,tick_sequence,numeric_value,unit,snapshot_id) SELECT l.population_id||':frontier-index:'||l.tick_sequence,l.world_id,'NPC_POPULATION',l.population_id,'frontier-population-index',l.tick_sequence,l.population_index_after,'index',NULL FROM npc_population_ledger l WHERE l.station_id=NEW.station_id AND l.tick_sequence=NEW.last_tick; END"
        );
    }
}
