package io.github.mrcalzon02.barotrauma.persistence;

import io.github.mrcalzon02.barotrauma.observation.ObservationContracts;
import io.github.mrcalzon02.barotrauma.observation.ObservationContracts.FlowStatus;
import io.github.mrcalzon02.barotrauma.observation.ObservationContracts.ObservationCause;
import io.github.mrcalzon02.barotrauma.observation.ObservationContracts.ObservationEventCategory;
import io.github.mrcalzon02.barotrauma.observation.ObservationContracts.ObservedEntityType;
import io.github.mrcalzon02.barotrauma.observation.ObservationContracts.TerritoryStatus;
import io.github.mrcalzon02.barotrauma.observation.ObservationContracts.VisibilityMode;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/** Schema 015: persistent observation populations, territories, influence, flows, evidence, and snapshots. */
public final class ObservationFoundationSchema {
    private ObservationFoundationSchema() { }

    public static List<String> statements() {
        String eventCategories = sqlValues(ObservationEventCategory.values());
        String entityTypes = sqlValues(ObservedEntityType.values());
        String causes = sqlValues(ObservationCause.values());
        String flowStatuses = sqlValues(FlowStatus.values());
        String territoryStatuses = sqlValues(TerritoryStatus.values());
        String visibilityModes = sqlValues(VisibilityMode.values());
        String rulesVersion = quote(ObservationContracts.RULES_VERSION);

        List<String> statements = new ArrayList<>();
        statements.add("CREATE TABLE npc_population_state (population_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, station_id TEXT NOT NULL UNIQUE, civilians INTEGER NOT NULL CHECK(civilians >= 0), industrial_workers INTEGER NOT NULL CHECK(industrial_workers >= 0), logistics_workers INTEGER NOT NULL CHECK(logistics_workers >= 0), security_personnel INTEGER NOT NULL CHECK(security_personnel >= 0), medical_personnel INTEGER NOT NULL CHECK(medical_personnel >= 0), scientific_personnel INTEGER NOT NULL CHECK(scientific_personnel >= 0), temporary_residents INTEGER NOT NULL CHECK(temporary_residents >= 0), refugees INTEGER NOT NULL CHECK(refugees >= 0), housing_capacity INTEGER NOT NULL CHECK(housing_capacity >= 0), life_support_capacity INTEGER NOT NULL CHECK(life_support_capacity >= 0), employment_capacity INTEGER NOT NULL CHECK(employment_capacity >= 0), morale INTEGER NOT NULL CHECK(morale BETWEEN 0 AND 100), seed_source TEXT NOT NULL, last_tick INTEGER NOT NULL CHECK(last_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id))");
        statements.add("CREATE INDEX npc_population_world_tick_index ON npc_population_state(world_id,last_tick DESC,station_id)");
        statements.add("CREATE TABLE creature_population_state (population_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, location_id TEXT NOT NULL, species_key TEXT NOT NULL, population_class TEXT NOT NULL CHECK(population_class IN ('HERBIVORE','PREDATOR','SCAVENGER','BIOACCUMULATOR')), estimated_count INTEGER NOT NULL CHECK(estimated_count >= 0), biomass INTEGER NOT NULL CHECK(biomass BETWEEN 0 AND 100), juvenile_percent INTEGER NOT NULL CHECK(juvenile_percent BETWEEN 0 AND 100), mature_percent INTEGER NOT NULL CHECK(mature_percent BETWEEN 0 AND 100), breeding_percent INTEGER NOT NULL CHECK(breeding_percent BETWEEN 0 AND 100), health INTEGER NOT NULL CHECK(health BETWEEN 0 AND 100), food_stress INTEGER NOT NULL CHECK(food_stress BETWEEN 0 AND 100), habitat_support INTEGER NOT NULL CHECK(habitat_support BETWEEN 0 AND 100), migration_pressure INTEGER NOT NULL CHECK(migration_pressure BETWEEN 0 AND 100), recent_losses INTEGER NOT NULL DEFAULT 0 CHECK(recent_losses >= 0), observation_confidence INTEGER NOT NULL CHECK(observation_confidence BETWEEN 0 AND 100), seed_source TEXT NOT NULL, last_tick INTEGER NOT NULL CHECK(last_tick >= 0), UNIQUE(location_id,species_key), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(location_id) REFERENCES world_location(location_id))");
        statements.add("CREATE INDEX creature_population_world_location_index ON creature_population_state(world_id,location_id,population_class,biomass DESC)");
        statements.add("CREATE TABLE creature_territory_state (territory_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, creature_population_id TEXT NOT NULL UNIQUE, location_id TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN (" + territoryStatuses + ")), territory_pressure INTEGER NOT NULL CHECK(territory_pressure BETWEEN 0 AND 100), nest_strength INTEGER NOT NULL DEFAULT 0 CHECK(nest_strength BETWEEN 0 AND 100), carrying_pressure INTEGER NOT NULL CHECK(carrying_pressure BETWEEN 0 AND 100), last_tick INTEGER NOT NULL CHECK(last_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(creature_population_id) REFERENCES creature_population_state(population_id), FOREIGN KEY(location_id) REFERENCES world_location(location_id))");
        statements.add("CREATE INDEX creature_territory_status_index ON creature_territory_state(world_id,status,territory_pressure DESC,last_tick DESC)");
        statements.add("CREATE TABLE faction_location_presence (presence_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, location_id TEXT NOT NULL, faction_key TEXT NOT NULL, influence INTEGER NOT NULL CHECK(influence BETWEEN 0 AND 100), presence_state TEXT NOT NULL CHECK(presence_state IN ('DOMINANT','MINORITY','NEUTRAL','CONTESTED','COVERT','WITHDRAWN')), seed_source TEXT NOT NULL, last_tick INTEGER NOT NULL CHECK(last_tick >= 0), UNIQUE(location_id,faction_key), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(location_id) REFERENCES world_location(location_id))");
        statements.add("CREATE INDEX faction_location_influence_index ON faction_location_presence(world_id,location_id,influence DESC,faction_key)");
        statements.add("CREATE TABLE population_flow (flow_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, entity_type TEXT NOT NULL CHECK(entity_type IN ('NPC_POPULATION','CREATURE_POPULATION')), population_id TEXT NOT NULL, origin_location_id TEXT NOT NULL, destination_location_id TEXT, quantity INTEGER NOT NULL CHECK(quantity >= 0), cause TEXT NOT NULL CHECK(cause IN (" + causes + ")), status TEXT NOT NULL CHECK(status IN (" + flowStatuses + ")), departure_tick INTEGER CHECK(departure_tick >= 0), arrival_tick INTEGER CHECK(arrival_tick >= 0), losses INTEGER NOT NULL DEFAULT 0 CHECK(losses >= 0 AND losses <= quantity), created_tick INTEGER NOT NULL CHECK(created_tick >= 0), updated_tick INTEGER NOT NULL CHECK(updated_tick >= created_tick), summary TEXT NOT NULL, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(origin_location_id) REFERENCES world_location(location_id), FOREIGN KEY(destination_location_id) REFERENCES world_location(location_id))");
        statements.add("CREATE INDEX population_flow_status_index ON population_flow(world_id,status,updated_tick DESC,entity_type)");
        statements.add("CREATE TABLE world_observation_event (event_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), canonical_time TEXT NOT NULL, category TEXT NOT NULL CHECK(category IN (" + eventCategories + ")), primary_entity_type TEXT NOT NULL CHECK(primary_entity_type IN (" + entityTypes + ")), primary_entity_id TEXT NOT NULL, primary_cause TEXT NOT NULL CHECK(primary_cause IN (" + causes + ")), primary_evidence_key TEXT NOT NULL, contributing_factors TEXT NOT NULL DEFAULT '', magnitude INTEGER NOT NULL DEFAULT 0 CHECK(magnitude >= 0), visibility TEXT NOT NULL CHECK(visibility IN (" + visibilityModes + ")), confidence INTEGER NOT NULL CHECK(confidence BETWEEN 0 AND 100), summary TEXT NOT NULL, UNIQUE(world_id,tick_sequence,event_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))");
        statements.add("CREATE INDEX world_observation_event_tick_index ON world_observation_event(world_id,tick_sequence DESC,category,primary_entity_type)");
        statements.add("CREATE TABLE observation_snapshot (snapshot_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), parent_snapshot_id TEXT, rules_version TEXT NOT NULL, created_at TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('BUILDING','COMPLETE','FAILED')), source TEXT NOT NULL CHECK(source IN ('MIGRATION','POST_TICK','MANUAL','CHECKPOINT')), UNIQUE(world_id,tick_sequence,source), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(parent_snapshot_id) REFERENCES observation_snapshot(snapshot_id), CHECK(parent_snapshot_id IS NULL OR parent_snapshot_id <> snapshot_id))");
        statements.add("CREATE INDEX observation_snapshot_tick_index ON observation_snapshot(world_id,tick_sequence DESC,created_at DESC)");
        statements.add("CREATE TABLE observation_metric_series (metric_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, entity_type TEXT NOT NULL CHECK(entity_type IN (" + entityTypes + ")), entity_id TEXT NOT NULL, metric_key TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), numeric_value REAL NOT NULL, unit TEXT NOT NULL, snapshot_id TEXT, UNIQUE(world_id,entity_type,entity_id,metric_key,tick_sequence), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(snapshot_id) REFERENCES observation_snapshot(snapshot_id))");
        statements.add("CREATE INDEX observation_metric_lookup_index ON observation_metric_series(world_id,entity_type,entity_id,metric_key,tick_sequence DESC)");
        statements.add("CREATE TABLE observer_watch_rule (watch_rule_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, entity_type TEXT NOT NULL CHECK(entity_type IN (" + entityTypes + ")), entity_id TEXT NOT NULL, condition_key TEXT NOT NULL, threshold_value REAL, enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)), created_at TEXT NOT NULL, last_triggered_tick INTEGER CHECK(last_triggered_tick >= 0), UNIQUE(world_id,entity_type,entity_id,condition_key), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))");

        statements.add("CREATE VIEW npc_population_observation AS SELECT p.population_id,p.world_id,p.station_id,ws.display_name AS station_name,p.civilians,p.industrial_workers,p.logistics_workers,p.security_personnel,p.medical_personnel,p.scientific_personnel,p.temporary_residents,p.refugees,(p.civilians+p.industrial_workers+p.logistics_workers+p.security_personnel+p.medical_personnel+p.scientific_personnel+p.temporary_residents+p.refugees) AS total_population,p.housing_capacity,p.life_support_capacity,p.employment_capacity,p.morale,p.last_tick FROM npc_population_state p JOIN world_station ws ON ws.station_id=p.station_id");
        statements.add("CREATE VIEW creature_population_observation AS SELECT p.population_id,p.world_id,p.location_id,wl.display_name AS location_name,p.species_key,p.population_class,p.estimated_count,p.biomass,p.health,p.food_stress,p.habitat_support,p.migration_pressure,p.observation_confidence,t.status AS territory_status,t.territory_pressure,t.nest_strength,p.last_tick FROM creature_population_state p JOIN world_location wl ON wl.location_id=p.location_id LEFT JOIN creature_territory_state t ON t.creature_population_id=p.population_id");
        statements.add("CREATE VIEW observation_world_summary AS SELECT w.world_id,w.display_name,(SELECT COUNT(*) FROM npc_population_state p WHERE p.world_id=w.world_id) AS npc_populations,(SELECT COALESCE(SUM(civilians+industrial_workers+logistics_workers+security_personnel+medical_personnel+scientific_personnel+temporary_residents+refugees),0) FROM npc_population_state p WHERE p.world_id=w.world_id) AS npc_population_total,(SELECT COUNT(*) FROM creature_population_state c WHERE c.world_id=w.world_id) AS creature_populations,(SELECT COALESCE(SUM(estimated_count),0) FROM creature_population_state c WHERE c.world_id=w.world_id) AS creature_estimated_total,(SELECT COUNT(*) FROM faction_location_presence f WHERE f.world_id=w.world_id) AS faction_presences,(SELECT COUNT(*) FROM world_observation_event e WHERE e.world_id=w.world_id) AS observation_events FROM world_metadata w");

        statements.add("CREATE TRIGGER observation_world_root_snapshot AFTER INSERT ON world_metadata BEGIN INSERT OR IGNORE INTO observation_snapshot(snapshot_id,world_id,tick_sequence,parent_snapshot_id,rules_version,created_at,status,source) VALUES (substr(NEW.world_id,1,24)||'00000000000a',NEW.world_id,0,NULL," + rulesVersion + ",NEW.created_at,'COMPLETE','MIGRATION'); END");
        statements.add("CREATE TRIGGER observation_npc_population_event AFTER INSERT ON npc_population_state BEGIN INSERT OR IGNORE INTO world_observation_event(event_id,world_id,tick_sequence,canonical_time,category,primary_entity_type,primary_entity_id,primary_cause,primary_evidence_key,magnitude,visibility,confidence,summary) SELECT NEW.population_id,NEW.world_id,NEW.last_tick,COALESCE(w.canonical_time,w.created_at),'POPULATION','NPC_POPULATION',NEW.population_id,'SYSTEM_INITIALIZATION','schema-015-npc-population-seed',NEW.civilians+NEW.industrial_workers+NEW.logistics_workers+NEW.security_personnel+NEW.medical_personnel+NEW.scientific_personnel+NEW.temporary_residents+NEW.refugees,'OMNISCIENT',100,'Initial NPC population observation was derived from the schema-014 station and civilization state.' FROM world_metadata w WHERE w.world_id=NEW.world_id; INSERT OR IGNORE INTO observation_metric_series(metric_id,world_id,entity_type,entity_id,metric_key,tick_sequence,numeric_value,unit,snapshot_id) VALUES (NEW.population_id||':total:'||NEW.last_tick,NEW.world_id,'NPC_POPULATION',NEW.population_id,'total-population',NEW.last_tick,NEW.civilians+NEW.industrial_workers+NEW.logistics_workers+NEW.security_personnel+NEW.medical_personnel+NEW.scientific_personnel+NEW.temporary_residents+NEW.refugees,'persons',(SELECT snapshot_id FROM observation_snapshot WHERE world_id=NEW.world_id ORDER BY tick_sequence LIMIT 1)); END");
        statements.add("CREATE TRIGGER observation_creature_population_event AFTER INSERT ON creature_population_state BEGIN INSERT OR IGNORE INTO world_observation_event(event_id,world_id,tick_sequence,canonical_time,category,primary_entity_type,primary_entity_id,primary_cause,primary_evidence_key,magnitude,visibility,confidence,summary) SELECT NEW.population_id,NEW.world_id,NEW.last_tick,COALESCE(w.canonical_time,w.created_at),'CREATURE','CREATURE_POPULATION',NEW.population_id,'SYSTEM_INITIALIZATION','schema-015-creature-population-seed',NEW.estimated_count,'OMNISCIENT',NEW.observation_confidence,'Initial creature population observation was derived from the schema-014 ecological state.' FROM world_metadata w WHERE w.world_id=NEW.world_id; INSERT OR IGNORE INTO observation_metric_series(metric_id,world_id,entity_type,entity_id,metric_key,tick_sequence,numeric_value,unit,snapshot_id) VALUES (NEW.population_id||':biomass:'||NEW.last_tick,NEW.world_id,'CREATURE_POPULATION',NEW.population_id,'biomass-index',NEW.last_tick,NEW.biomass,'index',(SELECT snapshot_id FROM observation_snapshot WHERE world_id=NEW.world_id ORDER BY tick_sequence LIMIT 1)); END");
        statements.add("CREATE TRIGGER observation_creature_territory_seed AFTER INSERT ON creature_population_state BEGIN INSERT OR IGNORE INTO creature_territory_state(territory_id,world_id,creature_population_id,location_id,status,territory_pressure,nest_strength,carrying_pressure,last_tick) SELECT substr(NEW.world_id,1,24)||printf('%012x',(wl.source_ordinal*16+CASE NEW.population_class WHEN 'HERBIVORE' THEN 6 WHEN 'PREDATOR' THEN 7 WHEN 'SCAVENGER' THEN 8 ELSE 9 END)%281474976710655),NEW.world_id,NEW.population_id,NEW.location_id,CASE WHEN NEW.biomass=0 THEN 'DORMANT' WHEN NEW.food_stress>=75 THEN 'COLLAPSING' WHEN NEW.migration_pressure>=70 THEN 'MIGRATING' WHEN NEW.biomass>=80 THEN 'OVERPOPULATED' WHEN NEW.population_class='PREDATOR' AND NEW.biomass>=45 THEN 'NESTING' WHEN NEW.biomass>=55 THEN 'EXPANDING' ELSE 'FORAGING' END,MAX(0,MIN(100,NEW.migration_pressure+NEW.biomass/3)),CASE WHEN NEW.population_class='PREDATOR' AND NEW.biomass>=45 THEN MIN(100,NEW.biomass) ELSE 0 END,MAX(0,MIN(100,NEW.biomass+NEW.food_stress/2)),NEW.last_tick FROM world_location wl WHERE wl.location_id=NEW.location_id; END");
        statements.add("CREATE TRIGGER observation_npc_population_seed AFTER INSERT ON station_civilization_state BEGIN INSERT OR IGNORE INTO npc_population_state(population_id,world_id,station_id,civilians,industrial_workers,logistics_workers,security_personnel,medical_personnel,scientific_personnel,temporary_residents,refugees,housing_capacity,life_support_capacity,employment_capacity,morale,seed_source,last_tick) SELECT substr(NEW.world_id,1,24)||printf('%012x',(wl.source_ordinal*16+1)%281474976710655),NEW.world_id,NEW.station_id,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index*5 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index*s.industry/25 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index*2 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index*s.security/30 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index/10 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index/12 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.surplus_ticks END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.shortage_ticks END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index*12+s.industry*5 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index*14+s.supplies*2 END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 0 ELSE NEW.population_index*8+s.industry*8 END,MAX(0,MIN(100,NEW.civilization_strength+s.supplies/4-s.threat/4)),'SCHEMA_014_CIVILIZATION',MAX(NEW.last_tick,s.last_tick) FROM station_simulation_state s JOIN world_station ws ON ws.station_id=NEW.station_id JOIN world_location wl ON wl.location_id=ws.location_id WHERE s.station_id=NEW.station_id; END");
        statements.add("CREATE TRIGGER observation_creature_population_seed AFTER INSERT ON location_ecology_state BEGIN " + creatureSeedSql("NEW.location_id", "NEW.world_id", "NEW.primary_producers", "NEW.herbivore_biomass", "NEW.predator_biomass", "NEW.scavenger_biomass", "NEW.bioaccumulator_mass", "NEW.habitat_integrity", "NEW.migration_pressure", "NEW.last_tick") + " END");
        statements.add("CREATE TRIGGER observation_location_faction_seed AFTER INSERT ON world_location WHEN NEW.faction IS NOT NULL AND trim(NEW.faction)<>'' BEGIN INSERT OR IGNORE INTO faction_location_presence(presence_id,world_id,location_id,faction_key,influence,presence_state,seed_source,last_tick) VALUES (NEW.location_id||':'||lower(replace(trim(NEW.faction),' ','-')),NEW.world_id,NEW.location_id,trim(NEW.faction),CASE WHEN NEW.is_station=1 THEN 70 ELSE 35 END,CASE WHEN NEW.is_station=1 THEN 'DOMINANT' ELSE 'MINORITY' END,'SCHEMA_014_LOCATION',0); END");
        statements.add("CREATE TRIGGER observation_station_faction_seed AFTER INSERT ON world_station WHEN NEW.faction IS NOT NULL AND trim(NEW.faction)<>'' BEGIN INSERT OR IGNORE INTO faction_location_presence(presence_id,world_id,location_id,faction_key,influence,presence_state,seed_source,last_tick) VALUES (NEW.location_id||':'||lower(replace(trim(NEW.faction),' ','-')),NEW.world_id,NEW.location_id,trim(NEW.faction),70,'DOMINANT','SCHEMA_014_STATION',0); UPDATE faction_location_presence SET influence=MAX(influence,70),presence_state='DOMINANT',seed_source='SCHEMA_014_STATION' WHERE location_id=NEW.location_id AND faction_key=trim(NEW.faction); END");

        statements.add("INSERT OR IGNORE INTO observation_snapshot(snapshot_id,world_id,tick_sequence,parent_snapshot_id,rules_version,created_at,status,source) SELECT substr(w.world_id,1,24)||'00000000000a',w.world_id,COALESCE(s.current_tick_sequence,s.imported_tick_sequence,0),NULL," + rulesVersion + ",COALESCE(w.canonical_time,w.created_at),'COMPLETE','MIGRATION' FROM world_metadata w LEFT JOIN world_simulation_metadata s ON s.world_id=w.world_id");
        statements.add("INSERT OR IGNORE INTO faction_location_presence(presence_id,world_id,location_id,faction_key,influence,presence_state,seed_source,last_tick) SELECT wl.location_id||':'||lower(replace(trim(COALESCE(ws.faction,wl.faction)),' ','-')),wl.world_id,wl.location_id,trim(COALESCE(ws.faction,wl.faction)),CASE WHEN ws.station_id IS NOT NULL OR wl.is_station=1 THEN 70 ELSE 35 END,CASE WHEN ws.station_id IS NOT NULL OR wl.is_station=1 THEN 'DOMINANT' ELSE 'MINORITY' END,CASE WHEN ws.station_id IS NOT NULL THEN 'SCHEMA_014_STATION' ELSE 'SCHEMA_014_LOCATION' END,COALESCE(c.last_tick,e.last_tick,0) FROM world_location wl LEFT JOIN world_station ws ON ws.location_id=wl.location_id LEFT JOIN station_civilization_state c ON c.station_id=ws.station_id LEFT JOIN location_ecology_state e ON e.location_id=wl.location_id WHERE COALESCE(ws.faction,wl.faction) IS NOT NULL AND trim(COALESCE(ws.faction,wl.faction))<>''");
        statements.add("INSERT OR IGNORE INTO npc_population_state(population_id,world_id,station_id,civilians,industrial_workers,logistics_workers,security_personnel,medical_personnel,scientific_personnel,temporary_residents,refugees,housing_capacity,life_support_capacity,employment_capacity,morale,seed_source,last_tick) SELECT substr(c.world_id,1,24)||printf('%012x',(wl.source_ordinal*16+1)%281474976710655),c.world_id,c.station_id,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index*5 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index*s.industry/25 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index*2 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index*s.security/30 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index/10 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index/12 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.surplus_ticks END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.shortage_ticks END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index*12+s.industry*5 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index*14+s.supplies*2 END,CASE WHEN c.frontier_state='ABANDONED' THEN 0 ELSE c.population_index*8+s.industry*8 END,MAX(0,MIN(100,c.civilization_strength+s.supplies/4-s.threat/4)),'SCHEMA_014_CIVILIZATION',MAX(c.last_tick,s.last_tick) FROM station_civilization_state c JOIN station_simulation_state s ON s.station_id=c.station_id JOIN world_station ws ON ws.station_id=c.station_id JOIN world_location wl ON wl.location_id=ws.location_id");
        statements.add("INSERT OR IGNORE INTO creature_population_state(population_id,world_id,location_id,species_key,population_class,estimated_count,biomass,juvenile_percent,mature_percent,breeding_percent,health,food_stress,habitat_support,migration_pressure,recent_losses,observation_confidence,seed_source,last_tick) " + creatureSeedSelect("e.location_id", "e.world_id", "e.primary_producers", "e.herbivore_biomass", "e.predator_biomass", "e.scavenger_biomass", "e.bioaccumulator_mass", "e.habitat_integrity", "e.migration_pressure", "e.last_tick").replace("FROM world_location wl WHERE wl.location_id=e.location_id", "FROM location_ecology_state e JOIN world_location wl ON wl.location_id=e.location_id"));
        return List.copyOf(statements);
    }

    private static String creatureSeedSql(String location, String world, String producers, String herbivore,
                                          String predator, String scavenger, String bioaccumulator,
                                          String habitat, String migration, String tick) {
        return "INSERT OR IGNORE INTO creature_population_state(population_id,world_id,location_id,species_key,population_class,estimated_count,biomass,juvenile_percent,mature_percent,breeding_percent,health,food_stress,habitat_support,migration_pressure,recent_losses,observation_confidence,seed_source,last_tick) "
                + creatureSeedSelect(location, world, producers, herbivore, predator, scavenger,
                bioaccumulator, habitat, migration, tick) + ";";
    }

    private static String creatureSeedSelect(String location, String world, String producers, String herbivore,
                                             String predator, String scavenger, String bioaccumulator,
                                             String habitat, String migration, String tick) {
        String confidence = "CASE WHEN wl.is_station=1 THEN 75 ELSE 45 END";
        return "SELECT substr(" + world + ",1,24)||printf('%012x',(wl.source_ordinal*16+2)%281474976710655)," + world + "," + location + ",'guild-herbivore','HERBIVORE'," + herbivore + "*8," + herbivore + ",30,55,15," + habitat + ",MAX(0,50-" + producers + ")," + producers + "," + migration + ",0," + confidence + ",'SCHEMA_014_ECOLOGY'," + tick + " FROM world_location wl WHERE wl.location_id=" + location
                + " UNION ALL SELECT substr(" + world + ",1,24)||printf('%012x',(wl.source_ordinal*16+3)%281474976710655)," + world + "," + location + ",'guild-predator','PREDATOR'," + predator + "*3," + predator + ",20,65,15," + habitat + ",MAX(0,55-" + herbivore + ")," + herbivore + "," + migration + ",0," + confidence + ",'SCHEMA_014_ECOLOGY'," + tick + " FROM world_location wl WHERE wl.location_id=" + location
                + " UNION ALL SELECT substr(" + world + ",1,24)||printf('%012x',(wl.source_ordinal*16+4)%281474976710655)," + world + "," + location + ",'guild-scavenger','SCAVENGER'," + scavenger + "*6," + scavenger + ",25,60,15," + habitat + ",MAX(0,45-(" + predator + "+" + herbivore + ")/2),MAX(" + scavenger + ",(" + predator + "+" + herbivore + ")/2)," + migration + ",0," + confidence + ",'SCHEMA_014_ECOLOGY'," + tick + " FROM world_location wl WHERE wl.location_id=" + location
                + " UNION ALL SELECT substr(" + world + ",1,24)||printf('%012x',(wl.source_ordinal*16+5)%281474976710655)," + world + "," + location + ",'guild-bioaccumulator','BIOACCUMULATOR'," + bioaccumulator + "*5," + bioaccumulator + ",35,50,15," + habitat + ",MAX(0,40-" + bioaccumulator + "),MAX(" + bioaccumulator + "," + producers + ")," + migration + ",0," + confidence + ",'SCHEMA_014_ECOLOGY'," + tick + " FROM world_location wl WHERE wl.location_id=" + location;
    }

    private static String sqlValues(Enum<?>[] values) {
        return Stream.of(values).map(value -> quote(value.name())).collect(Collectors.joining(","));
    }

    private static String quote(String value) {
        return "'" + value.replace("'", "''") + "'";
    }
}
