package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 004: persistent passive-world workloads visible from the Europa map. */
public final class PassiveWorldSchema {
    private PassiveWorldSchema() { }

    public static List<String> statements() {
        return List.of(
                "CREATE TABLE passive_simulation_config (world_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0,1)), cadence_seconds INTEGER NOT NULL DEFAULT 5 CHECK(cadence_seconds BETWEEN 1 AND 3600), ticks_per_cycle INTEGER NOT NULL DEFAULT 1 CHECK(ticks_per_cycle BETWEEN 1 AND 1000), updated_at TEXT NOT NULL, last_cycle_at TEXT, last_cycle_tick INTEGER CHECK(last_cycle_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))",
                "CREATE TABLE station_simulation_state (station_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, credits INTEGER NOT NULL DEFAULT 10000, supplies INTEGER NOT NULL DEFAULT 100 CHECK(supplies >= 0), ore INTEGER NOT NULL DEFAULT 25 CHECK(ore >= 0), industry INTEGER NOT NULL DEFAULT 50 CHECK(industry BETWEEN 0 AND 100), security INTEGER NOT NULL DEFAULT 50 CHECK(security BETWEEN 0 AND 100), integrity INTEGER NOT NULL DEFAULT 100 CHECK(integrity BETWEEN 0 AND 100), threat INTEGER NOT NULL DEFAULT 10 CHECK(threat BETWEEN 0 AND 100), research INTEGER NOT NULL DEFAULT 0 CHECK(research >= 0), status TEXT NOT NULL DEFAULT 'STABLE' CHECK(status IN ('RISING','STABLE','STRAINED','BESIEGED','FALLEN')), last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), FOREIGN KEY(station_id) REFERENCES world_station(station_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))",
                "CREATE INDEX station_simulation_status_index ON station_simulation_state(world_id, status, threat DESC)",
                "CREATE TABLE world_mission (mission_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, mission_type TEXT NOT NULL CHECK(mission_type IN ('TRADE','MINING','FAUNA_CLEARING','DEFENSE','RESEARCH','SALVAGE','TRANSIT')), status TEXT NOT NULL CHECK(status IN ('AVAILABLE','ASSIGNED','ACTIVE','COMPLETE','FAILED','CANCELLED')), origin_station_id TEXT, target_location_id TEXT NOT NULL, assigned_npc_vessel_id TEXT, deterministic_seed INTEGER NOT NULL, difficulty INTEGER NOT NULL CHECK(difficulty BETWEEN 1 AND 100), reward_credits INTEGER NOT NULL DEFAULT 0, cargo_units INTEGER NOT NULL DEFAULT 0 CHECK(cargo_units >= 0), progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100), created_tick INTEGER NOT NULL CHECK(created_tick >= 0), updated_tick INTEGER NOT NULL CHECK(updated_tick >= 0), completed_tick INTEGER CHECK(completed_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(origin_station_id) REFERENCES world_station(station_id), FOREIGN KEY(target_location_id) REFERENCES world_location(location_id))",
                "CREATE INDEX world_mission_status_index ON world_mission(world_id, status, mission_type, created_tick)",
                "CREATE TABLE npc_vessel (npc_vessel_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, display_name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('TRADER','MINER','HUNTER','PATROL','RESEARCH','SALVAGE','COURIER')), home_station_id TEXT, current_location_id TEXT NOT NULL, destination_location_id TEXT, mission_id TEXT, status TEXT NOT NULL CHECK(status IN ('DOCKED','PREPARING','IN_TRANSIT','WORKING','RETURNING','DISABLED','LOST')), hull INTEGER NOT NULL DEFAULT 100 CHECK(hull BETWEEN 0 AND 100), supplies INTEGER NOT NULL DEFAULT 100 CHECK(supplies >= 0), cargo INTEGER NOT NULL DEFAULT 0 CHECK(cargo >= 0), crew_quality INTEGER NOT NULL DEFAULT 50 CHECK(crew_quality BETWEEN 1 AND 100), navigation INTEGER NOT NULL DEFAULT 50 CHECK(navigation BETWEEN 1 AND 100), engineering INTEGER NOT NULL DEFAULT 50 CHECK(engineering BETWEEN 1 AND 100), combat INTEGER NOT NULL DEFAULT 50 CHECK(combat BETWEEN 1 AND 100), mining INTEGER NOT NULL DEFAULT 50 CHECK(mining BETWEEN 1 AND 100), research INTEGER NOT NULL DEFAULT 50 CHECK(research BETWEEN 1 AND 100), route_progress INTEGER NOT NULL DEFAULT 0 CHECK(route_progress >= 0), route_ticks_required INTEGER NOT NULL DEFAULT 1 CHECK(route_ticks_required >= 1), deterministic_seed INTEGER NOT NULL, last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(home_station_id) REFERENCES world_station(station_id), FOREIGN KEY(current_location_id) REFERENCES world_location(location_id), FOREIGN KEY(destination_location_id) REFERENCES world_location(location_id), FOREIGN KEY(mission_id) REFERENCES world_mission(mission_id))",
                "CREATE INDEX npc_vessel_status_index ON npc_vessel(world_id, status, role, last_tick)",
                "CREATE TABLE npc_voyage_log (log_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, npc_vessel_id TEXT NOT NULL, mission_id TEXT, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), canonical_time TEXT NOT NULL, event_type TEXT NOT NULL, severity INTEGER NOT NULL CHECK(severity BETWEEN 0 AND 100), summary TEXT NOT NULL, details TEXT NOT NULL, resolution TEXT NOT NULL, hull_delta INTEGER NOT NULL DEFAULT 0, supplies_delta INTEGER NOT NULL DEFAULT 0, station_delta INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id), FOREIGN KEY(mission_id) REFERENCES world_mission(mission_id))",
                "CREATE INDEX npc_voyage_log_index ON npc_voyage_log(npc_vessel_id, tick_sequence DESC)",
                "CREATE TABLE world_encounter (encounter_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, npc_vessel_id TEXT NOT NULL, mission_id TEXT, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), canonical_time TEXT NOT NULL, hazard_type TEXT NOT NULL, challenge INTEGER NOT NULL CHECK(challenge BETWEEN 1 AND 100), resolution_roll INTEGER NOT NULL CHECK(resolution_roll BETWEEN 1 AND 100), margin INTEGER NOT NULL, outcome TEXT NOT NULL CHECK(outcome IN ('TRIUMPH','SUCCESS','COSTLY_SUCCESS','SETBACK','DISASTER')), narrative TEXT NOT NULL, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id), FOREIGN KEY(mission_id) REFERENCES world_mission(mission_id))",
                "CREATE INDEX world_encounter_tick_index ON world_encounter(world_id, tick_sequence DESC)",
                "CREATE TABLE station_research_project (project_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, station_id TEXT NOT NULL, topic TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('PROPOSED','ACTIVE','COMPLETE','STALLED','ABANDONED')), progress INTEGER NOT NULL DEFAULT 0 CHECK(progress >= 0), target INTEGER NOT NULL CHECK(target > 0), created_tick INTEGER NOT NULL CHECK(created_tick >= 0), updated_tick INTEGER NOT NULL CHECK(updated_tick >= 0), completed_tick INTEGER CHECK(completed_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id))",
                "CREATE INDEX station_research_status_index ON station_research_project(world_id, status, updated_tick)"
        );
    }
}
