package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 020: carrier-neutral freight delivery stories and typed station recovery changes. */
public final class StationDeliveryCausalitySchema {
    private StationDeliveryCausalitySchema() { }

    public static List<String> statements() {
        return List.of(
                "CREATE TABLE station_delivery_baseline (lot_id TEXT PRIMARY KEY,station_id TEXT NOT NULL,tick_sequence INTEGER NOT NULL,inventory_before INTEGER NOT NULL CHECK(inventory_before>=0),credits_before INTEGER NOT NULL,supplies_before INTEGER NOT NULL CHECK(supplies_before>=0),integrity_before INTEGER NOT NULL CHECK(integrity_before BETWEEN 0 AND 100),security_before INTEGER NOT NULL CHECK(security_before BETWEEN 0 AND 100),industry_before INTEGER NOT NULL CHECK(industry_before BETWEEN 0 AND 100),shortage_ticks_before INTEGER NOT NULL CHECK(shortage_ticks_before>=0),surplus_ticks_before INTEGER NOT NULL CHECK(surplus_ticks_before>=0),civilization_before INTEGER NOT NULL CHECK(civilization_before BETWEEN 0 AND 100),fauna_before INTEGER NOT NULL CHECK(fauna_before BETWEEN 0 AND 100),carrier_type TEXT NOT NULL CHECK(carrier_type IN ('PLAYER_VESSEL','NPC_VESSEL','UNASSIGNED')),carrier_id TEXT,FOREIGN KEY(lot_id) REFERENCES freight_lot(lot_id) ON DELETE CASCADE,FOREIGN KEY(station_id) REFERENCES world_station(station_id))",

                "CREATE TRIGGER station_delivery_capture BEFORE UPDATE OF status ON freight_lot WHEN NEW.status='DELIVERED' AND OLD.status<>'DELIVERED' AND NEW.destination_station_id IS NOT NULL BEGIN "
                        + "INSERT OR REPLACE INTO station_delivery_baseline(lot_id,station_id,tick_sequence,inventory_before,credits_before,supplies_before,integrity_before,security_before,industry_before,shortage_ticks_before,surplus_ticks_before,civilization_before,fauna_before,carrier_type,carrier_id) "
                        + "SELECT NEW.lot_id,NEW.destination_station_id,NEW.updated_tick,MAX(0,COALESCE(inv.quantity,0)-CASE WHEN NEW.assigned_npc_vessel_id IS NULL THEN NEW.quantity ELSE 0 END),s.credits,s.supplies,s.integrity,s.security,s.industry,COALESCE(c.shortage_ticks,0),COALESCE(c.surplus_ticks,0),COALESCE(c.civilization_strength,0),COALESCE(c.fauna_pressure,0),CASE WHEN NEW.assigned_player_vessel_id IS NOT NULL THEN 'PLAYER_VESSEL' WHEN NEW.assigned_npc_vessel_id IS NOT NULL THEN 'NPC_VESSEL' ELSE 'UNASSIGNED' END,COALESCE(NEW.assigned_player_vessel_id,NEW.assigned_npc_vessel_id) "
                        + "FROM station_simulation_state s LEFT JOIN station_inventory inv ON inv.station_id=NEW.destination_station_id AND inv.item_id=NEW.item_id LEFT JOIN station_civilization_state c ON c.station_id=NEW.destination_station_id WHERE s.station_id=NEW.destination_station_id; END",

                "CREATE TRIGGER station_delivery_causal_event AFTER UPDATE OF status ON freight_lot WHEN NEW.status='DELIVERED' AND OLD.status<>'DELIVERED' AND EXISTS (SELECT 1 FROM station_delivery_baseline WHERE lot_id=NEW.lot_id) BEGIN "
                        + "INSERT OR IGNORE INTO station_event(event_id,world_id,station_id,tick_sequence,canonical_time,event_type,severity,headline,narrative,actor_type,actor_id,cause_type,cause_id,deterministic_key,visibility,correlation_id,policy_version,created_at) "
                        + "SELECT NEW.lot_id||':delivery-event',NEW.world_id,NEW.destination_station_id,NEW.updated_tick,m.canonical_time,'DELIVERY',CASE WHEN NEW.item_id IN ('item-rations','item-medical','item-fuel','item-ammunition','item-steel') THEN 1 ELSE 0 END,'Freight delivered: '||i.display_name,"
                        + "CASE b.carrier_type WHEN 'PLAYER_VESSEL' THEN 'A player vessel delivered ' WHEN 'NPC_VESSEL' THEN 'An NPC vessel delivered ' ELSE 'A freight transfer delivered ' END||NEW.quantity||' units of '||i.display_name||'. The delivery updated inventory and any applicable station recovery values in the same transaction.',b.carrier_type,b.carrier_id,'FREIGHT_LOT',NEW.lot_id,'delivery:'||NEW.lot_id,'OBSERVED',NEW.world_id||':tick:'||NEW.updated_tick,(SELECT policy_version FROM station_story_policy WHERE active=1),COALESCE(m.canonical_time,'tick:'||NEW.updated_tick) "
                        + "FROM station_delivery_baseline b JOIN item_catalogue i ON i.item_id=NEW.item_id LEFT JOIN world_simulation_metadata m ON m.world_id=NEW.world_id WHERE b.lot_id=NEW.lot_id; "

                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-inventory',NEW.lot_id||':delivery-event','inventory.'||i.item_key,'INTEGER',b.inventory_before,NEW.quantity,b.inventory_before+NEW.quantity,'units','FREIGHT_DELIVERY','ITEM',NEW.item_id FROM station_delivery_baseline b JOIN item_catalogue i ON i.item_id=NEW.item_id WHERE b.lot_id=NEW.lot_id; "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-credits',NEW.lot_id||':delivery-event','station.credits','INTEGER',b.credits_before,CASE b.carrier_type WHEN 'PLAYER_VESSEL' THEN -i.base_value*NEW.quantity WHEN 'NPC_VESSEL' THEN i.base_value*NEW.quantity+COALESCE((SELECT cargo*25 FROM npc_vessel WHERE npc_vessel_id=b.carrier_id),0) ELSE 0 END,b.credits_before+CASE b.carrier_type WHEN 'PLAYER_VESSEL' THEN -i.base_value*NEW.quantity WHEN 'NPC_VESSEL' THEN i.base_value*NEW.quantity+COALESCE((SELECT cargo*25 FROM npc_vessel WHERE npc_vessel_id=b.carrier_id),0) ELSE 0 END,'credits','TRADE_SETTLEMENT','STATION',NEW.destination_station_id FROM station_delivery_baseline b JOIN item_catalogue i ON i.item_id=NEW.item_id WHERE b.lot_id=NEW.lot_id AND b.carrier_type<>'UNASSIGNED'; "

                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-supplies',NEW.lot_id||':delivery-event','station.supplies','INTEGER',b.supplies_before,MIN(1000,b.supplies_before+CASE NEW.item_id WHEN 'item-rations' THEN NEW.quantity*2 WHEN 'item-medical' THEN NEW.quantity WHEN 'item-fuel' THEN NEW.quantity ELSE 0 END)-b.supplies_before,MIN(1000,b.supplies_before+CASE NEW.item_id WHEN 'item-rations' THEN NEW.quantity*2 WHEN 'item-medical' THEN NEW.quantity WHEN 'item-fuel' THEN NEW.quantity ELSE 0 END),'units','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id IN ('item-rations','item-medical','item-fuel'); "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-integrity',NEW.lot_id||':delivery-event','station.integrity','INTEGER',b.integrity_before,MIN(100,b.integrity_before+CASE NEW.item_id WHEN 'item-medical' THEN MAX(1,NEW.quantity/4) WHEN 'item-steel' THEN MAX(1,NEW.quantity/5) ELSE 0 END)-b.integrity_before,MIN(100,b.integrity_before+CASE NEW.item_id WHEN 'item-medical' THEN MAX(1,NEW.quantity/4) WHEN 'item-steel' THEN MAX(1,NEW.quantity/5) ELSE 0 END),'points','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id IN ('item-medical','item-steel'); "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-security',NEW.lot_id||':delivery-event','station.security','INTEGER',b.security_before,MIN(100,b.security_before+MAX(1,NEW.quantity/4))-b.security_before,MIN(100,b.security_before+MAX(1,NEW.quantity/4)),'points','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id='item-ammunition'; "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-industry',NEW.lot_id||':delivery-event','station.industry','INTEGER',b.industry_before,MIN(100,b.industry_before+CASE NEW.item_id WHEN 'item-fuel' THEN MAX(1,NEW.quantity/6) ELSE MAX(1,NEW.quantity/8) END)-b.industry_before,MIN(100,b.industry_before+CASE NEW.item_id WHEN 'item-fuel' THEN MAX(1,NEW.quantity/6) ELSE MAX(1,NEW.quantity/8) END),'points','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id IN ('item-fuel','item-steel'); "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-shortage',NEW.lot_id||':delivery-event','civilization.shortage_ticks','INTEGER',b.shortage_ticks_before,MAX(0,b.shortage_ticks_before-NEW.quantity)-b.shortage_ticks_before,MAX(0,b.shortage_ticks_before-NEW.quantity),'ticks','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id='item-rations'; "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-surplus',NEW.lot_id||':delivery-event','civilization.surplus_ticks','INTEGER',b.surplus_ticks_before,1,b.surplus_ticks_before+1,'ticks','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id IN ('item-rations','item-medical','item-fuel','item-ammunition','item-steel'); "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-civilization',NEW.lot_id||':delivery-event','civilization.strength','INTEGER',b.civilization_before,MIN(100,b.civilization_before+CASE NEW.item_id WHEN 'item-rations' THEN MAX(1,NEW.quantity/5) WHEN 'item-medical' THEN MAX(1,NEW.quantity/6) WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/8) ELSE MAX(1,NEW.quantity/10) END)-b.civilization_before,MIN(100,b.civilization_before+CASE NEW.item_id WHEN 'item-rations' THEN MAX(1,NEW.quantity/5) WHEN 'item-medical' THEN MAX(1,NEW.quantity/6) WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/8) ELSE MAX(1,NEW.quantity/10) END),'points','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id IN ('item-rations','item-medical','item-ammunition','item-steel'); "
                        + "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.lot_id||':delivery-fauna',NEW.lot_id||':delivery-event','civilization.fauna_pressure','INTEGER',b.fauna_before,-MIN(b.fauna_before,CASE NEW.item_id WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/6) ELSE 1 END),MAX(0,b.fauna_before-CASE NEW.item_id WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/6) ELSE 1 END),'points','RELIEF_DELIVERY','STATION',NEW.destination_station_id FROM station_delivery_baseline b WHERE b.lot_id=NEW.lot_id AND NEW.item_id IN ('item-ammunition','item-medical'); "
                        + "DELETE FROM station_delivery_baseline WHERE lot_id=NEW.lot_id; END",

                "CREATE VIEW station_delivery_story AS SELECT f.lot_id,f.world_id,f.destination_station_id station_id,f.item_id,f.quantity,f.delivered_tick,f.assigned_npc_vessel_id,f.assigned_player_vessel_id,e.event_id,e.severity,e.headline,e.narrative,e.actor_type,e.actor_id,e.correlation_id FROM freight_lot f JOIN station_event e ON e.cause_type='FREIGHT_LOT' AND e.cause_id=f.lot_id WHERE f.status='DELIVERED'"
        );
    }
}
