package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 021: measured attack, recovery, and frontier-transition causality. */
public final class StationFrontierCausalitySchema {
    private StationFrontierCausalitySchema() { }

    public static List<String> statements() {
        return List.of(
                "INSERT OR IGNORE INTO station_change_reason(reason_code,display_name,reason_family) VALUES "
                        + "('FRONTIER_ADVANCE','Frontier advance','RECOVERY'),"
                        + "('FRONTIER_RETREAT','Frontier retreat','SECURITY'),"
                        + "('FRONTIER_RECOVERY','Frontier recovery','RECOVERY')",

                "CREATE TABLE station_frontier_tick_baseline (station_id TEXT NOT NULL,world_id TEXT NOT NULL,tick_sequence INTEGER NOT NULL,integrity_before INTEGER NOT NULL,security_before INTEGER NOT NULL,industry_before INTEGER NOT NULL,threat_before INTEGER NOT NULL,station_status_before TEXT NOT NULL,population_before INTEGER NOT NULL,civilization_before INTEGER NOT NULL,fauna_before INTEGER NOT NULL,frontier_before INTEGER NOT NULL,frontier_state_before TEXT NOT NULL,PRIMARY KEY(station_id,tick_sequence),FOREIGN KEY(station_id) REFERENCES world_station(station_id),FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))",
                "CREATE TABLE station_frontier_transition (event_id TEXT PRIMARY KEY,frontier_state_before TEXT NOT NULL,frontier_state_after TEXT NOT NULL,station_status_before TEXT NOT NULL,station_status_after TEXT NOT NULL,attack_detected INTEGER NOT NULL DEFAULT 0 CHECK(attack_detected IN (0,1)),FOREIGN KEY(event_id) REFERENCES station_event(event_id) ON DELETE CASCADE)",

                "CREATE TRIGGER station_frontier_capture_before_tick BEFORE UPDATE OF last_tick ON station_simulation_state WHEN NEW.last_tick>OLD.last_tick AND EXISTS (SELECT 1 FROM station_civilization_state WHERE station_id=NEW.station_id) BEGIN "
                        + "INSERT OR REPLACE INTO station_frontier_tick_baseline(station_id,world_id,tick_sequence,integrity_before,security_before,industry_before,threat_before,station_status_before,population_before,civilization_before,fauna_before,frontier_before,frontier_state_before) "
                        + "SELECT NEW.station_id,NEW.world_id,NEW.last_tick,NEW.integrity,NEW.security,NEW.industry,NEW.threat,NEW.status,c.population_index,c.civilization_strength,c.fauna_pressure,c.frontier_position,c.frontier_state FROM station_civilization_state c WHERE c.station_id=NEW.station_id; END",

                "CREATE TRIGGER station_frontier_finalize_tick AFTER UPDATE OF status ON station_simulation_state WHEN NEW.last_tick=OLD.last_tick AND EXISTS (SELECT 1 FROM station_frontier_tick_baseline b WHERE b.station_id=NEW.station_id AND b.tick_sequence=NEW.last_tick) BEGIN "
                        + "INSERT OR IGNORE INTO station_event(event_id,world_id,station_id,tick_sequence,canonical_time,event_type,severity,headline,narrative,actor_type,actor_id,cause_type,cause_id,deterministic_key,visibility,correlation_id,policy_version,created_at) "
                        + "SELECT NEW.station_id||':frontier-causal:'||NEW.last_tick,NEW.world_id,NEW.station_id,NEW.last_tick,NULL,CASE WHEN NEW.threat>b.threat_before THEN 'ATTACK' WHEN b.frontier_state_before IN ('CONTESTED','CONTRACTING') AND c.frontier_state IN ('HOLDING','EXPANDING') THEN 'RECOVERY' ELSE 'FRONTIER_CHANGE' END,"
                        + "CASE WHEN NEW.threat>b.threat_before THEN MIN(5,2+(NEW.threat-b.threat_before)/2) WHEN c.frontier_state='ABANDONED' THEN 5 WHEN c.frontier_state<>b.frontier_state_before THEN 3 ELSE 1 END,"
                        + "CASE WHEN NEW.threat>b.threat_before THEN 'Europan fauna attacked the station perimeter' WHEN b.frontier_state_before IN ('CONTESTED','CONTRACTING') AND c.frontier_state IN ('HOLDING','EXPANDING') THEN 'The civilian perimeter recovered' WHEN c.frontier_state='ABANDONED' THEN 'The civilian frontier was abandoned' WHEN c.frontier_state='EXPANDING' THEN 'The civilian frontier advanced' ELSE 'The civilian frontier contracted' END,"
                        + "CASE WHEN NEW.threat>b.threat_before THEN 'Fauna pressure caused measured station damage and forced a frontier response.' WHEN b.frontier_state_before<>c.frontier_state THEN 'Measured station conditions changed the frontier from '||b.frontier_state_before||' to '||c.frontier_state||'.' ELSE 'The civilian frontier moved from '||b.frontier_before||' to '||c.frontier_position||' under sustained local conditions.' END,"
                        + "CASE WHEN NEW.threat>b.threat_before THEN 'FAUNA' ELSE 'SYSTEM' END,CASE WHEN NEW.threat>b.threat_before THEN 'europan-fauna-pressure' ELSE 'civilization-frontier' END,'FRONTIER_TICK',NEW.station_id||':'||NEW.last_tick,'frontier-tick:'||NEW.last_tick,'OBSERVED',NEW.world_id||':tick:'||NEW.last_tick,(SELECT policy_version FROM station_story_policy WHERE active=1),'tick:'||NEW.last_tick "
                        + "FROM station_frontier_tick_baseline b JOIN station_civilization_state c ON c.station_id=b.station_id WHERE b.station_id=NEW.station_id AND b.tick_sequence=NEW.last_tick AND (NEW.threat<>b.threat_before OR c.frontier_state<>b.frontier_state_before OR c.frontier_position<>b.frontier_before); "
                        + "INSERT OR IGNORE INTO station_frontier_transition(event_id,frontier_state_before,frontier_state_after,station_status_before,station_status_after,attack_detected) SELECT NEW.station_id||':frontier-causal:'||NEW.last_tick,b.frontier_state_before,c.frontier_state,b.station_status_before,NEW.status,CASE WHEN NEW.threat>b.threat_before THEN 1 ELSE 0 END FROM station_frontier_tick_baseline b JOIN station_civilization_state c ON c.station_id=b.station_id WHERE b.station_id=NEW.station_id AND b.tick_sequence=NEW.last_tick AND EXISTS (SELECT 1 FROM station_event WHERE event_id=NEW.station_id||':frontier-causal:'||NEW.last_tick); "

                        + measuredChange("integrity", "station.integrity", "NEW.integrity", "b.integrity_before", "points", "CASE WHEN NEW.threat>b.threat_before THEN 'ATTACK_DAMAGE' ELSE 'FRONTIER_RECOVERY' END")
                        + measuredChange("security", "station.security", "NEW.security", "b.security_before", "points", "CASE WHEN NEW.threat>b.threat_before THEN 'ATTACK_DAMAGE' ELSE 'FRONTIER_RECOVERY' END")
                        + measuredChange("industry", "station.industry", "NEW.industry", "b.industry_before", "points", "CASE WHEN NEW.industry>b.industry_before THEN 'FRONTIER_RECOVERY' ELSE 'FRONTIER_RETREAT' END")
                        + measuredChange("threat", "station.threat", "NEW.threat", "b.threat_before", "points", "CASE WHEN NEW.threat>b.threat_before THEN 'ATTACK_DAMAGE' ELSE 'FRONTIER_RECOVERY' END")
                        + measuredCivilizationChange("population", "civilization.population_index", "c.population_index", "b.population_before", "points", "CASE WHEN c.population_index>b.population_before THEN 'FRONTIER_RECOVERY' ELSE 'FRONTIER_RETREAT' END")
                        + measuredCivilizationChange("civilization", "civilization.strength", "c.civilization_strength", "b.civilization_before", "points", "CASE WHEN c.civilization_strength>b.civilization_before THEN 'FRONTIER_RECOVERY' WHEN NEW.threat>b.threat_before THEN 'ATTACK_DAMAGE' ELSE 'FRONTIER_RETREAT' END")
                        + measuredCivilizationChange("fauna", "civilization.fauna_pressure", "c.fauna_pressure", "b.fauna_before", "points", "'FAUNA_PRESSURE'")
                        + measuredCivilizationChange("frontier", "civilization.frontier_position", "c.frontier_position", "b.frontier_before", "points", "CASE WHEN c.frontier_position>b.frontier_before THEN 'FRONTIER_ADVANCE' ELSE 'FRONTIER_RETREAT' END")
                        + "DELETE FROM station_frontier_tick_baseline WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick; END",

                "CREATE TRIGGER station_frontier_direct_transition AFTER UPDATE OF frontier_state ON station_civilization_state WHEN OLD.frontier_state<>NEW.frontier_state AND NOT EXISTS (SELECT 1 FROM station_frontier_tick_baseline b WHERE b.station_id=NEW.station_id AND b.tick_sequence=NEW.last_tick) BEGIN "
                        + "INSERT OR IGNORE INTO station_event(event_id,world_id,station_id,tick_sequence,canonical_time,event_type,severity,headline,narrative,actor_type,actor_id,cause_type,cause_id,deterministic_key,visibility,correlation_id,policy_version,created_at) VALUES (NEW.station_id||':frontier-transition:'||NEW.last_tick||':'||OLD.frontier_state||':'||NEW.frontier_state,NEW.world_id,NEW.station_id,NEW.last_tick,NULL,CASE WHEN OLD.frontier_state IN ('CONTESTED','CONTRACTING') AND NEW.frontier_state IN ('HOLDING','EXPANDING') THEN 'RECOVERY' ELSE 'FRONTIER_CHANGE' END,CASE WHEN NEW.frontier_state='ABANDONED' THEN 5 ELSE 2 END,CASE WHEN OLD.frontier_state IN ('CONTESTED','CONTRACTING') AND NEW.frontier_state IN ('HOLDING','EXPANDING') THEN 'The civilian perimeter recovered' WHEN NEW.frontier_state='ABANDONED' THEN 'The civilian frontier was abandoned' WHEN NEW.frontier_state='EXPANDING' THEN 'The civilian frontier advanced' ELSE 'The civilian frontier contracted' END,'The civilian frontier changed from '||OLD.frontier_state||' to '||NEW.frontier_state||' after an explicit station-state intervention.','SYSTEM','civilization-frontier','FRONTIER_TRANSITION',NEW.station_id||':'||NEW.last_tick||':'||OLD.frontier_state||':'||NEW.frontier_state,'frontier-transition:'||NEW.last_tick||':'||OLD.frontier_state||':'||NEW.frontier_state,'OBSERVED',NEW.world_id||':tick:'||NEW.last_tick,(SELECT policy_version FROM station_story_policy WHERE active=1),'tick:'||NEW.last_tick); "
                        + "INSERT OR IGNORE INTO station_frontier_transition(event_id,frontier_state_before,frontier_state_after,station_status_before,station_status_after,attack_detected) SELECT NEW.station_id||':frontier-transition:'||NEW.last_tick||':'||OLD.frontier_state||':'||NEW.frontier_state,OLD.frontier_state,NEW.frontier_state,s.status,s.status,0 FROM station_simulation_state s WHERE s.station_id=NEW.station_id; "
                        + directChange("population", "civilization.population_index", "NEW.population_index", "OLD.population_index", "CASE WHEN NEW.population_index>OLD.population_index THEN 'FRONTIER_RECOVERY' ELSE 'FRONTIER_RETREAT' END")
                        + directChange("civilization", "civilization.strength", "NEW.civilization_strength", "OLD.civilization_strength", "CASE WHEN NEW.civilization_strength>OLD.civilization_strength THEN 'FRONTIER_RECOVERY' ELSE 'FRONTIER_RETREAT' END")
                        + directChange("fauna", "civilization.fauna_pressure", "NEW.fauna_pressure", "OLD.fauna_pressure", "'FAUNA_PRESSURE'")
                        + directChange("frontier", "civilization.frontier_position", "NEW.frontier_position", "OLD.frontier_position", "CASE WHEN NEW.frontier_position>OLD.frontier_position THEN 'FRONTIER_ADVANCE' ELSE 'FRONTIER_RETREAT' END")
                        + "END",

                "CREATE VIEW station_frontier_story AS SELECT e.event_id,e.world_id,e.station_id,e.tick_sequence,e.event_type,e.severity,e.headline,e.narrative,e.actor_type,e.actor_id,e.cause_type,e.cause_id,e.correlation_id,t.frontier_state_before,t.frontier_state_after,t.station_status_before,t.station_status_after,t.attack_detected FROM station_event e JOIN station_frontier_transition t ON t.event_id=e.event_id WHERE e.cause_type IN ('FRONTIER_TICK','FRONTIER_TRANSITION')"
        );
    }

    private static String measuredChange(String suffix, String key, String after, String before,
                                         String unit, String reason) {
        return "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.station_id||':frontier-causal:'||NEW.last_tick||':" + suffix + "',NEW.station_id||':frontier-causal:'||NEW.last_tick,'" + key + "','INTEGER'," + before + "," + after + "-(" + before + ")," + after + ",'" + unit + "'," + reason + ",'STATION',NEW.station_id FROM station_frontier_tick_baseline b WHERE b.station_id=NEW.station_id AND b.tick_sequence=NEW.last_tick AND " + after + "<>(" + before + ") AND EXISTS (SELECT 1 FROM station_event WHERE event_id=NEW.station_id||':frontier-causal:'||NEW.last_tick); ";
    }

    private static String measuredCivilizationChange(String suffix, String key, String after, String before,
                                                      String unit, String reason) {
        return "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.station_id||':frontier-causal:'||NEW.last_tick||':" + suffix + "',NEW.station_id||':frontier-causal:'||NEW.last_tick,'" + key + "','INTEGER'," + before + "," + after + "-(" + before + ")," + after + ",'" + unit + "'," + reason + ",'STATION',NEW.station_id FROM station_frontier_tick_baseline b JOIN station_civilization_state c ON c.station_id=b.station_id WHERE b.station_id=NEW.station_id AND b.tick_sequence=NEW.last_tick AND " + after + "<>(" + before + ") AND EXISTS (SELECT 1 FROM station_event WHERE event_id=NEW.station_id||':frontier-causal:'||NEW.last_tick); ";
    }

    private static String directChange(String suffix, String key, String after, String before, String reason) {
        return "INSERT OR IGNORE INTO station_change(change_id,event_id,statistic_key,value_type,previous_value,delta_value,resulting_value,unit,reason_code,affected_type,affected_id) SELECT NEW.station_id||':frontier-transition:'||NEW.last_tick||':'||OLD.frontier_state||':'||NEW.frontier_state||':" + suffix + "',NEW.station_id||':frontier-transition:'||NEW.last_tick||':'||OLD.frontier_state||':'||NEW.frontier_state,'" + key + "','INTEGER'," + before + "," + after + "-(" + before + ")," + after + ",'points'," + reason + ",'STATION',NEW.station_id WHERE " + after + "<>(" + before + "); ";
    }
}
