package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;

/** Schema 006: item-level station logistics and player-vessel route operations. */
public final class StationLogisticsSchema {
    private StationLogisticsSchema() { }

    public static List<String> statements() {
        return List.of(
                "CREATE TABLE item_catalogue (item_id TEXT PRIMARY KEY, item_key TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, category TEXT NOT NULL CHECK(category IN ('RAW','INDUSTRIAL','FUEL','MEDICAL','SUPPLY','MUNITIONS','RESEARCH','LUXURY')), base_value INTEGER NOT NULL CHECK(base_value >= 0), unit_mass REAL NOT NULL CHECK(unit_mass >= 0))",
                "CREATE TABLE production_recipe (recipe_id TEXT PRIMARY KEY, recipe_key TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, cycle_ticks INTEGER NOT NULL DEFAULT 1 CHECK(cycle_ticks > 0), credit_cost INTEGER NOT NULL DEFAULT 0 CHECK(credit_cost >= 0))",
                "CREATE TABLE production_recipe_input (recipe_id TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity > 0), PRIMARY KEY(recipe_id,item_id), FOREIGN KEY(recipe_id) REFERENCES production_recipe(recipe_id), FOREIGN KEY(item_id) REFERENCES item_catalogue(item_id))",
                "CREATE TABLE production_recipe_output (recipe_id TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity > 0), PRIMARY KEY(recipe_id,item_id), FOREIGN KEY(recipe_id) REFERENCES production_recipe(recipe_id), FOREIGN KEY(item_id) REFERENCES item_catalogue(item_id))",
                "CREATE TABLE station_inventory (station_id TEXT NOT NULL, item_id TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 0 CHECK(quantity >= 0), reserved INTEGER NOT NULL DEFAULT 0 CHECK(reserved >= 0 AND reserved <= quantity), reorder_point INTEGER NOT NULL DEFAULT 0 CHECK(reorder_point >= 0), last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), PRIMARY KEY(station_id,item_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id), FOREIGN KEY(item_id) REFERENCES item_catalogue(item_id))",
                "CREATE INDEX station_inventory_shortage_index ON station_inventory(station_id,quantity,reorder_point)",
                "CREATE TABLE station_vendor_offer (offer_id TEXT PRIMARY KEY, station_id TEXT NOT NULL, item_id TEXT NOT NULL, buy_price INTEGER NOT NULL CHECK(buy_price >= 0), sell_price INTEGER NOT NULL CHECK(sell_price >= buy_price), stock_limit INTEGER NOT NULL DEFAULT 0 CHECK(stock_limit >= 0), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), UNIQUE(station_id,item_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id), FOREIGN KEY(item_id) REFERENCES item_catalogue(item_id))",
                "CREATE TABLE station_production_run (run_id TEXT PRIMARY KEY, station_id TEXT NOT NULL, recipe_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), cycles INTEGER NOT NULL DEFAULT 1 CHECK(cycles > 0), status TEXT NOT NULL DEFAULT 'COMPLETE' CHECK(status IN ('PLANNED','COMPLETE','FAILED')), UNIQUE(station_id,recipe_id,tick_sequence), FOREIGN KEY(station_id) REFERENCES world_station(station_id), FOREIGN KEY(recipe_id) REFERENCES production_recipe(recipe_id))",
                "CREATE TABLE freight_lot (lot_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, mission_id TEXT UNIQUE, source_station_id TEXT, destination_station_id TEXT, item_id TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity > 0), status TEXT NOT NULL CHECK(status IN ('READY','LOADED','IN_TRANSIT','DELIVERED','LOST','CANCELLED')), assigned_npc_vessel_id TEXT, assigned_player_vessel_id TEXT, created_tick INTEGER NOT NULL CHECK(created_tick >= 0), updated_tick INTEGER NOT NULL CHECK(updated_tick >= 0), delivered_tick INTEGER CHECK(delivered_tick >= 0), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(mission_id) REFERENCES world_mission(mission_id), FOREIGN KEY(source_station_id) REFERENCES world_station(station_id), FOREIGN KEY(destination_station_id) REFERENCES world_station(station_id), FOREIGN KEY(item_id) REFERENCES item_catalogue(item_id), FOREIGN KEY(assigned_npc_vessel_id) REFERENCES npc_vessel(npc_vessel_id), FOREIGN KEY(assigned_player_vessel_id) REFERENCES vessel_instance(vessel_id))",
                "CREATE INDEX freight_lot_status_index ON freight_lot(world_id,status,updated_tick)",
                "CREATE TABLE treasury_transaction (transaction_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, station_id TEXT, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), category TEXT NOT NULL CHECK(category IN ('PRODUCTION','TRADE','MINING','FREIGHT','MISSION','REPAIR','RESEARCH','MARKET','ADJUSTMENT')), credits_delta INTEGER NOT NULL, counterparty_type TEXT, counterparty_id TEXT, memo TEXT NOT NULL, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id))",
                "CREATE INDEX treasury_transaction_tick_index ON treasury_transaction(world_id,tick_sequence DESC)",
                "CREATE TABLE player_vessel_state (vessel_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, current_location_id TEXT NOT NULL, destination_location_id TEXT, status TEXT NOT NULL CHECK(status IN ('DOCKED','IN_TRANSIT','ARRIVED','DISABLED','LOST')), hull INTEGER NOT NULL DEFAULT 100 CHECK(hull BETWEEN 0 AND 100), supplies INTEGER NOT NULL DEFAULT 100 CHECK(supplies >= 0), cargo INTEGER NOT NULL DEFAULT 0 CHECK(cargo >= 0), crew_quality INTEGER NOT NULL DEFAULT 50 CHECK(crew_quality BETWEEN 1 AND 100), navigation INTEGER NOT NULL DEFAULT 50 CHECK(navigation BETWEEN 1 AND 100), engineering INTEGER NOT NULL DEFAULT 50 CHECK(engineering BETWEEN 1 AND 100), combat INTEGER NOT NULL DEFAULT 50 CHECK(combat BETWEEN 1 AND 100), route_progress INTEGER NOT NULL DEFAULT 0 CHECK(route_progress >= 0), route_ticks_required INTEGER NOT NULL DEFAULT 1 CHECK(route_ticks_required >= 1), route_action_sequence INTEGER NOT NULL DEFAULT 0 CHECK(route_action_sequence >= 0), mission_type TEXT NOT NULL DEFAULT 'TRANSIT' CHECK(mission_type IN ('TRADE','MINING','FAUNA_CLEARING','DEFENSE','RESEARCH','SALVAGE','TRANSIT')), last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), FOREIGN KEY(vessel_id) REFERENCES vessel_instance(vessel_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(current_location_id) REFERENCES world_location(location_id), FOREIGN KEY(destination_location_id) REFERENCES world_location(location_id))",
                "CREATE INDEX player_vessel_status_index ON player_vessel_state(world_id,status,last_tick)",
                "CREATE TABLE player_voyage_log (log_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, vessel_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), action_sequence INTEGER NOT NULL CHECK(action_sequence >= 0), canonical_time TEXT NOT NULL, event_type TEXT NOT NULL, severity INTEGER NOT NULL CHECK(severity BETWEEN 0 AND 100), summary TEXT NOT NULL, details TEXT NOT NULL, resolution TEXT NOT NULL, hull_delta INTEGER NOT NULL DEFAULT 0, supplies_delta INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(vessel_id) REFERENCES vessel_instance(vessel_id))",
                "CREATE INDEX player_voyage_log_index ON player_voyage_log(vessel_id,tick_sequence DESC,action_sequence DESC)",
                "CREATE TABLE player_transit_encounter (encounter_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, vessel_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), action_sequence INTEGER NOT NULL CHECK(action_sequence > 0), canonical_time TEXT NOT NULL, route_id TEXT NOT NULL, hazard_type TEXT NOT NULL, challenge INTEGER NOT NULL CHECK(challenge BETWEEN 1 AND 100), resolution_roll INTEGER NOT NULL CHECK(resolution_roll BETWEEN 1 AND 100), effective_capability INTEGER NOT NULL CHECK(effective_capability >= 1), margin INTEGER NOT NULL, outcome TEXT NOT NULL CHECK(outcome IN ('TRIUMPH','SUCCESS','COSTLY_SUCCESS','SETBACK','DISASTER')), narrative TEXT NOT NULL, UNIQUE(vessel_id,tick_sequence,action_sequence), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(vessel_id) REFERENCES vessel_instance(vessel_id))",

                "INSERT INTO item_catalogue(item_id,item_key,display_name,category,base_value,unit_mass) VALUES "
                        + "('item-ore','ore','Raw Europan Ore','RAW',90,8.0),"
                        + "('item-steel','steel','Fabricated Steel','INDUSTRIAL',240,6.0),"
                        + "('item-fuel','fuel-rod','Reactor Fuel Rod','FUEL',850,4.0),"
                        + "('item-medical','medical-supplies','Medical Supplies','MEDICAL',320,1.0),"
                        + "('item-rations','rations','Crew Rations','SUPPLY',120,1.0),"
                        + "('item-ammunition','coilgun-ammunition','Coilgun Ammunition','MUNITIONS',280,2.0),"
                        + "('item-research','research-samples','Research Samples','RESEARCH',500,1.0),"
                        + "('item-luxury','luxury-goods','Luxury Goods','LUXURY',650,1.0)",
                "INSERT INTO production_recipe(recipe_id,recipe_key,display_name,cycle_ticks,credit_cost) VALUES "
                        + "('recipe-steel','smelt-steel','Smelt Steel',1,120),"
                        + "('recipe-fuel','assemble-fuel-rod','Assemble Fuel Rod',2,350),"
                        + "('recipe-medical','prepare-medical','Prepare Medical Supplies',1,180),"
                        + "('recipe-ammunition','fabricate-ammunition','Fabricate Coilgun Ammunition',1,160)",
                "INSERT INTO production_recipe_input(recipe_id,item_id,quantity) VALUES "
                        + "('recipe-steel','item-ore',3),"
                        + "('recipe-fuel','item-ore',2),('recipe-fuel','item-steel',1),"
                        + "('recipe-medical','item-rations',1),('recipe-medical','item-research',1),"
                        + "('recipe-ammunition','item-steel',1),('recipe-ammunition','item-ore',1)",
                "INSERT INTO production_recipe_output(recipe_id,item_id,quantity) VALUES "
                        + "('recipe-steel','item-steel',2),"
                        + "('recipe-fuel','item-fuel',1),"
                        + "('recipe-medical','item-medical',2),"
                        + "('recipe-ammunition','item-ammunition',3)",

                "INSERT OR IGNORE INTO station_inventory(station_id,item_id,quantity,reserved,reorder_point,last_tick) "
                        + "SELECT s.station_id,i.item_id,CASE i.item_key WHEN 'ore' THEN s.ore WHEN 'rations' THEN s.supplies WHEN 'research-samples' THEN s.research ELSE 0 END,0,CASE i.category WHEN 'FUEL' THEN 8 WHEN 'MEDICAL' THEN 12 WHEN 'SUPPLY' THEN 30 WHEN 'MUNITIONS' THEN 15 ELSE 5 END,s.last_tick FROM station_simulation_state s CROSS JOIN item_catalogue i",
                "INSERT OR IGNORE INTO station_vendor_offer(offer_id,station_id,item_id,buy_price,sell_price,stock_limit,active,last_tick) "
                        + "SELECT s.station_id||':'||i.item_id,s.station_id,i.item_id,MAX(1,i.base_value*70/100),MAX(1,i.base_value*120/100),CASE i.category WHEN 'SUPPLY' THEN 120 WHEN 'RAW' THEN 200 ELSE 60 END,CASE WHEN s.status='FALLEN' THEN 0 ELSE 1 END,s.last_tick FROM station_simulation_state s CROSS JOIN item_catalogue i",

                "CREATE TRIGGER station_logistics_seed AFTER INSERT ON station_simulation_state BEGIN "
                        + "INSERT OR IGNORE INTO station_inventory(station_id,item_id,quantity,reserved,reorder_point,last_tick) "
                        + "SELECT NEW.station_id,i.item_id,CASE i.item_key WHEN 'ore' THEN NEW.ore WHEN 'rations' THEN NEW.supplies WHEN 'research-samples' THEN NEW.research ELSE 0 END,0,CASE i.category WHEN 'FUEL' THEN 8 WHEN 'MEDICAL' THEN 12 WHEN 'SUPPLY' THEN 30 WHEN 'MUNITIONS' THEN 15 ELSE 5 END,NEW.last_tick FROM item_catalogue i; "
                        + "INSERT OR IGNORE INTO station_vendor_offer(offer_id,station_id,item_id,buy_price,sell_price,stock_limit,active,last_tick) "
                        + "SELECT NEW.station_id||':'||i.item_id,NEW.station_id,i.item_id,MAX(1,i.base_value*70/100),MAX(1,i.base_value*120/100),CASE i.category WHEN 'SUPPLY' THEN 120 WHEN 'RAW' THEN 200 ELSE 60 END,1,NEW.last_tick FROM item_catalogue i; END",

                "CREATE TRIGGER passive_station_logistics_cycle AFTER UPDATE OF last_cycle_tick ON passive_simulation_config "
                        + "WHEN NEW.last_cycle_tick IS NOT NULL AND (OLD.last_cycle_tick IS NULL OR NEW.last_cycle_tick>OLD.last_cycle_tick) BEGIN "
                        + "INSERT OR IGNORE INTO station_inventory(station_id,item_id,quantity,reserved,reorder_point,last_tick) SELECT s.station_id,i.item_id,0,0,5,NEW.last_cycle_tick FROM station_simulation_state s CROSS JOIN item_catalogue i WHERE s.world_id=NEW.world_id; "
                        + "INSERT OR IGNORE INTO station_vendor_offer(offer_id,station_id,item_id,buy_price,sell_price,stock_limit,active,last_tick) SELECT s.station_id||':'||i.item_id,s.station_id,i.item_id,MAX(1,i.base_value*70/100),MAX(1,i.base_value*120/100),60,1,NEW.last_cycle_tick FROM station_simulation_state s CROSS JOIN item_catalogue i WHERE s.world_id=NEW.world_id; "
                        + "UPDATE station_inventory SET quantity=quantity+MAX(1,(SELECT industry FROM station_simulation_state s WHERE s.station_id=station_inventory.station_id)/20),last_tick=NEW.last_cycle_tick WHERE item_id='item-ore' AND station_id IN (SELECT station_id FROM station_simulation_state WHERE world_id=NEW.world_id AND status<>'FALLEN'); "
                        + "UPDATE station_inventory SET quantity=quantity+MAX(1,(SELECT supplies FROM station_simulation_state s WHERE s.station_id=station_inventory.station_id)/50),last_tick=NEW.last_cycle_tick WHERE item_id='item-rations' AND station_id IN (SELECT station_id FROM station_simulation_state WHERE world_id=NEW.world_id AND status<>'FALLEN'); "
                        + "INSERT OR IGNORE INTO station_production_run(run_id,station_id,recipe_id,tick_sequence,cycles,status) SELECT s.station_id||':'||r.recipe_id||':'||NEW.last_cycle_tick,s.station_id,r.recipe_id,NEW.last_cycle_tick,1,'COMPLETE' FROM station_simulation_state s CROSS JOIN production_recipe r WHERE s.world_id=NEW.world_id AND s.status<>'FALLEN' AND r.recipe_id=(SELECT r2.recipe_id FROM production_recipe r2 WHERE NEW.last_cycle_tick%r2.cycle_ticks=0 AND NOT EXISTS (SELECT 1 FROM production_recipe_input ri LEFT JOIN station_inventory inv ON inv.station_id=s.station_id AND inv.item_id=ri.item_id WHERE ri.recipe_id=r2.recipe_id AND COALESCE(inv.quantity-inv.reserved,0)<ri.quantity) ORDER BY r2.recipe_id LIMIT 1); "
                        + "UPDATE station_vendor_offer SET buy_price=MAX(1,(SELECT base_value FROM item_catalogue i WHERE i.item_id=station_vendor_offer.item_id)*(70+(SELECT threat FROM station_simulation_state s WHERE s.station_id=station_vendor_offer.station_id)/4)/100),sell_price=MAX(1,(SELECT base_value FROM item_catalogue i WHERE i.item_id=station_vendor_offer.item_id)*(115+(SELECT threat FROM station_simulation_state s WHERE s.station_id=station_vendor_offer.station_id)/3)/100),active=CASE WHEN (SELECT status FROM station_simulation_state s WHERE s.station_id=station_vendor_offer.station_id)='FALLEN' THEN 0 ELSE 1 END,last_tick=NEW.last_cycle_tick WHERE station_id IN (SELECT station_id FROM station_simulation_state WHERE world_id=NEW.world_id); END",

                "CREATE TRIGGER station_production_apply AFTER INSERT ON station_production_run WHEN NEW.status='COMPLETE' BEGIN "
                        + "UPDATE station_inventory SET quantity=quantity-(SELECT quantity*NEW.cycles FROM production_recipe_input ri WHERE ri.recipe_id=NEW.recipe_id AND ri.item_id=station_inventory.item_id),last_tick=NEW.tick_sequence WHERE station_id=NEW.station_id AND item_id IN (SELECT item_id FROM production_recipe_input WHERE recipe_id=NEW.recipe_id); "
                        + "UPDATE station_inventory SET quantity=quantity+(SELECT quantity*NEW.cycles FROM production_recipe_output ro WHERE ro.recipe_id=NEW.recipe_id AND ro.item_id=station_inventory.item_id),last_tick=NEW.tick_sequence WHERE station_id=NEW.station_id AND item_id IN (SELECT item_id FROM production_recipe_output WHERE recipe_id=NEW.recipe_id); "
                        + "UPDATE station_simulation_state SET credits=credits-(SELECT credit_cost*NEW.cycles FROM production_recipe WHERE recipe_id=NEW.recipe_id) WHERE station_id=NEW.station_id; "
                        + "INSERT OR IGNORE INTO treasury_transaction(transaction_id,world_id,station_id,tick_sequence,category,credits_delta,counterparty_type,counterparty_id,memo) SELECT NEW.run_id||':treasury',s.world_id,NEW.station_id,NEW.tick_sequence,'PRODUCTION',-r.credit_cost*NEW.cycles,'RECIPE',NEW.recipe_id,'Production run: '||r.display_name FROM station_simulation_state s JOIN production_recipe r ON r.recipe_id=NEW.recipe_id WHERE s.station_id=NEW.station_id; END",

                "CREATE TRIGGER freight_from_completed_mission AFTER UPDATE OF status ON world_mission WHEN NEW.status='COMPLETE' AND OLD.status<>'COMPLETE' AND NEW.mission_type IN ('TRADE','MINING','SALVAGE') BEGIN "
                        + "INSERT OR IGNORE INTO freight_lot(lot_id,world_id,mission_id,source_station_id,destination_station_id,item_id,quantity,status,assigned_npc_vessel_id,created_tick,updated_tick) SELECT NEW.mission_id||':freight',NEW.world_id,NEW.mission_id,NEW.origin_station_id,COALESCE((SELECT station_id FROM world_station WHERE location_id=NEW.target_location_id),NEW.origin_station_id),CASE NEW.mission_type WHEN 'MINING' THEN 'item-ore' WHEN 'SALVAGE' THEN 'item-steel' ELSE 'item-rations' END,MAX(1,NEW.cargo_units),'IN_TRANSIT',NEW.assigned_npc_vessel_id,NEW.created_tick,NEW.updated_tick; END",

                "CREATE TRIGGER freight_delivered_by_npc AFTER UPDATE OF status ON npc_vessel WHEN NEW.status='DOCKED' AND OLD.status IN ('RETURNING','WORKING') BEGIN "
                        + "UPDATE freight_lot SET status='DELIVERED',updated_tick=NEW.last_tick,delivered_tick=NEW.last_tick,destination_station_id=NEW.home_station_id WHERE assigned_npc_vessel_id=NEW.npc_vessel_id AND status IN ('READY','LOADED','IN_TRANSIT'); "
                        + "UPDATE station_inventory SET quantity=quantity+COALESCE((SELECT SUM(quantity) FROM freight_lot f WHERE f.assigned_npc_vessel_id=NEW.npc_vessel_id AND f.status='DELIVERED' AND f.delivered_tick=NEW.last_tick AND f.item_id=station_inventory.item_id),0),last_tick=NEW.last_tick WHERE station_id=NEW.home_station_id; "
                        + "UPDATE station_simulation_state SET credits=credits+COALESCE((SELECT SUM(i.base_value*f.quantity) FROM freight_lot f JOIN item_catalogue i ON i.item_id=f.item_id WHERE f.assigned_npc_vessel_id=NEW.npc_vessel_id AND f.status='DELIVERED' AND f.delivered_tick=NEW.last_tick),0) WHERE station_id=NEW.home_station_id; "
                        + "INSERT OR IGNORE INTO treasury_transaction(transaction_id,world_id,station_id,tick_sequence,category,credits_delta,counterparty_type,counterparty_id,memo) SELECT f.lot_id||':delivery',f.world_id,NEW.home_station_id,NEW.last_tick,'FREIGHT',i.base_value*f.quantity,'NPC_VESSEL',NEW.npc_vessel_id,'Delivered freight lot '||f.lot_id FROM freight_lot f JOIN item_catalogue i ON i.item_id=f.item_id WHERE f.assigned_npc_vessel_id=NEW.npc_vessel_id AND f.status='DELIVERED' AND f.delivered_tick=NEW.last_tick; END"
        );
    }
}
