package io.github.mrcalzon02.barotrauma.persistence;

import java.util.List;
import java.util.Objects;

/** Schema 008: variable station consumption and slow civilization expansion/contraction. */
public final class StationConsumptionAndFrontierSchema {
    private StationConsumptionAndFrontierSchema() { }

    public static List<String> statements() {
        return List.of(
                "CREATE TABLE station_civilization_state (station_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, population_index INTEGER NOT NULL DEFAULT 70 CHECK(population_index BETWEEN 0 AND 100), civilization_strength INTEGER NOT NULL DEFAULT 60 CHECK(civilization_strength BETWEEN 0 AND 100), fauna_pressure INTEGER NOT NULL DEFAULT 15 CHECK(fauna_pressure BETWEEN 0 AND 100), supply_consumption_base INTEGER NOT NULL DEFAULT 2 CHECK(supply_consumption_base BETWEEN 1 AND 10), last_consumption INTEGER NOT NULL DEFAULT 0 CHECK(last_consumption BETWEEN 0 AND 20), shortage_ticks INTEGER NOT NULL DEFAULT 0 CHECK(shortage_ticks >= 0), surplus_ticks INTEGER NOT NULL DEFAULT 0 CHECK(surplus_ticks >= 0), frontier_position INTEGER NOT NULL DEFAULT 50 CHECK(frontier_position BETWEEN 0 AND 100), frontier_state TEXT NOT NULL DEFAULT 'HOLDING' CHECK(frontier_state IN ('EXPANDING','HOLDING','CONTESTED','CONTRACTING','ABANDONED')), last_tick INTEGER NOT NULL DEFAULT 0 CHECK(last_tick >= 0), FOREIGN KEY(station_id) REFERENCES world_station(station_id), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id))",
                "CREATE INDEX station_civilization_frontier_index ON station_civilization_state(world_id,frontier_state,frontier_position,fauna_pressure DESC)",
                "CREATE TABLE station_consumption_log (consumption_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, station_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), required_units INTEGER NOT NULL CHECK(required_units > 0), ration_units_consumed INTEGER NOT NULL DEFAULT 0 CHECK(ration_units_consumed >= 0), abstract_supply_delta INTEGER NOT NULL, shortage INTEGER NOT NULL CHECK(shortage IN (0,1)), supplies_after INTEGER NOT NULL CHECK(supplies_after >= 0), ration_stock_after INTEGER NOT NULL CHECK(ration_stock_after >= 0), UNIQUE(station_id,tick_sequence), FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id))",
                "CREATE INDEX station_consumption_tick_index ON station_consumption_log(world_id,tick_sequence DESC,shortage DESC)",
                "CREATE TABLE civilization_frontier_event (event_id TEXT PRIMARY KEY, world_id TEXT NOT NULL, station_id TEXT NOT NULL, tick_sequence INTEGER NOT NULL CHECK(tick_sequence >= 0), event_type TEXT NOT NULL CHECK(event_type IN ('SHORTAGE','RECOVERY','MONSTER_ATTACK','EXPANSION','CONTRACTION','ABANDONMENT','DELIVERY')), severity INTEGER NOT NULL CHECK(severity BETWEEN 0 AND 100), supplies_delta INTEGER NOT NULL DEFAULT 0, integrity_delta INTEGER NOT NULL DEFAULT 0, security_delta INTEGER NOT NULL DEFAULT 0, civilization_delta INTEGER NOT NULL DEFAULT 0, fauna_delta INTEGER NOT NULL DEFAULT 0, frontier_delta INTEGER NOT NULL DEFAULT 0, summary TEXT NOT NULL, FOREIGN KEY(world_id) REFERENCES world_metadata(world_id), FOREIGN KEY(station_id) REFERENCES world_station(station_id))",
                "CREATE INDEX civilization_frontier_event_tick_index ON civilization_frontier_event(world_id,tick_sequence DESC,severity DESC)",

                "INSERT OR IGNORE INTO station_civilization_state(station_id,world_id,population_index,civilization_strength,fauna_pressure,supply_consumption_base,last_consumption,shortage_ticks,surplus_ticks,frontier_position,frontier_state,last_tick) SELECT s.station_id,s.world_id,MAX(20,MIN(100,55+s.industry/4+s.integrity/5-s.threat/5)),MAX(10,MIN(100,(s.industry+s.security+s.integrity)/3)),MAX(0,MIN(100,s.threat)),1+ABS(unicode(substr(s.station_id,1,1)))%3,0,0,0,MAX(10,MIN(90,50+(s.security-s.threat)/3)),CASE WHEN s.status='FALLEN' THEN 'ABANDONED' WHEN s.threat>=70 THEN 'CONTESTED' ELSE 'HOLDING' END,s.last_tick FROM station_simulation_state s",

                "CREATE TRIGGER station_civilization_seed AFTER INSERT ON station_simulation_state BEGIN "
                        + "INSERT OR IGNORE INTO station_civilization_state(station_id,world_id,population_index,civilization_strength,fauna_pressure,supply_consumption_base,last_consumption,shortage_ticks,surplus_ticks,frontier_position,frontier_state,last_tick) VALUES (NEW.station_id,NEW.world_id,MAX(20,MIN(100,55+NEW.industry/4+NEW.integrity/5-NEW.threat/5)),MAX(10,MIN(100,(NEW.industry+NEW.security+NEW.integrity)/3)),NEW.threat,1+ABS(unicode(substr(NEW.station_id,1,1)))%3,0,0,0,MAX(10,MIN(90,50+(NEW.security-NEW.threat)/3)),CASE WHEN NEW.status='FALLEN' THEN 'ABANDONED' WHEN NEW.threat>=70 THEN 'CONTESTED' ELSE 'HOLDING' END,NEW.last_tick); END",

                passiveConsumptionTrigger(""),

                "CREATE TRIGGER delivered_freight_supports_station AFTER UPDATE OF status ON freight_lot WHEN NEW.status='DELIVERED' AND OLD.status<>'DELIVERED' AND NEW.destination_station_id IS NOT NULL BEGIN "
                        + "UPDATE station_simulation_state SET supplies=MIN(1000,supplies+CASE NEW.item_id WHEN 'item-rations' THEN NEW.quantity*2 WHEN 'item-medical' THEN NEW.quantity WHEN 'item-fuel' THEN NEW.quantity ELSE 0 END),integrity=MIN(100,integrity+CASE NEW.item_id WHEN 'item-medical' THEN MAX(1,NEW.quantity/4) WHEN 'item-steel' THEN MAX(1,NEW.quantity/5) ELSE 0 END),security=MIN(100,security+CASE NEW.item_id WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/4) ELSE 0 END),industry=MIN(100,industry+CASE NEW.item_id WHEN 'item-fuel' THEN MAX(1,NEW.quantity/6) WHEN 'item-steel' THEN MAX(1,NEW.quantity/8) ELSE 0 END) WHERE station_id=NEW.destination_station_id; "
                        + "UPDATE station_civilization_state SET shortage_ticks=MAX(0,shortage_ticks-CASE NEW.item_id WHEN 'item-rations' THEN NEW.quantity ELSE 0 END),surplus_ticks=surplus_ticks+CASE WHEN NEW.item_id IN ('item-rations','item-medical','item-fuel','item-ammunition','item-steel') THEN 1 ELSE 0 END,civilization_strength=MIN(100,civilization_strength+CASE NEW.item_id WHEN 'item-rations' THEN MAX(1,NEW.quantity/5) WHEN 'item-medical' THEN MAX(1,NEW.quantity/6) WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/8) WHEN 'item-steel' THEN MAX(1,NEW.quantity/10) ELSE 0 END),fauna_pressure=MAX(0,fauna_pressure-CASE NEW.item_id WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/6) WHEN 'item-medical' THEN 1 ELSE 0 END) WHERE station_id=NEW.destination_station_id; "
                        + "INSERT OR IGNORE INTO civilization_frontier_event(event_id,world_id,station_id,tick_sequence,event_type,severity,supplies_delta,integrity_delta,security_delta,civilization_delta,fauna_delta,frontier_delta,summary) VALUES (NEW.lot_id||':civilization-delivery',NEW.world_id,NEW.destination_station_id,NEW.updated_tick,'DELIVERY',10,CASE NEW.item_id WHEN 'item-rations' THEN NEW.quantity*2 WHEN 'item-medical' THEN NEW.quantity WHEN 'item-fuel' THEN NEW.quantity ELSE 0 END,CASE NEW.item_id WHEN 'item-medical' THEN MAX(1,NEW.quantity/4) WHEN 'item-steel' THEN MAX(1,NEW.quantity/5) ELSE 0 END,CASE NEW.item_id WHEN 'item-ammunition' THEN MAX(1,NEW.quantity/4) ELSE 0 END,CASE WHEN NEW.item_id IN ('item-rations','item-medical','item-fuel','item-ammunition','item-steel') THEN MAX(1,NEW.quantity/8) ELSE 0 END,CASE NEW.item_id WHEN 'item-ammunition' THEN -MAX(1,NEW.quantity/6) WHEN 'item-medical' THEN -1 ELSE 0 END,0,'A supply delivery reinforced the station civilian perimeter.'); END",

                "CREATE TRIGGER frontier_response_mission AFTER UPDATE OF frontier_state ON station_civilization_state WHEN NEW.frontier_state IN ('CONTESTED','CONTRACTING') AND OLD.frontier_state<>NEW.frontier_state BEGIN "
                        + "INSERT OR IGNORE INTO world_mission(mission_id,world_id,mission_type,status,origin_station_id,target_location_id,deterministic_seed,difficulty,reward_credits,cargo_units,progress,created_tick,updated_tick) SELECT NEW.station_id||':frontier-defense:'||NEW.last_tick,NEW.world_id,CASE WHEN NEW.fauna_pressure>NEW.civilization_strength THEN 'FAUNA_CLEARING' ELSE 'DEFENSE' END,'AVAILABLE',NEW.station_id,(SELECT location_id FROM world_location WHERE world_id=NEW.world_id ORDER BY location_level DESC,ring ASC,source_ordinal LIMIT 1),NEW.last_tick,MIN(100,35+NEW.fauna_pressure/2),2000+NEW.fauna_pressure*100,0,0,NEW.last_tick,NEW.last_tick WHERE NOT EXISTS (SELECT 1 FROM world_mission WHERE world_id=NEW.world_id AND origin_station_id=NEW.station_id AND mission_type IN ('FAUNA_CLEARING','DEFENSE') AND status IN ('AVAILABLE','ASSIGNED','ACTIVE')); END"
        );
    }

    /** Returns the authoritative station passive trigger with an optional final transactional statement. */
    static String passiveConsumptionTrigger(String finalizationSql) {
        String finalization = Objects.requireNonNull(finalizationSql, "finalizationSql").trim();
        if (!finalization.isEmpty() && !finalization.endsWith(";")) finalization += ";";
        if (!finalization.isEmpty()) finalization += " ";
        return "CREATE TRIGGER station_passive_consumption AFTER UPDATE OF last_tick ON station_simulation_state WHEN NEW.last_tick>OLD.last_tick BEGIN "
                + "INSERT OR IGNORE INTO station_consumption_log(consumption_id,world_id,station_id,tick_sequence,required_units,ration_units_consumed,abstract_supply_delta,shortage,supplies_after,ration_stock_after) SELECT NEW.station_id||':consumption:'||NEW.last_tick,NEW.world_id,NEW.station_id,NEW.last_tick,MAX(1,c.supply_consumption_base+((ABS(NEW.last_tick+unicode(substr(NEW.station_id,2,1)))%3)-1)),MIN(COALESCE(inv.quantity,0),MAX(1,c.supply_consumption_base+((ABS(NEW.last_tick+unicode(substr(NEW.station_id,2,1)))%3)-1))),-(1+MAX(0,MAX(1,c.supply_consumption_base+((ABS(NEW.last_tick+unicode(substr(NEW.station_id,2,1)))%3)-1))-COALESCE(inv.quantity,0))),CASE WHEN COALESCE(inv.quantity,0)<MAX(1,c.supply_consumption_base+((ABS(NEW.last_tick+unicode(substr(NEW.station_id,2,1)))%3)-1)) OR NEW.supplies<30 THEN 1 ELSE 0 END,MAX(0,NEW.supplies-(1+MAX(0,MAX(1,c.supply_consumption_base+((ABS(NEW.last_tick+unicode(substr(NEW.station_id,2,1)))%3)-1))-COALESCE(inv.quantity,0)))),MAX(0,COALESCE(inv.quantity,0)-MIN(COALESCE(inv.quantity,0),MAX(1,c.supply_consumption_base+((ABS(NEW.last_tick+unicode(substr(NEW.station_id,2,1)))%3)-1)))) FROM station_civilization_state c LEFT JOIN station_inventory inv ON inv.station_id=NEW.station_id AND inv.item_id='item-rations' WHERE c.station_id=NEW.station_id; "
                + "UPDATE station_inventory SET quantity=MAX(0,quantity-(SELECT ration_units_consumed FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick)),last_tick=NEW.last_tick WHERE station_id=NEW.station_id AND item_id='item-rations'; "
                + "UPDATE station_simulation_state SET supplies=(SELECT supplies_after FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick),integrity=MAX(0,integrity-CASE WHEN (SELECT shortage FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick)=1 AND (SELECT shortage_ticks FROM station_civilization_state WHERE station_id=NEW.station_id)>=3 THEN 1 ELSE 0 END),industry=MAX(0,industry-CASE WHEN (SELECT shortage_ticks FROM station_civilization_state WHERE station_id=NEW.station_id)>=11 AND (NEW.last_tick%6)=0 THEN 1 ELSE 0 END),security=MAX(0,security-CASE WHEN (SELECT shortage_ticks FROM station_civilization_state WHERE station_id=NEW.station_id)>=7 AND (NEW.last_tick%5)=0 THEN 1 ELSE 0 END) WHERE station_id=NEW.station_id; "
                + "UPDATE station_civilization_state SET last_consumption=(SELECT required_units FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick),shortage_ticks=CASE WHEN (SELECT shortage FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick)=1 THEN shortage_ticks+1 ELSE MAX(0,shortage_ticks-1) END,surplus_ticks=CASE WHEN (SELECT shortage FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick)=0 AND (SELECT supplies FROM station_simulation_state WHERE station_id=NEW.station_id)>=55 THEN surplus_ticks+1 ELSE MAX(0,surplus_ticks-1) END,civilization_strength=MAX(0,MIN(100,civilization_strength+CASE WHEN (SELECT supplies FROM station_simulation_state WHERE station_id=NEW.station_id)>=65 AND (SELECT threat FROM station_simulation_state WHERE station_id=NEW.station_id)<40 THEN 1 WHEN (SELECT supplies FROM station_simulation_state WHERE station_id=NEW.station_id)<25 OR (SELECT integrity FROM station_simulation_state WHERE station_id=NEW.station_id)<45 OR (SELECT threat FROM station_simulation_state WHERE station_id=NEW.station_id)>75 THEN -1 ELSE 0 END)),fauna_pressure=MAX(0,MIN(100,fauna_pressure+CASE WHEN (SELECT threat FROM station_simulation_state WHERE station_id=NEW.station_id)>60 OR (SELECT supplies FROM station_simulation_state WHERE station_id=NEW.station_id)<25 THEN 1 WHEN (SELECT security FROM station_simulation_state WHERE station_id=NEW.station_id)>65 AND (SELECT threat FROM station_simulation_state WHERE station_id=NEW.station_id)<35 THEN -1 ELSE 0 END)),population_index=MAX(0,MIN(100,population_index+CASE WHEN shortage_ticks>=11 AND NEW.last_tick%6=0 THEN -1 WHEN surplus_ticks>=15 AND NEW.last_tick%8=0 THEN 1 ELSE 0 END)),frontier_position=MAX(0,MIN(100,frontier_position+CASE WHEN surplus_ticks>=5 AND civilization_strength>=fauna_pressure+15 AND NEW.last_tick%3=0 THEN 1 WHEN shortage_ticks>=3 OR fauna_pressure>=civilization_strength+10 THEN -1 ELSE 0 END)),last_tick=NEW.last_tick WHERE station_id=NEW.station_id; "
                + "UPDATE station_simulation_state SET integrity=MAX(0,integrity-CASE WHEN ((NEW.last_tick+unicode(substr(NEW.station_id,3,1)))%13)=0 AND (SELECT fauna_pressure FROM station_civilization_state WHERE station_id=NEW.station_id)>security THEN 1+ABS(NEW.last_tick)%3 ELSE 0 END),security=MAX(0,security-CASE WHEN ((NEW.last_tick+unicode(substr(NEW.station_id,3,1)))%13)=0 AND (SELECT fauna_pressure FROM station_civilization_state WHERE station_id=NEW.station_id)>security THEN 1 ELSE 0 END),threat=MIN(100,threat+CASE WHEN ((NEW.last_tick+unicode(substr(NEW.station_id,3,1)))%13)=0 AND (SELECT fauna_pressure FROM station_civilization_state WHERE station_id=NEW.station_id)>security THEN 3 ELSE 0 END) WHERE station_id=NEW.station_id; "
                + "UPDATE station_civilization_state SET fauna_pressure=MIN(100,fauna_pressure+CASE WHEN ((NEW.last_tick+unicode(substr(NEW.station_id,3,1)))%13)=0 AND fauna_pressure>(SELECT security FROM station_simulation_state WHERE station_id=NEW.station_id) THEN 4 ELSE 0 END),civilization_strength=MAX(0,civilization_strength-CASE WHEN ((NEW.last_tick+unicode(substr(NEW.station_id,3,1)))%13)=0 AND fauna_pressure>(SELECT security FROM station_simulation_state WHERE station_id=NEW.station_id) THEN 2 ELSE 0 END),frontier_position=MAX(0,frontier_position-CASE WHEN ((NEW.last_tick+unicode(substr(NEW.station_id,3,1)))%13)=0 AND fauna_pressure>(SELECT security FROM station_simulation_state WHERE station_id=NEW.station_id) THEN 2 ELSE 0 END) WHERE station_id=NEW.station_id; "
                + "UPDATE station_civilization_state SET frontier_state=CASE WHEN frontier_position<=0 OR population_index<=0 OR (SELECT integrity FROM station_simulation_state WHERE station_id=NEW.station_id)<=0 THEN 'ABANDONED' WHEN shortage_ticks>=8 OR fauna_pressure>=civilization_strength+15 OR frontier_position<30 THEN 'CONTRACTING' WHEN shortage_ticks>=3 OR fauna_pressure>=civilization_strength OR (SELECT threat FROM station_simulation_state WHERE station_id=NEW.station_id)>=60 THEN 'CONTESTED' WHEN surplus_ticks>=6 AND civilization_strength>=fauna_pressure+15 AND frontier_position<100 THEN 'EXPANDING' ELSE 'HOLDING' END WHERE station_id=NEW.station_id; "
                + "UPDATE station_simulation_state SET status=CASE WHEN integrity<=0 OR (SELECT frontier_state FROM station_civilization_state WHERE station_id=NEW.station_id)='ABANDONED' THEN 'FALLEN' WHEN threat>=80 OR integrity<35 OR (SELECT frontier_state FROM station_civilization_state WHERE station_id=NEW.station_id)='CONTRACTING' THEN 'BESIEGED' WHEN supplies<30 OR integrity<60 OR threat>=55 OR (SELECT frontier_state FROM station_civilization_state WHERE station_id=NEW.station_id)='CONTESTED' THEN 'STRAINED' WHEN supplies>=75 AND integrity>=85 AND threat<30 AND (SELECT frontier_state FROM station_civilization_state WHERE station_id=NEW.station_id)='EXPANDING' THEN 'RISING' ELSE 'STABLE' END WHERE station_id=NEW.station_id; "
                + "INSERT OR IGNORE INTO civilization_frontier_event(event_id,world_id,station_id,tick_sequence,event_type,severity,supplies_delta,integrity_delta,security_delta,civilization_delta,fauna_delta,frontier_delta,summary) SELECT NEW.station_id||':shortage:'||NEW.last_tick,NEW.world_id,NEW.station_id,NEW.last_tick,'SHORTAGE',MIN(100,20+c.shortage_ticks*4),(SELECT abstract_supply_delta FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick),CASE WHEN c.shortage_ticks>=4 THEN -1 ELSE 0 END,CASE WHEN c.shortage_ticks>=8 THEN -1 ELSE 0 END,-1,1,CASE WHEN c.frontier_state IN ('CONTRACTING','ABANDONED') THEN -1 ELSE 0 END,'Station consumption exceeded local supply and began eroding civilian capacity.' FROM station_civilization_state c WHERE c.station_id=NEW.station_id AND (SELECT shortage FROM station_consumption_log WHERE station_id=NEW.station_id AND tick_sequence=NEW.last_tick)=1 AND c.shortage_ticks IN (1,4,8,12,20); "
                + "INSERT OR IGNORE INTO civilization_frontier_event(event_id,world_id,station_id,tick_sequence,event_type,severity,integrity_delta,security_delta,civilization_delta,fauna_delta,frontier_delta,summary) SELECT NEW.station_id||':attack:'||NEW.last_tick,NEW.world_id,NEW.station_id,NEW.last_tick,'MONSTER_ATTACK',MIN(100,40+c.fauna_pressure/2),-(1+ABS(NEW.last_tick)%3),-1,-2,4,-2,'Europan fauna struck the station perimeter and forced civilization inward.' FROM station_civilization_state c WHERE c.station_id=NEW.station_id AND ((NEW.last_tick+unicode(substr(NEW.station_id,3,1)))%13)=0 AND c.fauna_pressure>(SELECT security FROM station_simulation_state WHERE station_id=NEW.station_id); "
                + "INSERT OR IGNORE INTO civilization_frontier_event(event_id,world_id,station_id,tick_sequence,event_type,severity,civilization_delta,fauna_delta,frontier_delta,summary) SELECT NEW.station_id||':frontier:'||NEW.last_tick,NEW.world_id,NEW.station_id,NEW.last_tick,CASE WHEN c.frontier_state='EXPANDING' THEN 'EXPANSION' WHEN c.frontier_state='ABANDONED' THEN 'ABANDONMENT' ELSE 'CONTRACTION' END,CASE WHEN c.frontier_state='ABANDONED' THEN 100 WHEN c.frontier_state='CONTRACTING' THEN 70 ELSE 20 END,CASE WHEN c.frontier_state='EXPANDING' THEN 1 ELSE -1 END,CASE WHEN c.frontier_state='EXPANDING' THEN -1 ELSE 1 END,CASE WHEN c.frontier_state='EXPANDING' THEN 1 WHEN c.frontier_state='ABANDONED' THEN -2 ELSE -1 END,CASE WHEN c.frontier_state='EXPANDING' THEN 'Stable supply and security allowed the civilian perimeter to expand.' WHEN c.frontier_state='ABANDONED' THEN 'The station lost its remaining civilian foothold and was abandoned.' ELSE 'Shortage and fauna pressure forced the civilian perimeter to contract.' END FROM station_civilization_state c WHERE c.station_id=NEW.station_id AND ((c.frontier_state='EXPANDING' AND c.surplus_ticks>0 AND c.surplus_ticks%6=0) OR (c.frontier_state='CONTRACTING' AND c.shortage_ticks>0 AND c.shortage_ticks%4=0) OR c.frontier_state='ABANDONED'); "
                + finalization + "END";
    }
}
